<!DOCTYPE html>
<html lang="zh">
<head>
	<link rel="icon" type="image/vnd.microsoft.icon" href="<?php echo static_file('images/favicon.ico')?>" />
	<meta charset="UTF-8">
	<meta name="keywords" content="<?php echo $seo['keywords']?>">
	<meta name="description" content="<?php echo $seo['description']?>">
	<meta property="og:title" content="<?php echo $seo['title']?>">
	<meta property="og:description" content="<?php echo $seo['description']?>">
	<meta property="og:image" content="<?php echo $seo['image']?>">
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<title><?php echo $seo['title'] ?></title>
	<link rel="stylesheet" href="<?php echo static_file('intro/css/style.css')?>">
	<link rel="stylesheet" href="<?php echo static_file('intro/css/animate.css')?>" data-skrollr-stylesheet>
	<link rel="stylesheet" href="<?php echo URL_ROOT.'js/jBox-0.3.2/Source/jBox.css'?>">
</head>
<body onLoad="MM_preloadImages('<?php echo static_file('intro/images/page06_01_hover.png')?>')">
<?php echo Core::settings('GOOGLE_ANALYTICS_TRACKINGCODE')?>
<div id="main">
	<!--<div class="bottom_bg"></div>-->
	<a href="<?php echo self::url()?>" class="skip"></a>
	<nav>
	    <a href="#" data-scroll="top" class="b1">
	    	<div class="s_pinple"></div>
	    	<div class="square">
	    		<div class="down"></div>
	    	</div>
	    </a>
	    <a href="#" data-scroll="page01" class="b2">
	    	<div class="s_pinple"></div>
	    	<div class="square">
	    		<div class="down"></div>
	    	</div>
	    </a>
	    <a href="#" data-scroll="page02" class="b3">
	    	<div class="s_pinple"></div>
	    	<div class="square">
	    		<div class="down"></div>
	    	</div>
	    </a>
	    <a href="#" data-scroll="page03" class="b4">
	    	<div class="s_pinple"></div>
	    	<div class="square">
	    		<div class="down"></div>
	    	</div>
	    </a>
	    <a href="#" data-scroll="page04" class="b5">
	    	<div class="s_pinple"></div>
	    	<div class="square">
	    		<div class="down"></div>
	    	</div>
	    </a>
	    <a href="#" data-scroll="page05" class="b6">
	    	<div class="s_pinple"></div>
	    	<div class="square">
	    		<div class="down"></div>
	    	</div>
	    </a>
	    <a href="#" data-scroll="page06" class="b7">
	    	<div class="s_pinple"></div>
	    	<div class="square">
	    		<div class="down"></div>
	    	</div>
	    </a>
	</nav>	
	<div id="wrapper">
		<div class="top_people03 ani" ><img src="<?php echo static_file('intro/images/people03.png')?>" height="143" width="110" alt=""></div>
		 <section id="top" data-anchor="top" class="wrap">
		 	<div id="top_p1">
		 		<div class="top_cloud"><img src="<?php echo static_file('intro/images/top_06.png')?>" height="200" width="740" alt=""></div>
		 		<div class="top_line"></div>
		 		<div class="top_people"><img src="<?php echo static_file('intro/images/people_01.png')?>" height="137" width="124" alt=""></div>
		 		<div class="top_box_t3"><img src="<?php echo static_file('intro/images/top_05.png')?>"  alt=""></div>
		 		<div class="top_box_t2"><img src="<?php echo static_file('intro/images/top_04.png')?>" alt=""></div>
		 		<div class="top_box_t1"><img src="<?php echo static_file('intro/images/top_03.png')?>"  alt=""></div>
		 		<div class="top_box_line"><img src="<?php echo static_file('intro/images/top_02.png')?>"  alt=""></div>
		 		<div class="top_box"><img src="<?php echo static_file('intro/images/top_01.png')?>" alt=""></div>
		 		<div class="top_bg05"></div>
		 		<div class="top_bg01"></div>
		 		<div class="top_bg02"></div>
		 	</div>
		 	<div id="top_p2">
		 		<div class="top_people02" data-anchor-target="#top_p2"><img src="<?php echo static_file('intro/images/people02.png')?>" height="156" width="116" alt=""></div>
		 		<div class="top_question" data-anchor-target="#top_p2"><img src="<?php echo static_file('intro/images/top_08.png')?>" height="178" width="141" alt=""></div>
		 		<div class="top_cicle"><img src="<?php echo static_file('intro/images/top_07.png')?>" height="46" width="46" alt=""></div>
		 		<div class="top_line02"></div>
		 		<div class="top_title"><img src="<?php echo static_file('intro/images/top_title.png')?>" height="218" width="496" alt=""></div>
		 		<div class="top_cloud"><img src="<?php echo static_file('intro/images/top_06.png')?>" height="200" width="740" alt=""></div>
		 		<div class="top_bg06"><img src="<?php echo static_file('intro/images/top_bg06.png')?>" height="623" width="1920" alt=""></div>
		 		<div class="top_bg07"><img src="<?php echo static_file('intro/images/top_bg07.png')?>" height="800" width="1915" alt=""></div>
		 		<div class="top_bg03"><img src="<?php echo static_file('intro/images/top_bg03.png')?>" height="1244" width="820" alt=""></div>
		 		<div class="top_bg04"><img src="<?php echo static_file('intro/images/top_bg04.png')?>"  alt=""></div>
		 		<div class="top_bg08"><img src="<?php echo static_file('intro/images/top_bg09.png')?>" height="285" width="628" alt=""></div>
				<div class="top_bg09"><img src="<?php echo static_file('intro/images/top_bg10.png')?>" height="188" width="364" alt=""></div>

		 	</div>
		 
		 </section>
		
		 <section id="page01" data-anchor="page01" class="wrap">
		 	<div class="page01_content">
		 		<div class="p1_text ani"><img src="<?php echo static_file('intro/images/page01_text.png')?>" height="302" width="441" alt=""></div>
		 		<div class="ferris ani" data-anchor-target=".page01_content"><img src="<?php echo static_file('intro/images/page01_01.png')?>" height="869" width="505" alt=""></div>
		 		
		 		<div class="p1_bg01 ani" ><img src="<?php echo static_file('intro/images/page01_bg04.png')?>" height="152" width="359" alt=""></div>
		 		<div class="mountain ani"><img src="<?php echo static_file('intro/images/page01_bg02.png')?>" height="740" width="1296" alt=""></div>
		 		<div class="p1_bg02 ani" ><img src="<?php echo static_file('intro/images/page01_bg03.png')?>" height="307" width="502" alt=""></div>
				<div class="p1_bg03"></div>
				<div class="p1_bg04"></div>				
		 	</div>
		 	
		 </section>
		 <section id="page02" data-anchor="page02" class="wrap">
		 	<div class="page02_content">
		 		
		 		<div class="p2_text ani" ><img src="<?php echo static_file('intro/images/page02_title.png')?>" height="160" width="919" alt=""></div>
		 		<div class="p2_phone02 ani" data-anchor-target=".page02_content"></div>
		 		<div class="p2_phone ani" data-anchor-target=".page02_content"></div>
		 		<div class="p2_circle ani" data-anchor-target=".page02_content"></div>
		 		
		 		<div class="mountain02 ani" ><img src="<?php echo static_file('intro/images/page02_bg02.png')?>" height="782" width="1015" alt=""></div>
		 		<div class="p2_bg01 ani" data-anchor-target=".page02_content"></div>
		 		<div class="p2_bg02 ani" data-anchor-target=".page02_content"></div>

		 	</div>

		 </section>
		 <section id="page03" data-anchor="page03" class="wrap">
		 	
		 	<div class="page03_content">
		 		<div class="p3_text ani" ><img src="<?php echo static_file('intro/images/page03_text.png')?>" height="306" width="583" alt=""></div>
		 		<div class="p3_light01 ani" data-anchor-target=".page03_content"></div>
		 		<div class="p3_light02 ani" data-anchor-target=".page03_content"></div>
		 		<div class="p3_money ani"><img src="<?php echo static_file('intro/images/page03_01.png')?>" height="184" width="101" alt=""></div>
		 		
		 		<div class="mountain03 ani" ><img src="<?php echo static_file('intro/images/page03_bg01.png')?>" height="571" width="947" alt=""></div>
		 		<div class="p3_star ani"><img src="<?php echo static_file('intro/images/page03_04.png')?>" height="220" width="423" alt=""></div>
		 		<div class="p3_bg01 ani"></div>
		 		<div class="p3_bg02 ani"></div>
		 		<div class="p3_bg03 ani"></div>
		 	</div>
		 </section>
		 <section id="page04" data-anchor="page04" class="wrap">
		 	<div class="page04_content">
		 		
		 		
		 		<div class="p4_info ani"><img src="<?php echo static_file('intro/images/page04_01.png')?>" height="640" width="467" alt=""></div>
		 		<div class="p4_text ani"><img src="<?php echo static_file('intro/images/page04_text.png')?>" height="302" width="704" alt=""></div>
		 		<div class="mountain04 ani" ><img src="<?php echo static_file('intro/images/page04_bg01.png')?>" height="853" width="1496" alt=""></div>
		 		<div class="p4_bg01 ani"></div>
		 		<div class="p4_bg02 ani"></div>
		 		<div class="p4_bg03 ani"></div>
		 	</div>
		 </section>
		 <section id="page05" data-anchor="page05" class="wrap">
		 	<div class="page05_content">
		 		
		 		<div class="p5_text02 ani"><img src="<?php echo static_file('intro/images/page05_04.png')?>" height="83" width="344" alt=""></div>
		 		<div class="p5_line ani"></div>
		 		<div class="p5_sound ani"><img src="<?php echo static_file('intro/images/page05_02.png')?>" height="59" width="54" alt=""></div>
		 		<div class="p5_text01 ani"><img src="<?php echo static_file('intro/images/page05_05.png')?>" height="163" width="349" alt=""></div>
		 		<div class="p5_map ani"><img src="<?php echo static_file('intro/images/page05_03.png')?>" height="217" width="217" alt=""></div>
		 		<div class="p5_music ani"><img src="<?php echo static_file('intro/images/page05_01.png')?>" height="486" width="459" alt=""></div>
		 		<div class="mountain05"><img src="<?php echo static_file('intro/images/page05_bg.png')?>" height="643" width="1663" alt=""></div>
		 		<div class="p5_bg01 ani"></div>
		 		<div class="p5_bg02 ani"></div>
		 		<div class="p5_bg03 ani"></div>
		 	</div>
		 </section>
		 <section id="page06" data-anchor="page06" class="wrap">
		 	<div class="page06_content">
		 		
		 		<div class="p6_appbtn ani">
		 			<a href="<?php echo Core::settings('GOOGLEPLAY_APK_URL')?>"><img src="<?php echo static_file('intro/images/page06_03.png')?>" height="66" width="229" alt=""></a><br>
		 			<a href="javascript:void(0)" onclick="ios_notice()"><img src="<?php echo static_file('intro/images/page06_04.png')?>" height="65" width="228" alt=""></a>
		 		</div>
		 		<div class="p6_text ani"><img src="<?php echo static_file('intro/images/page06_02.png')?>" height="159" width="356" alt=""></div>
		 		<div class="p6_start ani">
                <a href="<?php echo self::url()?>" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image45','','<?php echo static_file('intro/images/page06_01_hover.png')?>',1)"><img src="<?php echo static_file('intro/images/page06_01.png')?>" width="677" height="418" id="Image45"></a>
                </div>
		 		<div class="mountain06 ani"><img src="<?php echo static_file('intro/images/page06_bg.png')?>" height="268" width="1134" alt=""></div>
		 		<div class="p6_bg01 ani"></div>
		 		<div class="p6_bg02 ani"></div>
		 		
		 		<div class="p6_bg04 ani"></div>
		 	</div>
		 </section>
	</div>
</div>
<script type="text/javascript" src="<?php echo static_file('intro/js/jquery-1.11.1.min.js')?>"></script>
<script type="text/javascript" src="<?php echo static_file('intro/js/skrollr.stylesheets.js')?>"></script>
<script type="text/javascript" src="<?php echo static_file('intro/js/skrollr.js')?>"></script>
<script type="text/javascript" src="<?php echo static_file('intro/js/animate.js')?>"></script>
<script type="text/javascript" src="<?php echo URL_ROOT.'js/jBox-0.3.2/Source/jBox.min.js'?>"></script>
<script>
function MM_swapImgRestore() { //v3.0
	  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_preloadImages() { //v3.0
	  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
	    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
	    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_findObj(n, d) { //v4.01
	  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
	    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
	  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
	  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
	  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_swapImage() { //v3.0
	var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
	if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
	
function ios_notice() {
	var siteModal = new jBox('Modal', {
		delayOpen: 200,
		title: '<span style="display: inline-block;height: 100%;vertical-align: middle;"></span><img style="vertical-align: middle;" src="<?php echo static_file('images/info.png')?>">',
		maxWidth: 600,
		minWidth: 100,
	}).setContent('<?php echo _('Coming Soon!')?>').open();
}
</script>
</body>
</html>