<?php echo $form?>
<script>
$(function() {
	$('#form').validate({
		rules: {},
		submitHandler: function() {
			if (!$('#lang_id').val()) {
				formerror('<?php echo _('[Lang] is required')?>');
				return;
			}
			
			if (!$('#admingroup_id').val()) {
				formerror('<?php echo _('[Admin Group] is required')?>');
				return;
			}
			
			$.post('<?php echo $action?>', {
				keyword: $('#keyword').val(),
				lang_id: $('#lang_id').val(),
				admingroup_id: $('#admingroup_id').val(),
				type: $('input[name="type"]:checked').val(),
				value: $('input[name="type"]:checked').val() == 'editor'? CKEDITOR.instances['value-editor'].getData() : $('#value-textarea').val(),
				remark: $('#remark').val(),
			}, function(r) {
				r = $.parseJSON(r);
				switch (r.result) {
					case 0:formerror(r.message);break;
					case 1:formconfirm(r);break;
				}
			});
		}
	});

	value_toggle();
	
	$('input[name="type"]').on('click', function() {
		value_toggle();
	});
	
	$('#lang_id').on('keyup change', function() {
		$.post('<?php echo self::url(M_CLASS, 'extra0')?>', {
			keyword: $('#keyword').val(),
			lang_id: $(this).val(),
		}, function(r) {
			r = $.parseJSON(r);
			switch ($('input[name="type"]:checked').val()) {
				case 'textarea':
					$('#value-textarea').val(r.data.value);
					break;

				case 'editor':
					CKEDITOR.instances['value-editor'].setData(r.data.value || '');
					break;
			}
		});
	});
});

function value_toggle() {
	$('tr[id^="value-tr"]').hide();
	$('tr[id="value-tr-' + $('input[name="type"]:checked').val() + '"]').show();
}
</script>