<div id="alert_box" class="set_box">
	<div id="alert_bg" class="set_box_bg"></div>
	<div  class="set_box_in">
		<div  class="set_box_top">
			<div id="close_alert" class="close_box"><a href="javascript:void(0)">X</a></div><?php echo _('Password changed'); ?>
		</div>
		<div  class="set_box_content">
			<ul>
				<form id="js_user_password_form">
					<li><input type="password" name="old_pass" placeholder="<?php echo _('Current'); ?>"></li>
					<li><input type="password" name="new_pass" placeholder="<?php echo _('New'); ?>"></li>
					<li class="bottom_big"><input type="password" name="new_pass_check" placeholder="<?php echo _('Retype New'); ?>"></li>
					<li><a href="javascript:void(0)" class="used" onclick="$('#js_user_password').trigger('click')"><?php echo _('Done editing'); ?></a></li>
					<li><p id="password_msg" class="red"></p></li>
					<img style="width:20px;height:20px;display:block; margin:auto; display:none;" class="loading_img " src="<?php echo static_file('images/loading.gif')?>">
					<input style="display:none;" id="js_user_password" type="submit">
				</form>
			</ul>
		</div>
	</div>
</div>

