<div id="alert_box_new">
    <div id="alert_bg_new"></div>
    <div id="alert_box_area">
        <div id="alert_top_new">
            <div id="alert_top_title"><?php echo _('檢舉此作品'); ?></div>
            <div id="alert_close_btn"><i class="fa fa-times"></i></div>
        </div>
        <div id="alert_content_new">
            <div id="alert_items">
                <?php
				//echo 'report.php:'.date('m/d/Y h:i:s a', time());
				if(count($reportintent) > 0) {
				foreach($reportintent as $k => $v){
                        $desc = '';
                        if ($k == 6) $desc = '<div id="alert_desc_items0'.($k+1).'">
                                                <p>如果您確信有人在未獲授權的情況下，擅自在pinpinbox 上發佈您受版權保護的作品，這時可以提出侵犯版權通知。只有著作權人或其授權代理人可以提交這類要求。</p>
                                                <p>如要向 pinpinbox 通報涉嫌侵權的，最簡單快速的做法就是填寫網路表單。建議使用桌機和筆電填寫這份表單；在行動裝置及平板電腦上操作會較為繁複。</p>
                                                <p>如果您選擇提出侵權通知，要求我們移除相關內容，代表您採取了正式的法律程式。</p>
                                                <p class="red">請勿提出不實聲明，當送出此項檢舉即表示您已閱讀、瞭解並同意上述說明。濫用這項程式可能會導致您的帳戶遭到停權，您本人也可能因此需要承擔其他法律責任。</p>
                                              </div>';
                        echo '<div id="alert_items0'.($k+1).'">
                            <div id="alert_radio_items0'.($k+1).'">
                                <input type="radio" value="'.$v['reportintent_id'].'" id="input_0'.($k+1).'" name="report">
                                <label for="input_0'.($k+1).'">'.\Core\Lang::i18n($v['name']).'</label>
                            </div>
                            '.$desc.'
                        </div>';
                    }
                }
                ?>
            </div>

            <div id="alert_desc_btn">
                <div class="btn_new btn_pink" id="alert_btn"><?php echo _('送出'); ?></a></div>
            </div>
        </div><!-- #alert_content_new -->
    </div><!-- #alert_box_area -->
</div><!-- #alert_box_new -->
