<?php echo $index?>
<script>
$(function(){
    $('#grid').kendoGrid({
    	columns: [
			{field: '<?php echo M_CLASS?>_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{field: 'name', attributes: {'class': 'string'}},
			{field: 'image', attributes: {'class': 'image'}, encoded: false},
			{field: 'image_promote', attributes: {'class': 'image'}, encoded: false},
			{field: 'vote', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{field: 'contribution', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{field: 'starttime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
			{field: 'endtime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
			{field: 'viewed', attributes: {'class': 'number'}},
			{field: 'act', attributes: {'class': 'enums act-#:act#'}},
			{field: 'modifytime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
			{
				title: 'eventjoin',
				columns: [
					{title: '@count', field: 'eventjoinX', attributes: {'class': 'number'}, filterable: false, sortable: false}
				]
			},
			{
				title: 'eventvote',
				columns: [
					{title: '@count', field: 'eventvoteX', attributes: {'class': 'number'}, filterable: false, sortable: false}
				]
			},
		],
		dataBinding: function(e) {},
		dataBound: function(e) {},
        dataSource: new kendo.data.DataSource({
    		page: 1,
    		pageSize: gridpageSize,
    		serverPaging: true,
    		serverSorting: true,
    		serverFiltering: true,
    		transport: {
    			read: {
    				dataType: 'json', //"jsonp" is required for cross-domain requests; use "json" for same-domain requests
    				type: 'POST',
    				url: '<?php echo self::url(M_CLASS, 'json')?>',
    			}
    		},
    		schema: {
    			data: function(r){return r.data;},
    			total: function(r){return r.total;}
    		},
    		sort: {field: 'modifytime', dir: 'desc'}
    	}),
        filterable: true,
        height: gridheight,
        pageable: {
            refresh: true,
            input: true,
            pageSize: gridpageSize,
            pageSizes: gridpageSizes,
        },
        reorderable: true,
        resizable: true,
        selectable: true,
        sortable: true,
		toolbar: [
		  	{template: '<a class="k-button" onclick="grid_toolbar_add(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'form', array('act'=>'add'))?>\')"><span class="k-icon k-i-plus"></span></a><a class="k-button" onclick="grid_toolbar_edit(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'form', array('act'=>'edit'))?>\', [\'<?php echo M_CLASS?>_id\'])"><span class="k-icon k-i-pencil"></span></a>'},
		],
    });
});
</script>