<!-- header區塊開始 -->
<?php include('diy_header.phtml');?>
<!-- header區塊結束 -->

<!-- 相本-進階設定區塊開始 -->
<?php include('album_setting.phtml');?>
<!-- 相本-進階設定區塊結束 -->

<!-- 相片-進階設定區塊開始 -->
<?php include('photo_setting.phtml');?>
<!-- 相片-進階設定區塊結束 -->

<!-- 影片上傳設定區塊開始 -->
<?php include('media_upload.phtml');?>
<!-- 影片上傳設定區塊結束 -->

<!-- 協作區塊開始 -->
<?php include('share.phtml');?>
<!-- 協作區塊結束 -->

<!-- 主要畫面開始 -->
<div id="editor_content">
	<div id="editor_info" >
		<h2><?php echo _('Create'); ?></h2>
		<span><?php echo $diyPageTips; ?></span>
	</div>
	<div id="editor_wrap">
		<div id="edit_control">
			<ul>
				<?php echo $diy['diy']['cooperate_btn'] ?>                
                <li><a href="javascript:void(0)" style="font-size: 14px;" class="con_icon02 preivewlists"><?php echo _('Album preview'); ?></a></li>
				<?php 
					if($diy['diy']['upload_type']) {
						echo '<li><a href="javascript:void(0)" class="con_icon04">'._('Templates').'</a></li>';
						echo '<li><a href="javascript:void(0)" id="ctr-btn" onclick="croppic()" alt="false" class="con_icon03">'._('Crop photo').'</a></li>';
					}
				?>
			</ul>
		</div>
		<div id="edit_home">
			<ul>
				<li>
					<a style="padding-top:10px;font-size:14px;" href="<?php echo self::url('template', 'index') ?>" ><i class="fa fa-sign-out fa-lg rotate_180" style="font-size:24px;margin-bottom: 8px;"></i><br><?php echo _('離開'); ?></a>
				</li>
			</ul>
		</div>
		<div id="editpage" class="editpage"><span class="edit_num1"><?php echo $edit_num; ?></span> / <span class="edit_num2"><?php echo $album_limit; ?></span></div>
			<?php if(!$diy['diy']['upload_type']) { ?>
				<div id="tem_content" style="padding:3px 150px;">
					<div id="tem_upload">
						<ul>
							<li>
								<!-- The file upload form used as target for the file upload widget -->
								<form id="fileupload_fastupload" action="javascript:void(0)" method="POST" enctype="multipart/form-data" name="uploadform" data-ng-app="demo" data-ng-controller="DemoFileUploadController" data-file-upload="options" data-ng-class="{'fileupload-processing': processing() || loadingFiles}">
									<!-- Redirect browsers with JavaScript disabled to the origin page -->
									<noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
									<!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
									<div class="row fileupload-buttonbar">
										<div style="width:90%;">
											<span class="btn btn-success fileinput-button" ng-class="{disabled: disabled}" style="background-color:#00acc1;border-color: #00acc1;" onclick="show_media_view()">
												<i class="glyphicon glyphicon-plus"></i>
												<span><?php echo _('上傳影片'); ?></span>												
											</span>
											<!-- The fileinput-button span is used to style the file input field as button -->
											<span class="btn btn-success fileinput-button" ng-class="{disabled: disabled}" style="background-color:#00acc1;border-color: #00acc1;">
												<i class="glyphicon glyphicon-plus"></i>
												<span><?php echo _('上傳圖檔或PDF'); ?></span>
												<input type="file" name="files[]" multiple ng-disabled="disabled" accept="image/gif, image/jpeg, image/jpg, image/png, application/pdf">
											</span>

											<!-- -->
											<button type="button" id="before_upload" class="btn btn-primary start" onclick="before_fileupload()">
												<i class="glyphicon glyphicon-upload"></i>
												<span><?php echo _('Start Uploading'); ?></span>
											</button>

											<button type="button" id="uploadstart" class="btn btn-primary start" data-ng-click="submit()" style="display:none;">
												<i class="glyphicon glyphicon-upload"></i>
												<span><?php echo _('Start Uploading'); ?></span>
											</button>
											<!-- The global file processing state -->
											<span class="fileupload-process"></span>
										</div>
										<div class="progress" style="display:none; width:40%;">
											<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="70"	aria-valuemin="0" aria-valuemax="100" style="width:0%;background-color:#17b1ad;">
												<span class="sr-only" style="color:white;"></span>
											</div>
										</div>
									</div>
									<!-- The table listing the files available for upload/download -->
									<table class="table table-striped files ng-cloak" style="margin-top:25px;">
										<tr data-ng-repeat="file in queue" data-ng-class="{'processing': file.$processing()}" state="pretreat">
											<td data-ng-switch data-on="!!file.thumbnailUrl">
												<div class="preview" data-ng-switch-when="true">
													<a data-ng-href="{{file.url}}" title="{{file.name}}" download="{{file.name}}" data-gallery><img data-ng-src="{{file.thumbnailUrl}}"></a>
												</div>
												<div class="preview" data-filesType="{{file.type}}"  data-ng-switch-default data-file-upload-preview="file"></div>
											</td>
											<td>
												<p class="name" data-ng-switch data-on="!!file.url">
													<span data-ng-switch-when="true" data-ng-switch data-on="!!file.thumbnailUrl">
														<a data-ng-switch-when="true" title="{{file.name}}" data-gallery>{{file.name}}</a>
														<a data-ng-switch-default data-ng-href="{{file.url}}" title="{{file.name}}" download="{{file.name}}">{{file.name}}</a>
													</span>
													<span data-ng-switch-default>{{file.name}}</span>
												</p>
												<strong data-ng-show="file.error" style="color:red;" class="error text-danger">{{file.error}}</strong>
												<strong class="success" style="color:#17b1ad;font-weight:bold;"></strong>
											</td>
											<td>
												<p class="size">{{ (file.size/1048576).toFixed(2) }} MB </p>
											</td>
											<td>
												<button type="button" class="btn btn-warning cancel common" data-ng-click="file.$cancel()" data-ng-hide="!file.$cancel" data-act="cancelfile">
													<i class="glyphicon glyphicon-ban-circle"></i>
													<span><?php echo _('Cancel Uploading'); ?></span>
												</button>
												<button data-ng-controller="FileDestroyController" type="button" class="btn btn-danger destroy" data-ng-click="file.$destroy()" data-ng-hide="!file.$destroy">
													<i class="glyphicon glyphicon-trash"></i>
													<span>Delete</span>
												</button>
											</td>
										</tr>
									</table>
								</form>
							</li>
						</ul>
					</div>
				</div>
			<?php } ?>
			<?php if($diy['diy']['upload_type']) { ?>
			<div id="edit_box">
				<div id="edit_in">
					<div id="temp_2">
						<!-- frame位置 -->
					</div>	
				</div>
			</div>
			<?php } ?>
		</div>
	</div>
</div>
<!-- 主要畫面結束 -->

<!-- 版型選擇區塊開始 -->
<div class="menu slide-menu-bottom">
	<?php 
	/**
	 * 套版模式引入模板清單
	 * 快速建立模式只引入按鈕
	 */
	//快速建立模式用的下方按鈕
	$layout_select_frame = '';

	if($diy['diy']['upload_type']) {
		//套板模式物件
		$layout_fream = null;
		foreach ($frame as $v0) { $layout_fream .= '<li id="frame'.$v0['frame_id'].'"><a onclick="set_frame('.$v0['frame_id'].')" href="javascript:void(0)"><img src="'.$v0['url'].'"></a></li>'; }
		
		$layout_select_frame = '<div class="menu_info">
					<a href="javascript:void(0)" class="changeto1">'._('Templates').'</a>
					<a href="javascript:void(0)" class="changeto2">'._('Albums page').'</a>
					<span><img src="'.static_file('images/object.png').'" height="20" width="20">'._('Templates can be altered any moment you edit the albums.').'</span>
				</div>
				<div class="menu_list" id="temp_list">
					<div id="tem_pic">
						<ul>'.$layout_fream.'</ul>
					</div>
				</div>';
	}

	echo $layout_select_frame;
	?>
</div>
<!-- 版型選擇區塊結束 -->

<!-- 已完成相片列表開始 -->
<div class="menu02 slide-menu-up ">
	<div class="menu_info">
		<?php if($diy['diy']['upload_type']) echo '<a href="javascript:void(0)" class="changeto1">'._('Templates').'</a>'; ?>
		<a href="javascript:void(0)" class="select"><?php echo _('Albums page'); ?></a>
		<a href="javascript:void(0)" onclick="save_album()" class="save start"><?php echo _('發佈作品') ?></a>
		<a href="javascript:void(0)" onclick="<?php echo (!$user['sort']) ? 'no_right' : 'load_album_setting'?>(this)" class="<?php echo (!$user['sort']) ? null : 'common' ?> music_open" data-act="album_setting"></a>
		
		<?php if($diy['user']['identity']) { ?>
		<span><img src="<?php echo static_file('images/object.png'); ?>" height="20" width="20"><?php echo _('Change album order by dragging the pictures using your mouse！'); ?></span>
		<span style="margin: 0px 1.5%;"> <input style="height:20%;margin:0 0.5%" name="previewPageType" value="all" type="radio" <?php echo ($album['preview_type'] == 'all') ? 'checked' : null ;?>>預覽全開</span>
		<span> <input style="height:20%;margin:0 0.5%" name="previewPageType" value="part" type="radio" <?php echo ($album['preview_type'] == 'part') ? 'checked' : null ;?>>前<input style="height:35%; width:3%;" name="previewPageNum" type="number" value="<?php echo $album['preview_page_num'] ?>" min="0" max="200">頁可供預覽</span>
		<?php } ?>
	</div>
	<div class="menu_list" id="album_list">
		<?php
		foreach ($photo as $k0 => $v0) {
			echo '
				<div class="menu_item">
					<ul id="links" style="min-height:215px;">
						<li>
							<span class="file-num">p'.($k0 + 1).'</span>
							<span class="type">'.$v0['type_photo'].'</span>
							<span class="music">'.$v0['music_image_thumbnail'].'</span>
							<span class="description">'.$v0['description_image_thumbnail'].'</span>
						</li>
						<li title="'._('建立者').':'.$v0['user_name'].'" >
							<img class="thumbnail" style="max-height:130px;" src="'.$v0['image_url_thumbnail'].'" onclick="browseKit_diy('.$k0.')">
						</li>
						<li class="edit_img">
							<a href="javascript:void(0)" title="新增資訊" onclick="'.$v0['photo_setting_onclick'].'(this)" class="e2 more_setting"></a>
							<a class="e3"  href="javascript:void(0)" onclick="'.$v0['delete_onclick'].'(this)" title="刪除"></a>
							<img id="edit_'.($k0 + 1).'" class="depot" data-width="'.getimagesize($v0['image_url'])[0].'" data-height="'.getimagesize($v0['image_url'])[1].'" data-usefor="'.$v0['usefor'].'" data-tag="'.$v0['image'].'" data-photo_id="'.$v0['photo_id'].'" style="display:none;" src="'.$v0['image_url'].'">
						</li>
					</ul>
				</div>';
		}
		?>
		<div class="menu_item">
			<a onclick="$('<?php echo $diy['diy']['plus_btn'] ?>').trigger('click');" href="javascript:void(0)">
				<div class="menu_add">
					<p class="editpage">
						<span><?php echo $edit_num; ?></span> / <span><?php echo $album_limit; ?></span>
					</p>
				</div>	
			</a>
		</div>
	</div>
</div>
<!-- 已完成相片列表結束 -->

<div tag="true" id="aviary"></div>
<div id="mask" class="maskclose"></div>
<div id="mask02" class="maskclose"></div>
<script src="https://dme0ih8comzn4.cloudfront.net/js/feather.js"></script>

<script type="text/javascript">
var photoChangeSettings = false,
	photoExchange = false,
	filesQueue=0, maxUploadFiles = 50,
	checkedBoxList =[],
	$_obj0 = $('#type_p3 div[data-tag="photousefor-amount"]'),
	$_obj1 = $('#type_p3 div[data-tag="photousefor-description"]'),
	$_obj2 = $('#type_p4 div[data-tag="photousefor-description"]'),
	$_obj3 = $('#type_p3 div[data-tag="photousefor-name"]'),
	$_obj4 = $('#type_p3 div[data-tag="photousefor-exchangeImageBtn"]');

var video_file = $("#video_demo_file")[0],audio = new Audio(),croppicAct,croppicResponse,
croppicJudge = function(r) {
	switch (r.result) {
		case 1:
			break;
		case 2:
			_jBox(r, 'login');
			break;
		case 3:
			_jBox(r, 'albumProcess');
			break;
		default:
			_jBox(r, 'error');
			break;
	}
};

var croppicContainerEyecandyOptions = {
	uploadUrl: '<?php echo self::url('diy', 'img_save_to_file', ['album_id'=>$album['album_id']])?>',
	cropUrl: '<?php echo self::url('diy', 'img_crop_to_file', ['album_id'=>$album['album_id']])?>',
	rotateFactor: 10,
	rotateControls: true,
	onError: function(data) {
		croppicResponse = $.parseJSON(data);
	
		//有 error 的情況下，upload 會跑到這裡就停止，但 crop 不會，為使 jBox 不打結因此處理
		if (croppicAct == 'upload') {
			croppicJudge(croppicResponse);
			croppicResponse = null;
		}
	},
	onAfterImgCrop:	function() {
		//因為在有 error 的情況下，crop 仍會跑到這裡，為使 jBox 不打結因此處理
		if (croppicResponse) {
			croppicJudge(croppicResponse);
			croppicResponse = null;
			return;
		}
		$('#' + this.id).find('div.cropControls>i.cropControlUpload').css('display', 'none');
		$('#' + this.id).find('div.cropControls>i.cropControlRemoveCroppedImage').data('imgUrl', this.croppedImg[0].src);
		
		make_tooltip('.cropControls .cropControlRemoveCroppedImage', '<?php echo _('Reset')?>');
	
		var upload_count = $('.croppedImg').length, //已上傳
			empty_count = $('.crop_upload').length;	//需上傳
		
		if (upload_count == empty_count) {
			$('#ctr-btn').removeClass('con_icon03').addClass('con_icon05').html('<?php echo _('Save page')?>');
		}
	},
	onAfterImgUpload: function() {
		make_tooltip('.cropControls .cropControlZoomMuchIn', '<?php echo _('ZoomMuchIn') ?>');
		make_tooltip('.cropControls .cropControlZoomIn', '<?php echo _('ZoomIn') ?>');
		make_tooltip('.cropControls .cropControlZoomOut', '<?php echo _('ZoomOut') ?>');
		make_tooltip('.cropControls .cropControlZoomMuchOut', '<?php echo _('ZoomMuchOut') ?>');
		make_tooltip('.cropControls .cropControlRotateLeft', '<?php echo _('RotateLeft') ?>');
		make_tooltip('.cropControls .cropControlRotateRight', '<?php echo _('RotateRight') ?>');
		make_tooltip('.cropControls .cropControlReset', '<?php echo _('Reset') ?>');
		$('.cropImgWrapper').css('opacity', '0');
		$('.con_icon03').addClass('active');
		$('.cropControlsCrop').each(function(k, v){
			var controlcrop = $(this);
			controlcrop.attr('id', controlcrop.parent('div').attr('id'));
		});

		//reset 
		$('.cropControlReset').on('click' , function(){
			var obj = $('div#'+$(this).parent('div').attr('id'));
			obj.find('img').remove();
			obj.find('i.cropControlRemoveCroppedImage').remove();
			$('.jBox-Tooltip').css('display', 'none');
			make_tooltip('.cropControls .cropControlUpload', '<?php echo _('Upload Image') ?>');
		});
	},
	onBeforeImgCrop: function() {
		croppicAct = 'crop';
	},
	onBeforeImgUpload: function() {
		croppicAct = 'upload';
	},
	onReset: function() {
		$.post('<?php echo self::url('diy', 'img_reset')?>', {
			album_id: '<?php echo $album['album_id']?>',
			imgUrl: this.imgUrl,
		}, function(r) {
			r = $.parseJSON(r);
			switch (r.result) {
				case 1:
					break;
				case 2:
					_jBox(r, 'login');
					break;
				case 3:
					_jBox(r, 'albumProcess');
					break;
				default:
					_jBox(r, 'error');
					break;
			}
		});
		$('.con_icon03').removeClass('active');
	},
	imgEyecandy: true,				
	loaderHtml: '<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div>',
};

window.onbeforeunload = function() { 
	$.post('<?php echo self::url('diy', 'onBeforeUnLoadSave') ?>', {
		album_id : <?php echo $album['album_id'] ; ?>,
	}, function(r) {
		r = $.parseJSON(r);
		switch (r.result) {
			case 1:
				return true;
				break;
			default : break;
		}
	});
}

var upload_data = [];

$(function(){
	<?php 
	$frame_id = (!empty($frame)) ? $frame[0]['frame_id'] : null;
	if ($diy['diy']['upload_type']) echo 'set_frame(\''.$frame_id.'\');' ;
	
	if (!empty($_GET['upload']) && $_GET['upload'] == 'true') {
		echo '$(\'.con_icon02\').trigger(\'click\');';
		
		//快速建立在此時將 album.state update 為 process
		if (!empty($album['album_id'])) Model('album')->where([[[['album_id', '=', $album['album_id']]], 'and']])->edit(['state'=>'process']);
		
		$param = query_string_parse(); unset($param['upload']);
		echo 'window.history.replaceState({}, "", "' . parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) . '?' . http_build_query($param, '', '&') . '");';
	}
	?>

	$(document).on('input', '#photo_form_enter', function(){
	    photoChangeSettings = true;
	}).on('input', '#type_p4 input[type="number"]', function(){slotPossibilityReflesh();});
	
	//搜尋框增加按鈕清除內容
	$(".share_search").addClear();
	$('li.video_upload.film_content').on('mouseout', function(){video_demo_file.pause();});
	$("#more_tab").easytabs({animate: true,animationSpeed: 80,updateHash: false,});
	$('.etabs02 a').on('click', function(e) {
		var currentAttrValue = $(this).attr('href'), usefor =  $(this).parent('li').attr('name');
        datepickerInitial();
		if (currentAttrValue == '#type_p4' && $('#more_enter a').data('usefor') != 'slot') {
            $.post('<?php echo self::url('diy', 'slot_point')?>', {
                album_id: '<?php echo $album['album_id']?>',
                photo_id: $('#more_enter a').data('photo_id'),
            }, function (r) {
                r = $.parseJSON(r);
                if (r.data) {
                    $('#type_tab ' + currentAttrValue).fadeIn().siblings().hide();
                    $(this).parent('li').addClass('active').siblings().removeClass('active');
                    $('#more_enter').children('a').data('usefor_save', usefor);
                    e.preventDefault();
                } else {
                    _jBox({message: '<?php echo _('P點不足');?>'}, 'error');
                    $('.etabs02').children('li[name=' + $('#more_enter a').data('usefor') + ']').removeClass('active').children('a').trigger('click');
                }
            });
        } else {
            $('#type_tab ' + currentAttrValue).fadeIn().siblings().hide();
            $(this).parent('li').addClass('active').siblings().removeClass('active');
            $('#more_enter').children('a').data('usefor_save', usefor);
            e.preventDefault();
        }
    });

	$('#album_list').sortable({
		cursor: "move",
		opacity: 0.8,
		items: '.menu_item:not(:last)',
		containment: 'parent',
		helper : 'clone',
		create : function( event, ui) {	<?php if(!$user['sort']) echo '$(\'#album_list\').sortable("destroy");'; ?>},
		update: function(event, ui) {
			var o_photo = [];
			$('.menu_item').each(function(k0, v0) {
				$(v0).find('.file-num').text('p' + (k0 + 1));
				if(k0 == 0) {
					$(v0).find('.previewCbox').data('cbox', 'locked').prop("checked", true);
				}else {
					$(v0).find('.previewCbox').data('cbox', 'unlocked');
				}

				o_photo[k0] = {
						photo_id: $(v0).find('img.depot').data('photo_id'),
						sequence: k0,
				};
				
				$(v0).find('img.thumbnail').attr('onclick', 'browseKit_diy('+k0+')');
			});
			
			$.post('<?php echo self::url('diy', 'sorted')?>', {
				album_id: '<?php echo $album['album_id']?>',
				photo: o_photo,
			}, function(r) {
				r = $.parseJSON(r);
				switch (r.result) {
					case 1:
						break;
					case 2:
						_jBox(r, 'login');
						break;
					case 3:
						_jBox(r, 'albumProcess');
						break;
					default:
						_jBox(r, 'error');
						break;
				}
			});
		},
	});

	<?php echo (!empty($audio_default['none']['js'])) ? $audio_default['none']['js'] : null; ?>
	<?php echo (!empty($audio_default['singular']['js'])) ? $audio_default['singular']['js'] : null; ?>
	<?php echo (!empty($audio_default['plural']['js'])) ? $audio_default['plural']['js'] : null; ?>

	$('#editor_wrap').css({'height':'auto', 'min-height':'798px'});

	/**	
	 * 螢幕大小不同會造成視窗顯示不完整, 故依照取得的解析度調整載入影片的視窗大小
	 */
	var _width = screen.width, _height = screen.height, _screen, _MediaElementPlayerSize = {'width':320, 'height':240};
	if(_width>1600) {
		// > 22吋桌上螢幕
		_screen = 'large';
	} else if (_width = 1366) {
		// > 15吋筆電螢幕
		_screen = 'laptop';
	};

	switch(_screen) {
		case 'large' : break;
		case 'laptop' :
			_MediaElementPlayerSize = {'width':320, 'height':200};
			break;
		default :
			break;
	}
	$('#media_demo_file, #video_demo_file').attr(_MediaElementPlayerSize);

	$('#fileupload_fastupload')
		.bind('fileuploadadd', function (e, data) {})
		.bind('fileuploadchange', function (e, data) {
			filesQueue += data.files.length;
			if(filesQueue > 50) { $('#before_upload').find('span').html('<?php echo _('待上傳數量 : ') ?>'+filesQueue); }
	});

	var nicesx1 = $(".search_result").niceScroll({
	    touchbehavior: true,
	    enablemousewheel: true,
	    cursorcolor: "#c4c4c4",
	    cursoropacitymax: 1,
	    cursorwidth: 8,
		autohidemode:true
	});

	var nicesx2 = $(".invited_item_list").niceScroll({
	    touchbehavior: true,
	    enablemousewheel: false,
	    cursorcolor: "#c4c4c4",
	    cursoropacitymax: 1,
	    cursorwidth: 8,
		autohidemode:true
	});


	$('.search_qrcode').jBox('Tooltip', {
		content: '<div style="text-align:center;"><img src="<?php echo $album['cooperation_qrcode'] ?>"><br>被邀請的用戶預設為瀏覽者</div>',
		closeOnMouseleave: true
	});
});

function datepickerInitial() {
    var dateFormat = "yy-mm-dd";
    $('.datepicker').datetimepicker({
        defaultDate: "+1w",
        changeMonth: true,
        numberOfMonths: 1,
        dateFormat: dateFormat
    })
}

function before_fileupload() {
	var obj = $('#before_upload'), failFileName = [], fileNameStr='', album_left = 0,
		block_box =  _jBox({'message':'<p><?php echo _('準備上傳檔案中...') ?></p>'} , 'blockCustomMsg');
	//檢查數量 & 錯誤訊息
	obj.queue('before_upload', function(next) {
		block_box.open();
		
		$('strong.text-danger').each(function(k, v){
			if($(this).html().length > 0) {
				_thisFileName = $(this).siblings('p.name').find('span').html();
				failFileName.push(_thisFileName);
			}
		})

		if(failFileName.length > 0) {
			for (var i = failFileName.length - 1; i >= 0; i--) {
				fileNameStr += '<p>'+failFileName[i]+'</p>';
			}
			tips_box = _jBox({'message':'檔案大小超過上限：'+fileNameStr} , 'error');
			obj.clearQueue('before_upload');
			block_box.close();
		} else {
			$.post('<?php echo self::url('diy', 'current_photo_num') ?>' , {
				album_id : '<?php echo $album['album_id'] ?>',
			}, function(r) {
				r = $.parseJSON(r);

				var upload_count = $('table.files').find('tr').length , pdfFilescount = $('div[data-filesType="application/pdf"]').length;
				if(upload_count > r.data.album_limit) {
					var m = {'message': '<?php echo _('The photo quantity is beyond the limit') ?><br><?php echo _('剩餘可用') ?>:'+r.data.album_limit+'<br><?php echo _('目前上傳') ?>:'+upload_count };
					_jBox(m,'info');
					block_box.close();
					obj.clearQueue('before_upload');
				}else if(upload_count > maxUploadFiles) {
					block_box.close();
					var m = {'message': '<?php echo _('The photo quantity is beyond the limit') ?><br><?php echo _('上傳上限') ?>:'+maxUploadFiles+'<br><?php echo _('目前上傳') ?>:'+upload_count };
					_jBox(m,'info');
					obj.clearQueue('before_upload');
				}else{
					album_left = r.data.album_left;
					delayExecute(
						function() {
                            // 190103 - 檔案過大的圖無法產生預覽，先不檢查縮圖將條件設為 true 上傳 - Mars
						    // var n = ($('div[data-file-upload-preview="file"').find('canvas').length+pdfFilescount), m = $('tr.ng-scope[state="pretreat"]').length;
							return true;
						},
						function() {
                            next();
						},
					);
				}
			});
		}
	});

	//檢查是否存在其他process相本,若有的話則直接儲存
	obj.queue('before_upload', function(next){
		$.post('<?php echo self::url(M_CLASS, 'save_album_ajax')?>' , {
			album_id: '<?php echo $album['album_id']?>',
		}, function(r) {
			r = $.parseJSON(r);
			switch (r.result) {
				case 0 : 
					_jBox(r, 'error');
				break;
				case 1 : 
					_jBox(r, 'success');
				break;
				case 2 : 
					next();
				break;
			}
		});
	});

	//上傳相片
	obj.queue('before_upload', function(next){
		//快速建立
		block_box.setContent('<div class="content"><p><?php echo _('正在上傳檔案...') ?></p><p style="text-align: center;"><img src="<?php echo static_file('images/loading.gif'); ?>"></p><p style="text-align: center;">(請勿關閉視窗)</p></div>');
		$('#fileupload_fastupload').fileupload({
			dataType: 'json',
			url: '<?php echo self::url('diy', 'upload', ['album_id'=>$album['album_id']])?>',
			sequentialUploads : true,
			start: function(e, data) {  upload_data =[]; },
			submit: function(e, data) { if (!$('tr.ng-scope[state="pretreat"]').length) return false; },
			success: function(result, textStatus, jqXHR) { },
			error: function(jqXHR, textStatus, errorThrown) { 
				block_box.close();
				var m = {'message': '<?php echo _('檔案上傳失敗, 請重新上傳') ?>', 'redirect': '<?php echo self::url('diy', 'index', ['album_id'=>$album['album_id']]) ?>' };
				_jBox(m,'error');
			},
			progressall: function(e, data) {
				var progressall = parseInt(data.loaded / data.total * 100, 10);
				$('.progress').slideDown();
				$('.progress>.progress-bar').css('width', progressall + '%');
				$('.sr-only').text(progressall + '%');
				if (progressall == 100) {
					setTimeout(function() {
						$('.progress').slideUp();
						$('.progress>.progress-bar').css('width','0%');
						$('.sr-only').text('0%');
					}, 2000);
				}
			},
			done: function(e, data) {
				if(data.result.result > 2 ) window.onbeforeunload = null;
				switch (data.result.result) {
					case 0:
                        data.result.redirect = '<?php echo self::url('diy', 'index', ['album_id'=>$album['album_id']]) ?>';
						_jBox(data.result, 'error');
						break;
					case 1:
						upload_data.push(data.result.data);
						$('tr.ng-scope[state="pretreat"]').each(function() {
							$(this).attr('state', 'success').find('strong.success').text('<?php echo _('Upload success.')?>').end().find('button.cancel').hide();
						});
						if ( $('table.files').find('tr').length == upload_data.length ) {
							var countUploadData = [].concat.apply([], upload_data);
							if (album_left < countUploadData.length) {
								_jBox({
									'message' : '<p><?php echo _('可用相片剩餘數量不足, 請重新上傳')?></p>',
									'redirect':'<?php echo self::url('diy', 'index', ['album_id'=> $album['album_id']]) ?>'
								}, 'error');
								window.onbeforeunload = null;
							} else {
								next();
							}
						}
						break;
					case 2:
						_jBox(data.result, 'login');
						break;
					case 3:
						_jBox(data.result, 'error');
						break; 
					case 4:
						_jBox(data.result, 'error');
						break;
					case 5:
						_jBox(data.result, 'error');
						break;
				}
			},
		});
		$('#uploadstart').trigger('click');	
	});

	//儲存相本
	obj.queue('before_upload', function() {
		if (upload_data.length == 0) {
			block_box.close();
			_jBox({'message': '<?php echo _('You are required to upload the photo profile first.')?>'}, 'info');
		} else if(upload_data.length > <?php echo $album_limit ?>) {
			block_box.close();
			_jBox({'message': '<?php echo _('The photo quantity is beyond the limit')?>'}, 'info');
		}else {
			var CboxId = [], photoData = [].concat.apply([], upload_data);
			$('.previewCbox').each(function(k, v){
				if($(v).prop('checked')) CboxId.push($(v).data('photo_id'));
			});

			$.ajax({
				url: '<?php echo self::url('diy', 'save_upload', ['album_id'=>$album['album_id']])?>',
				type: 'POST',
				data: ({
					album_data: JSON.stringify(photoData),
					album_id : '<?php echo $album['album_id'] ?>',
					preview_id : CboxId,
					current_num : $('div.menu_item').length,
					<?php if(!empty($_GET['event_id'])) echo 'event_id:\''.$_GET['event_id'].'\',' ?>
					<?php if(!empty($_GET['join_event'])) echo 'join_event:\''.$_GET['join_event'].'\',' ?>
				}),
			}).done(function(r) {
				r = $.parseJSON(r);

				switch (r.result) {
					case 1:
						block_box.close();
						upload_data = [];
						window.onbeforeunload = null;
						_jBox(r, 'success_notext');
						break;
					case 2:
						_jBox(r, 'login');
						break;
					case 3:
						_jBox(r, 'albumProcess');
						break;
					default:
                        r.redirect = '<?php echo self::url('diy', 'index', ['album_id'=>$album['album_id']]) ?>';
						_jBox(r, 'error');
						break;
				}
			});	
		}	
	})

	if($('table.files').find('tr').length > 0 ){
		obj.dequeue("before_upload");
	}
}

function browseKit_diy(key) {
	$('#mask02').data('indexId', key);
	browseKit_album('<?php echo self::url('album', 'show_photo') ?>', {album_id:'<?php echo $album['album_id'] ?>'});
}

function clean_setting(type) {
	for (key in type) {
		switch(type[key]) {
			case 'add_media':
				$('div#media_type_tab').find(':text').val('');
				$('.media_info_description').val('');
				$('#add_media_url').val('');
				$('#add_media_area').empty();
				$('#media_demo_file').attr('src', '');
				$('div[name="media_filename"]').html('');
				$('.media1_InfoUrlName,.media1_InfoUrl,.media2_InfoUrlName,.media2_InfoUrl').val('');
			break;

			case 'video':
				$('div[name="video_filename"]').html('').data('output_name', '');
				$("#video_demo_file source,#video_demo_file").attr('src','');
				$(':input#video_url').val('');
			break;
			
			case 'exchange':
			    $_obj0.html('<?php echo _('數量') ?>: <input step="1" type="number" max="65535" min="1" class="info_exchange_amount" placeholder="1 ~ 65535">');
				$_obj1.html('<textarea cols="30" rows="3"></textarea>');
				$_obj3.html('名稱: <input type="text" name="exchange_name" maxlength="32" class="laybar_text">');
				$_obj4.html('<img id="exchange_image_upload" class="common" src="<?php echo static_file('images/laybar_up.png')?>" data-act="exchange_image_upload">');

                $('#type_p3 div[data-tag="photousefor-exchange_starttime"]').html('<p>開始時間: <input type="text" name="exchange_starttime" class="datepicker" style="width:60%;"></p>');
                $('#type_p3 div[data-tag="photousefor-exchange_endtime"]').html('<p>結束時間: <input type="text" name="exchange_endtime" class="datepicker" style="width:60%;"></p>');
                $('img#exchange_image_show').attr({'src': '<?php echo static_file('images/transparent.png') ?>', 'name':''});
				$('#type_p3').data('photousefor_id', '');
			break;

			case 'slot' :
				$('.laybar_list').remove();
				$_obj2.html('<textarea cols="30" rows="2"></textarea>');
                $('#type_p4 div[data-tag="photousefor-slot-starttime"]').html('<input type="text" name="slot_starttime" class="datepicker" style="width:25%;">');
                $('#type_p4 div[data-tag="photousefor-slot-endtime"]').html('<input type="text" name="slot_endtime" class="datepicker" style="width:25%;">');

                break;
		}
	}
}

//crop & combine on one-button
function croppic() {
	$('#ctr-btn').attr('alt', 'true');
	//frame num
	var frame_num = $('.temp').length;			
	//upload num
	var upload_num = $('.cropControls i.cropControlCrop').length;
	//corped
	var croppic_num = $('.croppedImg').length;

	if (upload_num > 0) {
		$('.cropControls i.cropControlCrop').each(function() {
			$(this).trigger('click');
		});
	} else if (frame_num == croppic_num) {
		image_combine();
	} else {
		_jBox({message: '<?php echo _('The image has not been cropped yet or the pictures are not enough.')?>'}, 'info');
		$('#ctr-btn').attr('alt', 'false');
	}
}

//刪除 
function del(obj) {
	var setPreview = getPreviewCheck();
	var	deleteConfirm = new jBox('Confirm', {
		cancelButton: '<?php echo _('No')?>',
		confirmButton: '<?php echo _('Yes')?>',
		cancel: function() {
			deleteConfirm.destroy();
		},
		confirm: function() { 
			$.post('<?php echo self::url('diy', 'delete')?>', {
				album_id: '<?php echo $album['album_id']?>',
				photo_id: $(obj).next('img').data('photo_id'),
				setPreview : JSON.stringify(setPreview),
			}, function(r) {
				r = $.parseJSON(r);
				switch (r.result) {
					case 1:
						refreshPhoto(r.data);
						<?php 
							if($diy['diy']['upload_type']) {
								echo (!empty($frame)) ? 'set_frame('.$frame[0]['frame_id'].');' : null;
							}
						?>
						break;
					case 2:
						_jBox(r, 'login');
						break;
					case 3:
						_jBox(r, 'albumProcess');
						break;
					default:
						_jBox(r, 'error');
						break;
				}
			});
		},
		onCloseComplete: function() {
			deleteConfirm.destroy();
		}
	}).setContent(
		'<div class="message content"><?php echo _('Confirm the deletion?') ?></div>'
	).open();
};

function delayExecute(check, proc, chkInterval) {
    var x = chkInterval || 1000;
    var checkFunc = window.setInterval(function () {
        if (check()) {
            proc();
        }
        window.clearInterval(checkFunc);
    }, x);
}

function getPreviewCheck () {
	var PreviewCheck = [];
	$('.previewCbox').each(function(k, v){
		if($(v).prop('checked')) {
			PreviewCheck.push( $(v).parents('li').siblings('li.edit_img').children('img').data('tag') );
		}
	})
	return PreviewCheck;
}

//tooltip
function make_tooltip(target, text) {$(target).attr('title', text).jBox('Tooltip', {offset: {x: -30,y: 5}});}

//儲存相本
function save_album() {
    var item = $('.menu_item') , previewPageValidate = true;

    if( $('input[name="previewPageType"]:checked').val() == 'all' ) {
        previewPageNum = (item.length-1);
    } else {
        previewPageNum = Number.parseInt($('input[name="previewPageNum"]').val());

        if (previewPageNum > item.length) {
            _jBox({message: '<?php echo _('預覽頁數數量超過相片數量.')?>'}, 'error');
            $('input[name="previewPageNum"]').val(item.length-1);
            previewPageValidate = false;
        }  else if (previewPageNum < 1 || previewPageNum == '') {
            _jBox({message: '<?php echo _('至少需要輸入一頁提供預覽.')?>'}, 'error');
            $('input[name="previewPageNum"]').val(1);
            previewPageValidate = false;
        }
    }

    if(!previewPageValidate) return;
    if (item.length == 1) {
        _jBox({message: '<?php echo _('你的作品還沒有內容')?>'}, 'error');
    } else {
		function save_album_request () {
			var preview_id = [];

            for (var n = 0; n <= (previewPageNum-1); ++n) {
                preview_id.push($('.edit_img').eq(n).children('img').data('photo_id'));
            }

			Pace.track(function() {
				$.ajax({
					url: '<?php echo self::url('diy', 'save_album')?>',
					type: 'POST',
					data: {
						album_id: '<?php echo $album['album_id']?>',
						preview_id : preview_id,
                        preview_page_num : previewPageNum,
                        preview_type : $('input[name="previewPageType"]:checked').val(),

						<?php if(!empty($_GET['join_event'])) echo 'join_event:\''.$_GET['join_event'].'\',' ?>
						<?php if(!empty($_GET['event_id'])) echo 'event_id:\''.$_GET['event_id'].'\',' ?>
					},
					beforeSend: function(xhr) {
						Block_modal = _jBox(null, 'block');
					}
				}).done(function(r) {
					Block_modal.close();
					window.onbeforeunload = null;
					r = $.parseJSON(r);
					switch (r.result) {
						case 1:
							_jBox(r, 'success_notext');
							break;
						case 2:
							_jBox(r, 'login');
							break;
						case 3:
							_jBox(r, 'albumProcess');
							break;
						default:
							_jBox(r, 'error');
							break;
					}
				});
			});
		}

		/*slot pay*/
		$.post('<?php echo self::url('diy', 'slot_unpaid')?>', {
			album_id : '<?php echo $album['album_id'] ?>',
			sign : '<?php echo encrypt($param = array('album_id'=>$album['album_id'])); ?>',
		},function(r){
			r = $.parseJSON(r);
			switch(r.result) {
				case 1:
					if(r.data > 0) {
						var amount = r.data * <?php echo Core::settings('SLOT_PRICE'); ?>,
							myConfirm = new jBox('Confirm', {
							cancelButton: '<?php echo _('No')?>',
							confirmButton: '<?php echo _('Yes')?>',
							confirm: function() {
								$.post('<?php echo self::url('diy', 'slot_buy')?>' , {
									album_id : '<?php echo $album['album_id'] ?>',
									sign : '<?php echo encrypt($param = array('album_id'=>$album['album_id'])); ?>',
								},function(r){
									r = $.parseJSON(r);
									if(r.result == 1){
										save_album_request();
									}else{
										_jBox(r, 'error');
									}
								});
							},
							onCloseComplete: function() {
								myConfirm.destroy();
							}
						}).setContent(
							'<div class="content">' +
								'<p><?php echo _('剩餘P點：').number_format((new userModel())->getPoint($user['user_id'], 'web')) ?>p</p>' +
								'<p><?php echo _('Slot數量：'); ?>'+r.data+'張</p>' +
								'<p><?php echo _('共需花費：'); ?><span class="red">'+amount+'p</span></p>' +
							'</div>'
						).open();
					} else {
						save_album_request();
					}
				break;

				case 3:
					_jBox(r, 'albumProcess');
					break;
			}
		});
	}
};

//replace farem
function set_frame(id) {
	$('#temp_2').children().remove();
	if (typeof cropContainerEyecandy != "undefined") cropContainerEyecandy.destroy();
	$.post('<?php echo self::url('diy', 'set_frame')?>', {
		frame_id : id,
		success_item : $('.menu_item').length,
		album_id : '<?php echo $album['album_id']?>',
	}, function(r) {
		r = $.parseJSON(r);
		switch (r.result) {
			case 1:
				$('.frame_title').text(r.data['title']);
				
				//set frame into div#temp_2
				$('#temp_2').append(r.data['layout']);

				//1.建立Croppic 2.監聽Error message response 3.image格式篩選
				$('.temp').each(function(k, v){
					var cropContainerEyecandy = new Croppic('cropContainer' + k, croppicContainerEyecandyOptions);					
					var monitor = $('#cropContainer'+k);
					monitor.find('form>input[type=file]').attr('accept','image/jpeg, image/jpg, image/png');
				});
		
				//replade Editing img number
				$('.editpage').find('span').eq(0).text($('.menu_item').length);
				
				//tooltip
				make_tooltip('.cropControls .cropControlUpload', '<?php echo _('Upload Image') ?>');
				
				//close mask & back to edit area
				if ($('#mask').hasClass('maskopen')) {
					$('.menu').removeClass('slide-menu-up');
					$('#mask').addClass('maskclose');
					$('#mask').removeClass('maskopen');
					$('.menu').addClass('slide-menu-bottom', 1000, 'easeOutQuint'); 
				}

				$('#ctr-btn').attr('alt', 'false').removeClass('con_icon05 active').addClass('con_icon03').html('<?php echo _('Crop photo')?>');;
				$('li#frame' + id).addClass('active').siblings('li').removeClass('active');
				break;
			case 2:
				_jBox(r, 'login');
				break;
			case 3:
				_jBox(r, 'albumProcess');
				break;
			default:
				_jBox(r, 'error');
				if (r.data == 'over') $('.editpage').find('span').eq(0).text($('.menu_item').length);
				break;
		}
	});	
}

//all crop success then to do combine
function image_combine() {
	
	var setPreview = getPreviewCheck();
	//已上傳
	var croppic_count = $('.croppedImg').length;
	//需上傳
	var empty_count = $('.crop_upload').length;	
	
	if (croppic_count < empty_count) {
		//上傳不足縷空數
		_jBox({message: '<?php echo _('Your pictures are too few to be combined.')?>'}, 'info');
	} else if (croppic_count = empty_count) {
		var success_item = $('.menu_item').length;	
		var foreground = [];
		
		//逐一取得縷空格內圖片及位置
		$('.croppedImg').each(function() {
			//[url, top, left]
			var str = {
				url: $(this).attr('src'),
				top: $(this).parents('.temp').css('top'),
				left: $(this).parents('.temp').css('left'),
			};
			foreground.push(str);
		});
		
		Pace.track(function() {
			$.ajax({
				url: '<?php echo self::url('diy', 'image_combine')?>',
				type: 'POST',
				data: ({
					album_id: '<?php echo $album['album_id']?>',
					background: $('.tem_style').find('img').attr('alt'),
					foreground: JSON.stringify(foreground),
					success_item: success_item,
					setPreview : JSON.stringify(setPreview),
				}),
				beforeSend: function(xhr) {
					box0 = _jBox(null, 'processing');
				}
			}).done(function(r) {
				r = $.parseJSON(r);
				box0.close();
				switch (r.result) {
					case 1:
					case 4:
						refreshPhoto(r.data);
						set_frame(<?php echo (!empty($frame))? $frame[0]['frame_id'] : null ?>);

						// 進階編輯
						if (r.result == 1 && $('#aviary').attr('tag') == 'true') {
							var editConfirm = new jBox('Confirm', {
								cancelButton: '<?php echo _('No')?>',
								confirmButton: '<?php echo _('Yes')?>',
								cancel: function() {
									if ($('input[name=auto_aviary]').prop("checked")){$('#aviary').attr('tag', 'false');}
									$('.con_icon02').trigger('click');
									editConfirm.destroy();
								},
								confirm: function() {
									if ($('input[name=auto_aviary]').prop("checked")){$('#aviary').attr('tag', 'false');}
									editConfirm.destroy();
								},
								onCloseComplete: function() {
									$('.con_icon02').trigger('click');
									editConfirm.destroy();
								}
							}).setContent(
								'<div class="message content"><?php echo _('Advanced version?')?></div><div style="font-size:12px"><input type="checkbox" id="auto_aviary" name="auto_aviary"><label for="auto_aviary"><?php echo _('No prompt during session')?></label></div>'
							).open();
						}
						$('#ctr-btn').removeClass('con_icon05 active').addClass('con_icon03').html('<?php echo _('Crop photo')?>');
						break;
					case 2:
						_jBox(r, 'login');
						break;
					case 3:
						_jBox(r, 'albumProcess');
						break;
					default:
						_jBox(r, 'error');
						break;
				}
			});
		});
	} else if (empty_count == '') {
		_jBox({message: '<?php echo _('The photo quantity is beyond the limit.')?>'}, 'error');					
	}
}

function refreshPhoto(obj) {
	var html = '', CboxDefault= '';
	for (var k0 in obj.photo) {
		html +=
			'<div class="menu_item">' +
				'<ul id="links" style="min-height:215px;">' +
					'<li><span class="file-num">p' + (parseInt(k0, 10) + 1) + '</span><span class="type"><img onerror="this.src=\'<?php echo static_file('images/icon_empty.png') ?>\'" src="'+obj.photo[k0]['icon']+'"></span><span class="music">'+obj.photo[k0]['music_image_thumbnail']+'</span><span class="description">'+obj.photo[k0]['description_image_thumbnail']+'</span></li>' +
					'<li title="<?php echo _('建立者').':' ?>'+obj.photo[k0]['user_name']+'"><img class="thumbnail" src="' + obj.photo[k0]['image_url_thumbnail'] + '" onclick="browseKit_diy(' + k0 + ')"></li>' +
					'<li class="edit_img">' +
                        '<a href="javascript:void(0)" title="新增資訊" onclick="'+obj.photo[k0]['photo_setting_onclick']+'(this)" class="e2 more_setting"></a>' +
						'<a class="e3" href="javascript:void(0)" title="刪除" onclick="'+obj.photo[k0]['delete_onclick']+'(this)" title="delete"></a>' +
						'<img id="edit_' + (parseInt(k0, 10) + 1) + '" class="depot"  data-width="668" data-height="1002" data-usefor="'+obj.photo[k0]['usefor']+'" data-tag="' + obj.photo[k0]['image'] + '" data-photo_id="' + obj.photo[k0]['photo_id'] + '" style="display:none;" src="' + obj.photo[k0]['image_url'] + '">' +
					'</li>' +
				'</ul>' +
			'</div>';
	}

	$('#album_list').html(html);
	var editpage = '<div class="menu_item"><a onclick="$(\'#mask02\').trigger(\'click\');" href="javascript:void(0)"><div class="menu_add"><p class="editpage">'+($('.menu_item').length + 1)+'</span> / <span>'+obj.album_limit+'</span></p></div></a><div class="allSelectbtn"></div></div>';
	$('#album_list').append(editpage);

	$('.editpage').children('span.edit_num1').text($('.menu_item').length).children('span.edit_num2').text(obj.album_limit);
	
	for (var i = 0; i < checkedBoxList.length; i++) {
		$('input[data-photo_id="'+checkedBoxList[i]+'"]').attr('checked', 'checked');
	}

	browseKitRefresh();
}

function photo_setting(obj) {
	$('span[name="photo_setting_num"]').html($(obj).parents('ul').find('span.file-num').html());
	$.post('<?php echo self::url('diy', 'photo_setting')?>', {
		album_id: <?php echo $album['album_id']?>,
		photo_id: $(obj).siblings('img').data('photo_id'),
		sign: '<?php echo encrypt(['album_id'=>$album['album_id']])?>',
	}, function(r) {
		r = $.parseJSON(r);
		switch (r.result) {
			case 1:
				$('#more_enter a').data({'usefor': r.data.usefor, 'photo_id': r.data.photo_id});
				$('.etabs02>li[name='+r.data.usefor+']').children('a').trigger('click');$('.etabs02>li').show();
				$('.out_content .info_loaction').val(r.data.location); $('.out_content .info_description').val(r.data.description);
				$('.out_content .info_url1').val(r.data.url1); $('.out_content .info_url1_name').val(r.data.url1_name); 
				$('.out_content .info_url2').val(r.data.url2); $('.out_content .info_url2_name').val(r.data.url2_name); 
				$('[data-act="add_slot_item"]').show();$("#video_area1").empty();
				$('.etabs02>li[name="video"]').hide();
				var text_readonly='', upload_type = 'file', delete_style = '', video_platform;
				
				switch (r.data.usefor) {
					case 'video' : 
						$('.etabs02>li[name="video"]').show().siblings('li').hide(); 
						if (r.data.video_refer == 'embed') {
							
							video_platform = fetch_video_platform(r.data.video_target);
							if (typeof video_platform != 'undefined') {
								switch (video_platform) {
									case 'youtube':
									case 'vimeo':
										if($('#video_demo_embed').length > 0 || $('#fbVideo').length > 0){ $('#video_area1').empty();}
										$("#video_area1").append('<video style="margin-top:30px;" width="320" height="200" id="video_demo_embed"><source type="video/'+video_platform+'" src="'+r.data.video_target+'" /></video>');
										video_embed = new MediaElementPlayer('#video_demo_embed', {enablePluginDebug: false, flashName: 'flashmediaelement-cdn.swf'});
									break;

									case 'facebook':
										var video_url = r.data.video_target,
											element = `<div  
														id="fbVideo"
														class="fb-video" 
														data-href="${video_url}" 
														data-width="500" 
														data-allowfullscreen="true"></div>`;
										$('#video_area1').empty().append(element);
										window.FB.XFBML.parse();
									break;
								}

								$(':input[name="group1"].video_url').click();
								$(':input#video_url').val(r.data.video_target);
							}

						} else {
							$(':input[name="group1"].video_upload').click();
							$("#video_demo_file source.mp4, #video_demo_file").attr('src', '<?php echo URL_UPLOAD; ?>' + r.data.video_target);
							$('div[name="video_filename"]').data('output_name', r.data.video_target);
							$('#video_demo_file').attr('poster', r.data.imageUrl).data('poster', r.data.image);
						}
					break;
					
					case 'exchange' :
						$('.etabs02 li[name="exchange"]').siblings('li').hide();
						$('#type_p3').data('photousefor_id', r.data.photousefor.photousefor_id);
						$('img#exchange_image_show').attr({'src' : '<?php echo URL_UPLOAD ?>' +r.data.photousefor.image, 'name': r.data.photousefor.image});
						
						if (r.data.photo.exchange) {
						    photoExchange = true;
                            $_obj0.html('數量 :' + r.data.photousefor.amount);
                            $_obj3.html('名稱 :' + r.data.photousefor.name);
							$_obj1.html(r.data.photousefor.description);
							$_obj4.html('');
                            $('#type_p3 div[data-tag="photousefor-exchange_starttime"]').html('開始時間 : '+r.data.photousefor.starttime);
                            $('#type_p3 div[data-tag="photousefor-exchange_endtime"]').html('結束時間 : '+r.data.photousefor.endtime);
						} else {
							photoExchange = false;
							$_obj3.find('input').val(r.data.photousefor.name);
							$_obj0.find('input').val(r.data.photousefor.amount);
							$("input[name='exchange_starttime']").val(r.data.photousefor.starttime);
							$("input[name='exchange_endtime']").val(r.data.photousefor.endtime);
							$_obj1.find('textarea').val(r.data.photousefor.description);
						}
					break;

					case 'image':
						break;
					
					case 'slot' :
						$('.etabs02 li[name="slot"]').siblings('li').hide();
						
						var num0 = 0;
						for (k0 in r.data.photousefor) {
							$('#laybar_box').append(
								'<div class="laybar_list">' + 
									'<div class="laybar_left">' +
										'<ul>' +
											'<li><h4>' + (num0 + 1) + '</h4><a href="javascript:void(0)" class="laybar_delete common" data-act="laybar_delete"><img src="<?php echo static_file('images/editor/delete.png')?>" height="14" width="14"></a></li>' +
											'<li data-tag="slot-name-' + num0 + '">名稱: <input type="text" name="slot_name_' + num0 + '" maxlength="32" class="laybar_text"></li>' +
											'<li data-tag="slot-amount-' + num0 + '">數量: <span><input type="number" min="1" max="65535" name="slot_amount_' + num0 + '" placeholder="1 ~ 65535" class="laybar_text"></span></li>' +
                                            '<li data-tag="slot-uselessAward-' + num0 + '"><p>空獎項: <input type="checkbox" name="slot-uselessAward-' + num0 + '" style="width:10%;"></p></li>'+
											'<li data-tag="slot-possibility">機率: <span>0</span>%</li>' +
										'</ul>' +
									'</div>' +
									'<div id="slot_' + num0 + '" class="laybar_right">' +
										'<div class="right_upload">'+
											'<img id="slot_img_' + num0 + '" src="<?php echo static_file('images/laybar_up02.png')?>" height="49" width="32">'+
											'<input class="fileupload common" type="file" name="files[]" data-photo_type="slot" data-num="' + num0 + '" data-act="fileupload" accept="image/png,image/jpeg,image/jpg">'+
										'</div>'+
									'</div>'+
								'</div>');
							++num0;
						}
						
						if (r.data.photo.exchange) {
						    photoExchange = true;
                            $("input[name='slot_starttime']").replaceWith(r.data.photousefor[0].starttime);
                            $("input[name='slot_endtime']").replaceWith(r.data.photousefor[0].endtime);
							$('#type_p4 a[data-act="add_slot_item"]').hide();
							$('.laybar_delete, .right_upload').remove();

                            for (k0 in r.data.photousefor) {
                                $('.laybar_list').eq(k0).data('photousefor_id', r.data.photousefor[k0].photousefor_id);
                                $('li[data-tag="slot-name-' + k0 + '"] input').replaceWith(r.data.photousefor[k0].name);
                                $('li[data-tag="slot-amount-' + k0 + '"] span').text(r.data.photousefor[k0].amount);
                                var uselessAward = (r.data.photousefor[k0].useless_award) ? '&radic;' : 'x';
                                $('input[name="slot-uselessAward-' + k0 + '"]').replaceWith(uselessAward);
                                $('#slot_' + k0).prepend('<div class="right_img"><img src="<?php echo URL_UPLOAD?>' + r.data.photousefor[k0].image + '" name="' + r.data.photousefor[k0].image + '"></div>');
                            }

							$_obj2.html(r.data.photousefor[0].description);
						} else {
							photoExchange = false;
                            $("input[name='slot_starttime']").val(r.data.photousefor[0].starttime);
                            $("input[name='slot_endtime']").val(r.data.photousefor[0].endtime);
                            for (k0 in r.data.photousefor) {
                                $('.laybar_list').eq(k0).data('photousefor_id', r.data.photousefor[k0].photousefor_id);
                                $('li[data-tag="slot-name-' + k0 + '"] input').val(r.data.photousefor[k0].name);
                                $('li[data-tag="slot-amount-' + k0 + '"] input').val(r.data.photousefor[k0].amount);
                                if (r.data.photousefor[k0].useless_award) $('input[name="slot-uselessAward-' + k0 + '"]').prop('checked', true);
                                $('#slot_' + k0).prepend('<div class="right_img"><img src="<?php echo URL_UPLOAD?>' + r.data.photousefor[k0].image + '" name="' + r.data.photousefor[k0].image + '"></div>');
                            }
							
							$_obj2.find('textarea').val(r.data.photousefor[0].description);
						}

						slotPossibilityReflesh();
					break;
				}
				break;
			case 2:
				_jBox(r, 'login');
				break;
			case 3:
				_jBox(r, 'albumProcess');
				break;
			default:
				_jBox(r, 'error');
				break;
		}
	});
	
	$('.photo_setting').fadeIn();
}

function load_album_setting() {
	$('#page_turn').empty();$('#musicmulti_box').empty();
	$.post('<?php echo self::url('diy', 'load_album_setting') ?>', {
		album_id : <?php echo $album['album_id']; ?>,
	},function(r) {
		r = $.parseJSON(r);
		switch (r.result) {
			case 0:
				_jBox(r, 'error');
				break;
			case 1:
				for (var i=0, len = r.data.turn.length; i<len ; i++){
					$('#page_turn').append(r.data.turn[i]);
					$('#musicmulti_box').append(r.data.audio[i]);
				}
				break;
		}
	});
}

function show_media_view(){
	$('input[name="add_media_group"]:first').trigger('click');
	$('#media_upload_box').fadeIn();
}

function slotPossibilityReflesh() {
	var $tmp0 = $('#type_p4 li[data-tag^="slot-amount"] span'),
		num0 = 0,
		sum0 = 0;
	$.each($tmp0, function(k0, v0){
		sum0 += parseInt(($(v0).find('input[type="number"]').length? $(v0).find('input[type="number"]').val() : $(v0).text()) || 0, 10);
	});
	$.each($tmp0, function(k0, v0){
		if (sum0 !== 0) {
			num0 = (parseInt(($(v0).find('input[type="number"]').length? $(v0).find('input[type="number"]').val() : $(v0).text()) || 0, 10) / sum0 * 100).toFixed(1);
			if (num0 >= 100.0) {
				num0 = 100;
			} else if (num0 <= 0.0) {
				num0 = 0;
			}
		}
		$(v0).parent().siblings('li[data-tag="slot-possibility"]').find('span').text(num0);
	});
}

function no_right(obj) { _jBox({message: '<?php echo _('您無法進行此操作')?>'}, 'error'); }

//驗證輸入數字
function numcheck(obj){	var re = /^[0-9]+$/;if (!re.test(obj.value)){$(obj).val('');}}

//上傳影片相片(新增)
$('#media_upload_enter').on('submit', function() {
	var	message = null, data = {
		usefor : 'video',
		location : $('.media_info_loaction').val(),
		url1 : $('.media1_InfoUrl').val(),
		url1_name : $('.media1_InfoUrlName').val(),
		url2 : $('.media2_InfoUrl').val(),
		url2_name : $('.media2_InfoUrlName').val(),
		description : $('.media_info_description').val(),
		refer : ($(':radio[name="add_media_group"]:checked').data('rel') == 'media_embed' ) ? 'embed' : 'file' ,
	}, video_platform, setPreview = getPreviewCheck();

	data['value'] = (data['refer'] == 'embed') ? $('#add_media_url').val() : $('div[name="media_filename"]').data('output_name');
	video_platform = fetch_video_platform(data['value']);
	data['poster'] = (data['refer'] == 'file') ? $('#media_demo_file').data('poster') : null;

	if(typeof video_platform == 'undefined') {
		message = '<?php echo _('您的影片連結未填寫或是不支援此影片連結'); ?>';
		_jBox({'message': message}, 'error');
	}

	if(message == null) {
		data = JSON.stringify(data);
		checkedBoxList=[];
		$('.previewCbox').each(function(k, v){
			if($(v).prop('checked')) checkedBoxList.push($(v).data('photo_id'));
		});
		var process_box = _jBox({'message':''}, 'processing');
		$.post('<?php echo self::url('diy', 'add_media_photo') ?>', {
			album_id : <?php echo $album['album_id']; ?>,
			upload_type : '<?php echo $diy["diy"]["upload_type"]; ?>',
			data : data,
			video_platform : video_platform,
			setPreview : JSON.stringify(setPreview),
		},function(r) {
			r = $.parseJSON(r);
			process_box.close();
			clean_setting({'add_media':'add_media'});
			switch (r.result) {
				case 0:
					_jBox(r, 'error');
					break;
				case 1:
					_jBox(r, 'success_notext');
					refreshPhoto(r.data);
					photoChangeSettings = false;
					(data['refer'] == 'embed') ? $('#add_media_url').val('') : $('div[name="media_filename"]').data('output_name', '');
					$('div#media_close, .preivewlists').trigger('click');
                    $('#media_demo_file').attr('poster', '').data('poster', '');
                    $('#media_demo_file').load();
                    $('input[name="UploadCoverBtn"]').hide();
					break;
			}
		});
	}
});

//儲存相片模式
$('#photo_form_enter').on('submit', function() {
	var verify = true, message, clean_type = ['video', 'exchange', 'slot'],
		usefor = $('#more_enter a').data('usefor_save'),
		type_tab = $('li[name="'+usefor+'"] a').attr('href'),
		data = {
			usefor : usefor,
			location : $('.info_loaction').val(),
			url1 : $('.info_url1').val(),
			url1_name : $('.info_url1_name').val(),
			url2 : $('.info_url2').val(),
			url2_name : $('.info_url2_name').val(),
			description : $('.info_description').val(),
		},video_platform;

	//不同模式填入不同資料
	switch (usefor) {
		case 'video':
			var video_type = $(':radio[name="group1"]:checked').data('rel');
			data['value'] = (video_type == 'video_url') ? $(type_tab).find('input#video_url').val() : $(type_tab).find('div[name="video_filename"]').data('output_name');
			data['refer'] = (video_type == 'video_url') ? 'embed' : 'file';
            data['poster'] = (data['refer'] == 'file') ? $('#video_demo_file').data('poster') : null;

            video_platform = fetch_video_platform(data['value']);
			if (typeof video_platform == 'undefined' ||  video_platform == 'undefined') {
				verify = false ;
				message = '<?php echo _('您的影片連結未填寫或是不支援此影片連結'); ?>';
			}
		break;

		case 'exchange':
			if (!photoExchange) {
				var amount = parseInt($('input.info_exchange_amount').val(), 10) || 0,
				    name = $('input[name="exchange_name"]').val(),
				    img = $('#exchange_image_show').attr('name'),
                    starttime = $("[name='exchange_starttime']").val() || null,
                    endtime = $("[name='exchange_endtime']").val() || null;

				if(starttime > endtime ) {
                    verify = false ;
                    message = '<?php echo _('有效日期設定錯誤, 請重新設定'); ?>';
                }

				if (amount === 0) {
					verify = false;
					message = '<?php echo _('數量需大於 0')?>';
				}

				if(img == null|| img == '' || img == 'undefined') {
					verify = false;
					message = '<?php echo _('需上傳兌換券圖片') ?>';
				}

				data.photousefor = {
					photousefor_id: $('#type_p3').data('photousefor_id'),
					description: $_obj1.find('textarea').val(),
					amount: amount,
					image : img,
					name : name,
                    starttime : starttime,
                    endtime : endtime,
				};
			}
		break;

		case 'slot':
			if (!photoExchange) {
				var slot_item = $('div.laybar_list'),
                    starttime = $("[name='slot_starttime']").val() || null,
                    endtime = $("[name='slot_endtime']").val() || null;

				if (slot_item.length == 0) {
					verify = false ;
					message = '<?php echo _('至少須設定一個獎項'); ?>';
				} else if(starttime > endtime ) {
                    verify = false ;
                    message = '<?php echo _('有效日期設定錯誤, 請重新設定'); ?>';
                }

				data.photousefor = [];

				$(slot_item).each(function(k, v) {
					var flag = $(v).find('h4').text(),
						img = $(this).find('div.right_img').children('img').attr('name'),
						name =  $(this).find(':input[name^="slot_name_"]').val(),
						amount = $(this).find(':input[name^="slot_amount_"]').val(),
                        useless_award = ($(this).find(':input[name^="slot-uselessAward"]').prop('checked')) ? 1 : 0,
                        repeat = data.photousefor.some(function(value, index, array){return value['name'] == name ? true : false;});//檢查名稱重複

					if (repeat) {
						message = '<?php echo _('重複的獎項名稱')?>';
						verify = false;
						return false;
					} else if (typeof name == 'undefined' || name.length === 0 ) {
						message = flag + ' - <?php echo _('名稱需填寫')?>';
						verify = false;
						return false;
					} else if (typeof amount === 'undefined' || amount == 0) {
						message = flag + ' - <?php echo _('數量需填寫')?>';
						verify = false;
						return false;
					} else if (typeof img === 'undefined') {
						message = flag + ' - <?php echo _('圖示需上傳')?>';
						verify = false;
						return false;
					} else {
						data.photousefor.push({
							photousefor_id: $(v).data('photousefor_id'),
							name: name,
							image: img,
							description: $_obj2.find('textarea').val(),
							amount: amount,
                            starttime : starttime,
                            endtime : endtime,
                            useless_award : useless_award,
						});
					}
				});
			}
		break;
	}

	if (verify) {
		for(key in clean_type) {
			if(clean_type[key] == usefor) {
				clean_type.splice(key, 1);
			}
		}
		
		data = JSON.stringify(data);
		var process_box = _jBox({'message':'test'}, 'processing'), photo_id = $('#more_enter a').data('photo_id'), descriptionIcon = '';
		$.post('<?php echo self::url('diy', 'save_photo_setting') ?>', {
			album_id : <?php echo $album['album_id']; ?>,
			photo_id : photo_id,
			data : data,
			video_platform : video_platform,
		}, function(r) {
			r = $.parseJSON(r);
			process_box.close();
			
			switch (r.result) {
				case 0:
					_jBox(r, 'error');
					break;
					
				case 1:
					photoChangeSettings = false;
					photoExchange = false;
					
					_jBox(r, 'success_notext');
					clean_setting(clean_type);
					$('div#set_close').trigger('click');
					img = $('img[data-photo_id="'+r.data.photo_id+'"]').parents('ul#links').find('li>span.type>img').attr('src', '<?php echo static_file('images/icon_'); ?>'+usefor+'.png');
					$('img[data-photo_id="'+r.data.photo_id+'"]').attr('data-usefor', usefor);
					if($('.info_description').val() != '') descriptionIcon = '<img src="<?php echo static_file('js/editor/images/editor/icon_text.png');?>" height="11" width="11">';
					$('img[data-photo_id='+r.data.photo_id+']').parents().siblings('li:first').find('span.description').html('').append(descriptionIcon);
					if (usefor =='video') { $('img[data-photo_id="'+r.data.photo_id+'"]').parents('ul').find('li').eq(1).children('img').attr('src', r.data.image); }
					
					browseKitRefresh();
					break;
					
				case 2:
					_jBox(r, 'login');
					break;
					
				case 3:
					_jBox(r, 'albumProcess');
					break;
			}
		});
	} else {
		_jBox({message: message}, 'error');
	}
});

//儲存相本模式
$('#album_form_enter').on('submit', function() {
	var data = {'audio':'', 'turn':''}, audio = [], turn = [], audioIconId = [];
	
	//set audio
	var audio_mode = $('input[name="audio_mode"]:checked').val();
	audio = {'mode' : audio_mode,'data' : [],};
	
	if(audio_mode == 'singular') {
		var singular_mode = $('input[name="singular_mode"]:checked').val(), singular=[];
		singular = {'mode' : singular_mode,'data' : {'value' : '',	'repeat' : '',},};
		singular['data']['value'] = (singular_mode == 'system') ? $('select.music_album option:selected').data('audio_id') : $('div[name="audio_name_singular"]').data('output_name');
		singular['data']['repeat'] = ( $('input[name="'+singular_mode+'_repeat"]').prop('checked')) ? 'true' : 'false' ;
		audio['data'] = singular; 
	}
	
	if(audio_mode == 'plural') {
		$('div.audio_list').each(function(k, v){
			var photo_audio_mode = $('input[name="photo_audio_mode_'+(k+1)+'"]:checked').val();
			plural = {'photo_id' : $(v).data('photo_id'), 'mode' : photo_audio_mode,'data' : {'value' : '',	'repeat' : '',},};
			
			_audioIconId = (photo_audio_mode == 'none') ? {'photo_id':$(v).data('photo_id') , 'icon':''} : {'photo_id':$(v).data('photo_id') , 'icon':'<img src="<?php echo static_file('images/icon05.png'); ?>" height="11" width="11">'} ;
			audioIconId.push(_audioIconId);

			if(photo_audio_mode == 'system') {
				plural['data']['value'] = $('select[name="plural_'+(k+1)+'"] option:selected').data('audio_id')
				plural['data']['repeat'] = ( $('input[name="'+photo_audio_mode+'_repeat_'+(k+1)+'"]').prop('checked')) ? 'true' : 'false' ;
			}else{
				plural['data']['value'] = $('div[name="audio_name_'+(k+1)+'"]').data('output_name');
				plural['data']['repeat'] = ( $('input[name="file_repeat_'+(k+1)+'"]').prop('checked')) ? 'true' : 'false' ;
			}
			audio['data'].push( plural ); 
		});
	}
	data['audio']= audio;

	//set turn
	$('div.turn_list').each(function(k, v){
		var obj = $(this), tmp = [],
		duration = ( obj.find("input[name^='group']:checked").val() == 'manual' ) ? 0 : obj.find("input[name^='text']").val() ;
		tmp = {
			'photo_id' : obj.data('photo_id'),
			'duration' : duration,
		}
		turn.push(tmp);
	});
	
	data['turn']= turn;
	
	data = JSON.stringify(data);
	$.post('<?php echo self::url('diy', 'save_album_setting') ?>', {
		album_id : <?php echo $album['album_id']; ?>,
		data : data,
	},function(r) {
		r = $.parseJSON(r);
		switch (r.result) {
			case 0:
				_jBox(r, 'error');
				break;
			case 1:
				_jBox(r, 'success_notext');
				audioIconId.forEach(function(r) {
					$('img[data-photo_id='+r.photo_id+']').parents().siblings('li:first').find('span.music').html('').append(r.icon);
				});
				photoChangeSettings = false;
				$('#set_close').trigger('click');
				break;
		}
	});
});

//change 事件控制
$(document).on('change', 'input[name^="group"]', function(e) {
	($(this).val() == 'manual') ? $(this).parents('li').siblings('li.autocontent').hide() : $(this).parents('li').siblings('li.autocontent').show();	
}).on('change', 'input[name^="photo_audio_mode_"]' ,function() {
	switch( $(this).val() ){
		case 'none' : 
			$(this).parents('li').siblings('li.file_content, li.system_content').hide();
		break;
		
		case 'system' : 
			$(this).parents('li').siblings('li.file_content').hide().siblings('li.system_content').show();	
		
		break;
		
		case 'file' : 
			$(this).parents('li').siblings('li.system_content').hide().siblings('li.file_content').show();	
		break;
	}
}).on('change', 'input[name="audio_mode"]' ,function() {
	audio.pause();
}).on('change', '.music' ,function() {
	var file = $(this).val();
	//playing the song
	if(audio) {
		audio.pause();
		audio = null;
	}
	audio = new Audio(file);
	audio.addEventListener('canplaythrough', function() {
		$('.loading').hide();
	}, false);
	audio.addEventListener('ended', function() { 
		audio.pause();
		audio = null
	}, false);
	audio.play();
}).on('change', '.music_album' ,function() {
	var file = $(this).val();
	$('div#singular_audio_area').empty().append('<audio controls id="audio_demo_singular_system"><source src="'+file+'" type="audio/mpeg">Your browser does not support the audio element.</audio>');
}).on('change', '#add_media_url', function(e){
	var video_url = $(this).val();
	
	if(video_url.length > 0) {	
		var video_platform = fetch_video_platform(video_url),
			media_embed;
		
		if(typeof video_platform != 'undefined') {
			
			switch (video_platform) {
				case 'dailymotion' :
					var videoStr2Array = video_url.split('/'),
						videoID = videoStr2Array[(videoStr2Array.length-1)],
						element = `<div id="DMplayer"></div>`;
					$('#add_media_area').empty().append(element);
					DMplay(videoID);
					break;

				case 'youtube':
				case 'vimeo':
					if($('#add_media_demo_player').length > 0 || $('#fbVideo').length > 0){ $('#add_media_area').empty();}
					$("#add_media_area").append('<video style="margin-top:30px;" width="320" height="200" id="add_media_demo_player"><source type="video/'+video_platform+'" src="'+$(this).val()+'" /></video>');
					media_embed = new MediaElementPlayer('#add_media_demo_player', {enablePluginDebug: false, flashName: 'flashmediaelement-cdn.swf'});
					break;

				case 'facebook':
					var element = `<div  
									id="fbVideo"
									class="fb-video" 
									data-href="${video_url}" 
									data-width="500" 
									data-allowfullscreen="true"></div>`;
					$('#add_media_area').empty().append(element);
					window.FB.XFBML.parse();
					break;
			}

		} else {
			var r ={
				message : '<?php echo _('網址格式不正確, 請重新輸入。') ?>',
			};
			_jBox(r, 'error');
		}
	}
}).on('change', '#video_url', function(e){
	var video_url = $(this).val();
	console.log(video_url);
	if(video_url.length > 0) {
		var video_platform = fetch_video_platform(video_url), 
			video_embed;
		
		if(typeof video_platform != 'undefined') {
			switch (video_platform) {
				case 'dailymotion' :
					var videoStr2Array = video_url.split('/'),
						videoID = videoStr2Array[(videoStr2Array.length-1)],
						lement = `<div id="DMplayer"></div>`;
					$('#video_area1').empty().append(element);
					DMplay(videoID);
					break;

				case 'youtube':
				case 'vimeo':
					if($('#video_demo_embed').length > 0 || $('#fbVideo').length > 0){ $('#video_area1').empty();}
					$("#video_area1").append('<video style="margin-top:30px;" width="320" height="200" id="video_demo_embed"><source type="video/'+video_platform+'" src="'+$(this).val()+'" /></video>');
					video_embed = new MediaElementPlayer('#video_demo_embed', {enablePluginDebug: false, flashName: 'flashmediaelement-cdn.swf'});
					break;
				case 'facebook':
					var element = `<div  
									id="fbVideo"
									class="fb-video" 
									data-href="${video_url}" 
									data-width="500" 
									data-allowfullscreen="true"></div>`;
					$('#video_area1').empty().append(element);
					window.FB.XFBML.parse();
					break;
			}
		} else {
			var r ={
				message : '<?php echo _('網址格式不正確, 請重新輸入。') ?>',
			};
			_jBox(r, 'error');
		}
	}
}).on('change', '.info_url1, .info_url2', function(e){
	var value = $(this).val(),search_url_keys = 'http|https',
		strRegex = '^((https|http):\/\/)?'
	+ '(((([0-9]|1[0-9]{2}|[1-9][0-9]|2[0-4][0-9]|25[0-5])[.]{1}){3}([0-9]|1[0-9]{2}|[1-9][0-9]|2[0-4][0-9]|25[0-5]))' // IP URL
	+ '|'
	+ '([0-9a-zA-Z\u4E00-\u9FA5\uF900-\uFA2D-]+[.]{1})+[a-zA-Z-]+)' // DOMAIN URL
	+ '(:[0-9]{1,4})?',
		url_validate = new RegExp(strRegex), r = [];
	if(value.length > 0) {
		if(!url_validate.test(value)) {
			//驗證失敗
			r.message = '<?php echo _('無效的連結網址,請重新輸入') ?>';
			_jBox(r, 'info');
			$(this).focus().val('');
		}else{
			if(value.search(search_url_keys) != 0) {
				$(this).val('http://'+value);
			}
		}
	}
}).on('change', 'input[name="previewPageType"]', function(e) {
    if($(this).val() == 'all') {
        $('input[name="previewPageNum"]').val('');
    } else {
        $('input[name="previewPageNum"]').focus();
    }
}).on('change', 'select[id^="control_box_user_"]', function (e) {
	var id = $(this).data('user_id'), 
		identity = $(this).val();
		origin_identity = $(this).data('origin_identity');
	update_invited(id, identity, origin_identity);
});

//click 事件控制
$(document).on('click', '.common', function(e) {
	var obj = $(this), act = $(obj).data('act'),
		btnUpload = $('#before_upload');
	switch (act) {
		//開啟相本進階編輯
		case 'album_setting': $('.album_setting').fadeIn(); break;
		
		//關閉進階編輯
		case 'set_close':
			e.stopPropagation();

			var fn0 = function(){
				$('.album_setting, .media_upload, .photo_setting').fadeOut().promise().done(function(){
				     clean_setting(['video', 'exchange', 'slot']);
				     photoChangeSettings = false;
				     photoExchange = false;
				});
			}

			if (photoChangeSettings) {
				var box = new jBox('Confirm', {
					cancelButton: '<?php echo _('No')?>',
					confirmButton: '<?php echo _('Yes')?>',
					confirm: fn0,
					onCloseComplete: function(){
						box.destroy();
					}
				}).setContent(
					'<div class="content">' +
					'<p><?php echo _('您所做的變更沒有儲存，是否要離開？')?></p>' +
					'</div>'
				).open();
			} else {
				fn0();
			}
			break;
			
		break;
				
		//影片選單
		case 'triggervideo' : $('.film_content').hide(); $('.' + $(this).data('rel')).show(); break;
		//音樂單選框控制
		case 'triggermusic01' : $('.music_content').hide(); $('.' + $(this).data('rel')).show(); break;
		case 'triggersingle' : $('.music_content02').hide(); $('.' + $(this).data('rel')).show(); break;

		case 'exchange_image_upload' : $('.exchange_fileupload').trigger('click'); break;

		//新增slot item
		case 'add_slot_item':
			var $tmp0 = $('div.laybar_list'),
				num0 = $tmp0.length;
			if (num0 >= 20) {
				_jBox({'message': '<?php echo _('達到獎項上限')?>'}, 'error');
			} else {
				var num1 = 0;
				$.each($tmp0, function(k0, v0){
					num1 = Math.max(num1, $(v0).find('.fileupload').data('num'));
				});
				++num1;
					
				$('#laybar_box').append(
					'<div class="laybar_list">' + 
						'<div class="laybar_left">' +
							'<ul>' +
								'<li><h4>' + (num0 + 1) + '</h4><a href="javascript:void(0)" class="laybar_delete common" data-act="laybar_delete"><img src="<?php echo static_file('images/editor/delete.png')?>" height="14" width="14"></a></li>' +
								'<li data-tag="slot-name-' + num1 + '">名稱: <input type="text" name="slot_name_' + num1 + '" maxlength="32" class="laybar_text"></li>' +
								'<li data-tag="slot-amount-' + num1 + '">數量: <span><input type="number" min="1" max="65535" name="slot_amount_' + num1 + '" placeholder="1 ~ 65535" class="laybar_text"></span></li>' +
                                '<li data-tag="slot-uselessAward-' + num1 + '"><p>空獎項: <input type="checkbox" name="slot-uselessAward-' + num1 + '" style="width:10%;"></p></li>'+
                                '<li data-tag="slot-possibility">機率: <span>0</span>%</li>' +
							'</ul>' +
						'</div>' +
						'<div id="slot_' + num1 + '" class="laybar_right">' +
							'<div class="right_upload">'+
								'<img id="slot_img_' + num1 + '" src="<?php echo static_file('images/laybar_up.png')?>" height="49" width="32">'+
								'<input class="fileupload common" type="file" name="files[]" data-photo_type="slot" data-num="' + num1 + '" data-act="fileupload" accept="image/png,image/jpeg,image/jpg">'+
							'</div>'+
						'</div>'+
					'</div>');
			}
		break;
		
		//刪除slot_item
		case 'laybar_delete':
			var unit0 = obj.parents('.laybar_list'),
				param0 = {
					album_id: '<?php echo $album['album_id']?>',
					photo_id: $('#more_enter a').data('photo_id'),
					image: unit0.find('div.right_img img').attr('name'),
					timestamp: new Date().getTime(),
				};
			
			$.post('<?php echo self::url('diy', 'sign')?>', param0, function(r0){
				r0 = $.parseJSON(r0);

				param0.sign = r0.data;
				
				$.post('<?php echo self::url('diy', 'delete_slot_item')?>', param0, function(r1) {
					r1 = $.parseJSON(r1);
					switch (r1.result) {
						case 1:
							photoChangeSettings = true;
							
							unit0.remove();
							
							$('div.laybar_list').each(function(k0, v0){$(this).find('h4').text(k0 + 1);});
							
							slotPossibilityReflesh();
							break;
							
						case 2:
							_jBox(r1, 'login');
							break;
							
						case 3:
							_jBox(r1, 'albumProcess');
							break;
							
						default:
							_jBox(r1, 'error');
							break;
					}
				});
			});
		break;
		
		// 上傳 音樂 / 影片 / slot圖
		case 'fileupload' : 
			var photo_type = $(this).data('photo_type'), num = $(this).data('num'), mediavideo = $(this).data('mediavideo');
			$(this).fileupload({
				formData: {album_id: '<?php echo $album['album_id']?>', photo_type: photo_type},
				dataType: 'json',
				url: '<?php echo self::url('diy', 'file_upload')?>',
				add: function (e, data) {
					if(data.originalFiles[0]['size'] && data.originalFiles[0]['size'] > <?php echo $uploadFileMaxSizeData['file_upload_maxsize'] ?> ) {
						_jBox({'message':'<?php echo  $uploadFileMaxSizeData['overUploadMaxsizeMsg'] ?>'}, 'error');
					} else {
						data.submit();
					}
				},
				start : function(){
					box = new jBox('Modal', {
						offset: {y: -50},
						position: {y: 'center'},
						closeButton: 'title',
						closeOnClick: false,
						closeOnEsc: false,
						zIndex: 15000,
						width : 300,
						delayClose : 500,
					}).setContent('<?php echo _('Uploading') ?>...<div class="progress"><div class="progress-bar progress-bar-striped active" role="progressbar"aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">0% </div></div>').open();
				},
				done: function(e, data) {
					switch (data.result.result) {
						case 0:
							_jBox(data.result, 'error');
							break;
							
						case 1:
							photoChangeSettings = true;

							switch (photo_type) {
								case 'audio':
									var suffix = $(this).data('num');
									$('div[name="audio_name_'+suffix+'"]').html(data.result.data.input_name).data('output_name', data.result.data.output_name);
									$('#audio_demo_'+suffix).attr('src', '<?php echo URL_UPLOAD; ?>' + data.result.data.output_name);
								break;

								case 'video':
									$('div[name="'+mediavideo+'_filename"]').html(data.result.data.input_name).data('output_name', data.result.data.output_name);
									$('#'+mediavideo+'_demo_file source.mp4, #'+mediavideo+'_demo_file').attr('src', '<?php echo URL_UPLOAD; ?>' + data.result.data.output_name);
                                    $('input[name="UploadCoverBtn"]').show();
								break;

								case 'slot':
									var slot_img = $('div#slot_' + num);
									if (slot_img.find('div.right_img').length > 0) {
										slot_img.find('div.right_img img').attr({'src': data.result.data.output_url, 'name': data.result.data.output_name});
									} else {
										slot_img.prepend('<div class="right_img"><img src="'+data.result.data.output_url+'" name="'+data.result.data.output_name+'"></div>');
										$('img#slot_img_' + num).attr('src', '<?php echo static_file('images/laybar_up02.png')?>');
									}
								break;

								case 'exchange' :
									$('img#exchange_image_show').attr({'src' :data.result.data.output_url, 'name': data.result.data.output_name});
									$('img#exchange_image_upload').attr({'src': '<?php echo static_file('images/laybar_up02.png') ?>'});
								break;

                                case 'video_cover' :
                                    if(mediavideo == 'media') {
                                        $('#media_demo_file').attr('poster', data.result.data.fileurl).data('poster', data.result.data.basename);
                                        $('#media_demo_file').load();
                                    } else {
                                        $('#video_demo_file').attr('poster', data.result.data.fileurl).data('poster', data.result.data.basename);
                                        $('#video_demo_file').load();
                                    }
                                    break;

                                    default :
									_jBox({'message':'<?php echo _('Error phototype upload.') ?>'}, 'error');
								break;
							}

							break;
							
						case 2:
							_jBox(data.result, 'login');
							break;

						case 3:
							_jBox(data.result, 'albumProcess');
							break;
					}
					box.close();
				},
				progressall : function(e, data) {
					var progress = parseInt(data.loaded / data.total * 100, 10);
					$('.progress-bar').width(progress+'%').html(progress+'%');
				},
			});
		break;

		case 'cbox' :
			if($(this).data('cbox') == 'locked') {
				_jBox({message:'<?php echo _('首張相片必須設為預覽圖') ?>'}, 'error');
				return false;
			}
		break;

		case 'cancelfile' : 
			filesQueue = filesQueue-1; 
			if(filesQueue <= maxUploadFiles) { 
				btnUpload.find('span').html('<?php echo _('開始上傳檔案') ?>'); 
			} else {
				btnUpload.find('span').html('<?php echo _('待上傳數量 : ') ?>'+filesQueue); 
			} 
		break;
		
		case 'cancelallfile' : 
			filesQueue = 0; 
			$('#before_upload').find('span').html('<?php echo _('開始上傳檔案') ?>');
		break;
	}
}).on('click', 'div.cropControls>i.cropControlRemoveCroppedImage', function(e){
	var that = this;
	$.post('<?php echo self::url('diy', 'img_remove')?>', {
		album_id: '<?php echo $album['album_id']?>',
		imgUrl: $(this).data('imgUrl'),
	}, function(r) {
		r = $.parseJSON(r);
		switch (r.result) {
			case 1:
				$(that).prev().css('display', 'block');
				$('#ctr-btn').removeClass('con_icon05 active').addClass('con_icon03').html('<?php echo _('Crop photo')?>');
				break;
			case 2:
				_jBox(r, 'login');
				break;
			case 3:
				_jBox(r, 'albumProcess');
				break;
			default:
				_jBox(r, 'error');
				break;
		}
	});
	make_tooltip('.cropControls .cropControlUpload', '<?php echo _('Upload Image')?>');
}).on('click', 'input[name="previewPageNum"]', function() {
    $('input[name="previewPageType"]').eq(1).prop('checked', true);
});

//blur事件控制
$(document).on('blur', '.music', function(e) {
	audio.pause();
});

var trip = new Trip([
	{ sel : $("#temp_2"), content : "<?php echo _('Start Uploading'); ?>", position : "n"},
	{ sel : $(".con_icon03"), 
		content : "<?php echo _('Click to combine the photos'); ?>", 
		position : "w" ,
		onTripStart : function(){$('#ctr-btn').removeClass('con_icon05 active').addClass('con_icon03').html('<?php echo _('Crop photo'); ?>');},
		onTripEnd: function(){$('#ctr-btn').removeClass('con_icon03').addClass('con_icon05').html('<?php echo _('Save page'); ?>');},
	},
	{ sel : $(".con_icon03"),
		content : "<?php echo _('After editing all pages, they can be saved in the album.').'<br>'._('All uploading and editing are completed; the next step is to edit  information on the page.'); ?>", 
		position : "w" ,
		onTripStart : function(){$('#ctr-btn').removeClass('con_icon03').addClass('con_icon05').html('<?php echo _('Save page'); ?>');},
		onTripEnd: function(){	$('#ctr-btn').removeClass('con_icon05 active').addClass('con_icon03').html('<?php echo _('Crop photo'); ?>');},
	},
	{ sel : $("#menu_open"), content : "<?php echo _('You can: 1. select a style; 2. view the finished page; 3. advanced version; 4. delete the page here'); ?>", position : "n"},
	{ sel : $(".start"), content : "<?php echo _('After editing all pages, they can be saved in the album.').'<br>'._('All uploading and editing are completed; the next step is to edit  information on the page.'); ?>", position : "s"},  
], {
	animation : 'bounceIn' ,
	showNavigation : true,
	showCloseBox : true,
	delay : -1,
	prevLabel: '<?php echo _('Previous'); ?>',
	nextLabel: '<?php echo _('Next'); ?>',
	finishLabel: '<?php echo _('Close'); ?>',  
});

<?php echo (!$trip_tip) ? null : 'trip.start();'; ?>


//search: on + datalist
$('input[name="searchkey"]').on({
	keypress: function(e) {
		if (e.which == 13 || e.keyCode == 13) _search();
	},
}).typeahead({
	afterSelect: function(){_search();},
	autoSelect: false,
	showHintOnFocus: true,
	source: function(query, process) {
		$.post('<?php echo self::url('search') ?>', {
			searchkey: query
		}, function(r) {
			process($.parseJSON(r));
		});
	},
});


function _search() {
	var url = '<?php echo self::url('search', 'cooperate_search') ?>',
		searchkey = $('#searchkey').val().trim();
	if(searchkey) {
		$.post(url, {
			searchkey : searchkey,
			album_id : <?php echo $album['album_id'] ?>,
			user_id : <?php echo $album['user_id'] ?>
		}, function(r) {
			r = $.parseJSON(r);
			$('#creative_search_list').empty();
			for(var i of r ) {
				var status = (i.identity) ? '已邀請' : '邀請',
					btn_style = (i.identity) ? 'btn_invited' : 'btn_uninvited' ,
					click = (i.identity) ? '': 'onclick="add_invited_item('+i.user_id+' , \''+i.name+'\', \''+encodeURIComponent(i.cover)+'\');"' ,
					html = `<div class="result_item">
					<div class="result_face"><img src="${i.cover}" alt="${i.name}" onerror="this.src= '<?php echo static_file('images/face_sample.png') ?>' "></div>
					<div class="result_info">
						<ul>
							<li class="restult_name" title="${i.name}">${i.name}</li>
							<li class="${btn_style}" id="user_${i.user_id}" ${click} >${status}</li>
						</ul>
					</div>
				</div>`;

				$('#creative_search_list').append(html);
				$(".search_result").getNiceScroll().onResize();
			}
		});
	}
}

function add_invited_item (user_id, name, cover) {
	var url = '<?php echo self::url('diy', 'insertCooperation') ?>';
	$.post(url, {
		album_id : <?php echo $album['album_id'] ?>,
		user_id : user_id,
		identity : 'viewer',
	}, function(r) {
		r = $.parseJSON(r);
		switch (r.result) {
			case 1:
				var html = `<div class="invited_item" id="invited_item_${user_id}">
							<div class="delete_invited" onclick="delete_invited_item(${user_id},'${name}');" >X</div>
							<div class="invited_face"><img src="${decodeURIComponent(cover)}" alt="${name}" onerror="this.src= '<?php echo static_file('images/face_sample.png') ?>' "></div>
							<div class="invited_info">
								<ul>
									<li class="invited_name">${name}</li>
									<li>
										<div class="dropdown">
											<select id="control_box_user_${user_id}" data-user_id="${user_id}">
												<option value="viewer">瀏覽</option>
												<option value="editor">共用</option>
												<option value="approver">副管理</option>
											</select>
										</div>
									</li>
								</ul>
							</div>
						</div>`;

				$('li#user_'+user_id).switchClass('btn_uninvited', 'btn_invited').html('已邀請');
				$('#creative_cooperate_list').append(html);
			
				$('#creative_cooperate_list').width($('#creative_cooperate_list').width()+170);
				$(".invited_item_list").getNiceScroll().resize();
			
				break;
	
			default :
				_jBox(r, 'error');
				break;
		}
	});
}

function delete_invited_item(user_id, name) {
	var url = '<?php echo self::url('diy', 'deleteCooperation') ?>';
	$.post(url, {
		album_id : <?php echo $album['album_id'] ?>,
		user_id : user_id,
	}, function(r) {
		r = $.parseJSON(r);
		switch (r.result) {
			case 1:

				if( $('li#user_'+user_id).length ) {
					var img_src = $('#invited_item_'+user_id).find('img').attr('src');
					$('li#user_'+user_id).switchClass('btn_invited', 'btn_uninvited').html('邀請').attr('onclick', 'add_invited_item(\''+user_id+'\' , \''+name+'\', \''+encodeURIComponent(img_src)+'\');');
				}

				$('#invited_item_'+user_id).remove();
				$('#creative_cooperate_list').width($('#creative_cooperate_list').width()-170);
				break;
	
			default :
				_jBox(r, 'error');
				break;
		}
	});
}

function update_invited (user_id, identity, origin_identity) {
	var url = '<?php echo self::url('diy', 'updateCooperation') ?>';
	$.post(url, {
		album_id : <?php echo $album['album_id'] ?>,
		user_id : user_id,
		identity : identity,
	}, function(r) {
		r = $.parseJSON(r);
		switch (r.result) {
			case 1:
				break;
	
			default :
			$('#control_box_user_'+user_id).val(origin_identity);
			_jBox(r, 'error');
			break;
		}
	});
}

//邀請區塊寬度
$('.invited_item_list .product_scroll2').width($(".product_scroll2").find('.invited_item').length*170);
$(window).resize(function(){    
    $(".search_result").getNiceScroll().resize();
	$(".invited_item_list").getNiceScroll().resize();
});

$('.invited_item_list').on("mousewheel", function() {
	return false;
});


</script>