<?php echo $index?>
<script>
$(function() {
    $('#grid').kendoGrid({
    	columns: [
			{
				title: 'adarea',
				columns: [
					{field: 'adarea_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
					{title: '@info', field: 'adareaX', attributes: {'class': 'string'}, encoded: false, filterable: false, sortable: false}
				]
			},
			{
				title: 'ad',
				columns: [
					{field: 'ad_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
					{title: '@info', field: 'adX', attributes: {'class': 'string'}, encoded: false, filterable: false, sortable: false}
				]
			},
			{field: 'lang_id', attributes: {'class': 'enums'}},
			{field: 'sequence', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{field: 'act', attributes: {'class': 'enums act-#:act#'}},
			{field: 'modifytime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
		],
		dataBinding: function(e) {},
		dataBound: function(e) {},
        dataSource: new kendo.data.DataSource({
    		batch: true,
    		page: 1,
    		pageSize: gridpageSize,
    		serverPaging: true,
    		serverSorting: true,
    		serverFiltering: true,
    		transport: {
    			read: {
    				dataType: 'json',//"jsonp" is required for cross-domain requests; use "json" for same-domain requests
    				type: 'POST',
    				url: '<?php echo self::url(M_CLASS, 'json')?>',
    			},
    			update: {
    				beforeSend: function() {},
    				complete: function(xhr) {
    					r = $.parseJSON(xhr.responseText);
    					switch(r.result) {
    						case 0:griderror(r.message);break;
    						case 1:gridsuccess(r.message);break;
    					}
    				},
    				dataType: 'json',
    				type: 'POST',
    				url: '<?php echo self::url(M_CLASS, 'grid_edit')?>',
    			},
    		},
    		schema: {
    			data: function(r){return r.data;},
    			total: function(r){return r.total;},
    			model: {
    				id: 'adarea_id',
                    fields: {
                    	adarea_id: {editable: false},
                    	adareaX: {editable: false},
                    	ad_id: {editable: false},
                    	adX: {editable: false},
                    	lang_id: {editable: false},
                    	sequence: {type: 'number', validation: {required: true, min: 0, max: 65535}},
                    	act: {editable: false},
                    	modifytime: {editable: false},
                    }
                }
    		},
    		sort: {field: 'modifytime', dir: 'desc'}
    	}),
		editable: {
			confirmation: false,
			mode: 'incell'
		},
        filterable: true,
        height: gridheight,
        pageable: {
            refresh: true,
            input: true,
            pageSize: gridpageSize,
            pageSizes: gridpageSizes,
        },
        reorderable: true,
        resizable: true,
        selectable: true,
        sortable: true,
		toolbar: [
		  	{template: '<a class="k-button" onclick="grid_toolbar_add(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'form', array('act'=>'add'))?>\')"><span class="k-icon k-i-plus"></span></a><a class="k-button" onclick="grid_toolbar_edit(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'form', array('act'=>'edit'))?>\', [\'adarea_id\',\'ad_id\',\'lang_id\'])"><span class="k-icon k-i-pencil"></span></a>'},
		  	'save',
		  	'cancel',
		],
    });
});
</script>