<?php echo $form?>
<script>
$(function() {
	$('#form').validate({
		rules: {},
		submitHandler: function() {
			<?php if ('add' == $_GET['act']) {?>
			if (!$('#level').val()) {
				formerror('<?php echo _('[Level] is required')?>');
				return;
			} else {
				if ($('#level').val() == 1 && !$('#up').val()) {
					formerror('<?php echo _('[Up] is required')?>');
					return;
				}
			}
			<?php }?>
			
			$.post('<?php echo $action?>', {
				<?php if ('add' == $_GET['act']) {?>
				level: $('#level').val(),
				up: $('#up').prop('disabled')? 0 : $('#up').val(),
				<?php }?>
				<?php if ('edit' == $_GET['act']) {?>
				<?php echo M_CLASS?>_id: $('#<?php echo M_CLASS?>_id').val(),
				<?php }?>
				name: $('#name').val(),
				sequence: $('#sequence').val(),
				act: $('input[name="act"]:checked').val(),
			}, function(r) {
				r = $.parseJSON(r);
				switch (r.result) {
					case 0:formerror(r.message);break;
					case 1:formconfirm(r);break;
				}
			});
		}
	});
});
</script>