<a href="<?php echo $rank0?>" <?php if ($rank_id == 0) echo 'class="active"'?>><?php echo _('Hot'); ?></a>
<a href="<?php echo $rank1?>" <?php if ($rank_id == 1) echo 'class="active"'?>><?php echo _('Free'); ?></a>
<a href="<?php echo $rank2?>" <?php if ($rank_id == 2) echo 'class="active"'?>><?php echo _('Sponsored'); ?></a>
<a href="<?php echo $rank3?>" <?php if ($rank_id == 3) echo 'class="active"'?>><?php echo _('Latest'); ?></a>
