<div id="content_big" class="albumContentView">
    <div class="row new_nav">
        <div class="col-md-7 tree_box">
            <ol class="breadcrumb">
                <?php echo '<li><a href="' . self::url('album', 'explore') . '">' . _('Explore') . '</a></li>'; ?>
                <!-- Level 1 : categoryarea -->
                <li class="dropdown">
                    <?php
                    echo (!empty($categoryarea_id))
                        ? '<a href="' . $album['categoryarea']['url'] . '" class="dropdown-toggle"><span id="categoryarea_name">' . $album['categoryarea']['name'] . '</span></a>'
                        : '<a href="' . $album['categoryarea']['url'] . '" class="dropdown-toggle"><span id="categoryarea_name">' . _('All Albums') . '</span></a>';
                    ?>
                </li>
                <!-- Level 2 : category -->
                <li class="dropdown">
                    <?php
                    echo '<a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span id="category_name">' . $album['category']['name'] . '</span> <span class="caret"></span></a>';
                    ?>
                    <ul class="dropdown-menu" role="menu">
                        <?php
                        foreach ($categoryarea as $k0 => $v0) {
                            if ($v0['categoryarea_id'] == $categoryarea_id) {
                                foreach ($v0['category'] as $k1 => $v1) {
                                    echo '<li><a style="font-size:14px;" href="' . $v1['url'] . '">' . $v1['name'] . '</a></li>';
                                }
                            }
                        }
                        ?>
                    </ul>
                </li>
            </ol>
        </div>
    </div>
    <h3 class="page_title"><?php echo $album['album']['name'] ?></h3>
    <div id="tem_content">
        <ul>
            <li>
                <div id="slide_pic" class="test"
                     onclick="browseKit_album('<?php echo self::url('album', 'show_photo') ?>', {album_id: '<?php echo $album['album']['album_id'] ?>', keyPress : <?php echo $property['property']['browseKitKeyPress']; ?>})">
                    <div class="album_tags_gift">
                        <?php
                        $tags_text = '';
                        if ($album_tags['slot']) $tags_text = '抽獎';
                        if ($album_tags['exchange']) $tags_text = '兌換';
                        if ($album_tags['slot'] && $album_tags['exchange']) $tags_text = '抽獎 / 兌換';
                        if ($tags_text) echo '<span class="album_tags_gift-txt" alt="' . $tags_text . '" title="' . $tags_text . '">' . $tags_text . '</span>';
                        ?>
                    </div>

                    <div id="album_tags">
                        <?php
                        if ($album_tags['video']) echo '<img alt="影片" title="影片" src="' . static_file('images/assets-v6/play-01.svg') . '">';
                        if ($album_tags['audio']) echo '<img  alt="聲音" title="聲音"  src="' . static_file('images/assets-v6/speaker-01.svg') . '">';
                        $albumPages = $album['album']['page'] . _('pages');
                        ?>
                        <span class="pgtxt1"><span class="pgtxt" alt="<?php echo $albumPages ?>"
                                                   title="<?php echo $albumPages ?>"><?php echo $albumPages ?></span></span>
                    </div>

                    <div class="slide_pic_out">
                        <img alt="<?php echo $album['album']['name'] ?>" title="<?php echo $album['album']['name'] ?>"
                             src="<?php echo $album['album']['cover'] ?>">
                    </div>

                </div>

                <div id="temp_infobox">
                    <ul>
                        <li class="info">
                            <div class="lnr"> <?php if ($property['user']['collected'] && ($album['user']['user_id'] != $user['user_id'])) echo '<p class="need_help"><i class="arrow_in"></i>' . _('Collected') . '</p>'; ?></div>
                            <div class="lnr right">
                                <div class="dropdownItem dropdown-arrow">
                                    <div class="btn-group">
                                        <p class="dropdown-sign dropdown-toggle" data-toggle="dropdown"
                                           aria-expanded="false">
                                            <i class="fa fa-bars"></i>
                                        </p>
                                        <ul class="dropdown-menu" role="menu">
                                            <?php echo implode($album['dropdownMenu']) ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <?php
                        if (!empty($property['album']['eventjoin'])) echo '<li><div class="eventjoin">參賽中 : <a href="' . self::url('event', 'content', ['event_id' => $property['album']['eventjoin']['event_id']]) . '">' . $property['album']['eventjoin']['name'] . '</a></div></li>';
                        ?>
                        <li>
                            <h3><?php echo $album['album']['name'] ?></h3>
                            <?php echo $album['album']['location'] != null ? '<a id="g_maps" href="javascript:void(0)" style="color:#9d9d9d;font-size:22px;margin-left:2%"><i class="fa fa-map-marker" ></i></a>' : null; ?>
                        </li>
                        <li>
                            <div class="by_pic"><img
                                        src="<?php echo URL_STORAGE . Core::get_userpicture($album['user']['user_id']) ?>"
                                        height="101" width="101"
                                        onerror="this.src='<?php echo static_file('images/face_sample.svg') ?>'"></div>
                            <div class="by_info">
                                <p class="by">
                                    by
                                    <a href="<?php echo Core::get_creative_url($album['user']['user_id']) ?>"><?php echo $album['user']['name'] ?></a>
                                </p>
                                <p class="by"><?php echo $album['album']['inserttime'] ?></p>
                            </div>
                        </li>
                        <li>
                            <div class="descrip"><?php echo htmlspecialchars_decode($album['album']['description']) ?></div>
                        </li>
                        <li>
                            <div class="line"></div>
                        </li>
                        </li>
                        <?php echo $property['property']['pc_button']; ?>
                        <li class="edit_new">
                            <a href="javascript:void(0)" title="<?php echo _('釘一下') ?>"
                               onclick="likes('<?php echo $album['album']['album_id'] ?>');">
                                <i name="likes"
                                   class="fa fa-thumb-tack <?php echo ($property['user']['haslikes']) ? 'likes' : null; ?>"></i><span><?php echo $album['album2likes']['count'] ?></></span>
                            </a>
                            <a id="pinpinboardAnchor" href="javascript:void(0)" title="<?php echo _('留言') ?>"><i
                                        class="fa fa-comment-o"></i><?php echo $album['pinpinboard']['count'] ?></a>
                            <a href="javascript:void(0)" title="<?php echo _('Share it!') ?>"
                               onclick="share_album('<?php echo $album['album']['album_id'] ?>', '<?php echo $property['album']['qrcodeUrl'] ?>', '<?php echo $album['album']['cover'] ?>', '<?php echo self::url('album', 'content', ['album_id' => $album['album']['album_id'], 'categoryarea_id' => $album['categoryarea']['categoryarea_id'], 'autoplay' => true]) ?>')">
                                <i class="fa fa-share"></i>
                            </a>
                        </li>
                        <li>
                            <p class="tdtitle"><?php echo _('觀看次數'); ?></p>
                            <p class="tdtxt"><?php echo $album['albumstatistics']['viewed'] ?></p>
                        </li>
                        <?php if ($album['album']['point'] > 0) { ?>
                            <li>
                                <p class="tdtitle"><?php echo _('Savings conditions'); ?>
                                    <a href="javascript:void(0)" onclick="savings_tip()"><img width="15"
                                                                                              src="<?php echo static_file('images/icon-01.png') ?>"></a>
                                </p>
                                <p class="tdtxt money"><?php echo $album['album']['point'] ?>P</p>
                            </li>
                        <?php } ?>
                        <?php if (!empty($property['album']['eventjoin'])) { ?>
                            <li>
                                <p class="tdtitle" style="color:#ee5b8d">
                                    <?php echo _('累積票數'); ?>
                                </p>
                                <p class="tdtxt" style="color:#ee5b8d">
                                    <?php
                                    echo $property['album']['eventjoin']['count'];
                                    if ($property['user']['hasvoted']) echo '&nbsp;' . _('(今日已投票)');
                                    ?>
                                </p>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
                <div class="mobile_button mobiledisplay02"><?php echo $property['property']['mobile_button']; ?></div>
                <?php $tips = ($album['album']['point'] > 0) ? _('pages are contained in the album. Click “Pay Collect” to save all pages!') : _('pages are contained in the album. Click “Free Collect” to save all pages!') ?>
            </li>
            <?php
            if (!empty($other_album)) {
                echo '<li class="removeInPop"><div class="more_title"><p>' . _('您可能會想看') . '</p></div></li>
				<li class="removeInPop">
					<div class="seemore_content">';
                foreach ($other_album as $k0 => $v0) {
                    $tags_gift = null;
                    if ($v0['album']['album_tags']) {
                        $tags_gift = '<div class="album_tags_gift">
                                                <img alt="抽獎" title="抽獎" src="' . static_file('images/assets-v6/gift-01.svg') . '">
                                                <div class="album_tags_gift_bg"></div>
                                            </div>';
                    }
                    echo '<div class="item_box">
                                ' . $tags_gift . '
								<a class="imgh" href="' . $v0['album']['cover_url'] . '"><img src="' . $v0['album']['cover'] . '" onerror="this.src=\'' . static_file('images/origin.jpg') . '\'" height="330" width="220"></a>
								<div class="item_info">
									<div class="info_name">
										<h3> <a class="multi ellipsis" href="' . $v0['album']['name_url'] . '">' . $v0['album']['name'] . '</a></h3>
									</div>
									<a href="' . $v0['user']['url'] . '">
										<div class="info_user">
											<div class="user_face"><img src="' . $v0['user']['picture'] . '" height="101" width="101" onerror="this.src=\'' . static_file('images/face_sample.svg') . '\'"></div>
											<div class="user_name">
												<p class="name_id">' . $v0['user']['name'] . '</p>
												<p><i style="margin-right:5px;" class="fa fa-eye"></i>' . $v0['album']['viewed'] . '</p>
											</div>
										</div>
									</a>
								</div>								
							</div>';
                }
                echo '</div>
				</li>';
            }
            ?>
        </ul>
        <?php if (is_ajax()) echo '<div id="pageCalledByXHR"></div>' ?>
    </div>
</div>
<?php include(dirname(dirname(__FILE__)) . '/pinpinboard.phtml'); ?>

<script type="text/javascript" name="popview">
    $(function () {
        <?php if (!empty($_GET['pinpinboard']) && $_GET['pinpinboard'] == 'true') {
        echo 'window.location = $(\'#pinpinboardAnchor\').attr(\'href\');';
    } ?>

        $('#pinpinboardAnchor').on('click', function () {
            $('.comment_info_textarea').focus();
        })

        <?php if(!empty($property['album']['eventjoin']) && (!$property['user']['hasvoted'])) { ?>
        $('a#vote, a#vote_mobile').on('click', function () {
            $.post('<?php echo self::url('album', 'vote', query_string_parse())?>', {
                act: 'addvote',
                event_id: <?php echo $property['album']['eventjoin']['event_id']?>,
                album_id: '<?php echo $album['album']['album_id']?>',
            }, function (r) {
                r = $.parseJSON(r);
                if (r.result == 1) {
                    r.data = 'Modal';
                    site_jBox(r, 'success');
                } else if (r.result == 2) {
                    site_jBox(r);
                } else {
                    site_jBox(r, 'error');
                }
            });
        })
        <?php } ?>

    })

    function alert_submit(id) {
        var obj = $('input[name=report]:checked');
        var text = '';
        if (obj.length < 1) {
            alert('<?php echo _('Please select a report intent.')?>');
        } else {
            var value = obj.val();
            if (value == 4) {
                text = $('#input04_textarea').val();
            }
            $.post('<?php echo self::url('album', 'report')?>', {
                value: value,
                text: text,
                album_id: id,
                url: window.location.href,
            }, function (r) {
                r = $.parseJSON(r);
                if (r.result == 1) {
                    $('#alert_bg').trigger('click');
                    alert(r.message);
                } else {
                    $('#alert_bg').trigger('click');
                    _jBox(r, 'error');
                }
            });
        }
    }

    function buyalbum() {
        $.post('<?php echo self::url('album', 'buyalbum', query_string_parse())?>', {
            album_id: '<?php echo $album['album']['album_id']?>',
        }, function (r) {
            r = $.parseJSON(r);

            switch (r.result) {
                case 2:
                    if (typeof(window.onbeforeunload) != 'undefined') window.onbeforeunload = null;
                    if (r.data && typeof(r.data.task) != 'undefined') {
                        (typeof(r.data.task.message) != 'undefined' && r.data.task.message.length > 0) ? _TaskAlert(r, 'task') : (r.redirect) ? location.href = r.redirect : null;
                    } else {
                        if (r.redirect) location.href = r.redirect;
                    }
                    break;

                case 4:
                    var myConfirm = new jBox('Confirm', {
                        cancelButton: '<?php echo _('關閉')?>',
                        confirmButton: '<?php echo $property['property']['buyAlbumBoxBtn'] ?>',
                        closeOnConfirm : false,
                        closeButton : 'box',
                        confirm: function () {
                            var recipient = {}, validation = true;
                            <?php if ($property['album']['data']['album']['reward_after_collect'] && $property['property']['balance'] >= 0) { ?>

							    if (!$('input[name="recipient"]').val()) {
							        $('input[name="recipient"]').addClass('warning');
                                    validation = false;
                                } else {
                                    recipient.recipient = $('input[name="recipient"]').val();
							        $('input[name="recipient"]').removeClass('warning') ;
                                }

							    if (!$('input[name="recipient_tel"]').val() || !$.isNumeric($('input[name="recipient_tel"]').val()) ) {
							        $('input[name="recipient_tel"]').addClass('warning');
                                    validation = false;
                                } else {
                                    recipient.recipient_tel = $('input[name="recipient_tel"]').val();
							        $('input[name="recipient_tel"]').removeClass('warning') ;
                                }

							    if(!$('input[name="recipient_address"]').val()) {
							        $('input[name="recipient_address"]').addClass('warning');
                                    validation = false;
                                } else {
                                    recipient.recipient_address = $('input[name="recipient_address"]').val();
							        $('input[name="recipient_address"]').removeClass('warning') ;
                                }

                            <?php } ?>

                            if(validation) {
                                $.post('<?php echo self::url('album', 'buyalbum', query_string_parse())?>', {
                                    buy: true,
                                    recipient: recipient,
                                    album_id: '<?php echo $album['album']['album_id']?>',
                                    point_to_use: $('input[name="customerpoint"]').val(),
                                }, function (r2) {
                                    r2 = $.parseJSON(r2);

                                    switch (r2.result) {
                                        case 1:
                                            _jBox(r2, 'success');
                                            $('a#trip_collect, #preview_mobile').remove();
                                            $('a#read').css('width', (95 / $('#preview').find('a').length) + '%').attr('onclick', 'browseKit_album(\'<?php echo self::url('album', 'show_photo')?>\', {album_id: \'<?php echo $album['album']['album_id']?>\', keyPress : <?php echo $property['property']['browseKitKeyPress']; ?>})').html('<?php echo _('Read')?>').removeClass('white');
                                            if ($('a#vote').length > 0) $('a#vote, a#vote_mobile').removeClass('threebtns').addClass('twobtns');

                                            $('#heart_mobile').attr('onclick', 'browseKit_album(\'<?php echo self::url('album', 'show_photo')?>\', {album_id: \'<?php echo $album['album']['album_id']?>\', keyPress : <?php echo $property['property']['browseKitKeyPress']; ?>})').html('<img src="<?php echo static_file('images/icon_collection_click.svg')?>">');

                                            if (r2.data) {
                                                if (r2.data.task.message.length > 0) _TaskAlert(r2, 'task');
                                            }
                                            if (r2.data.album_count) $('span.albumstatistics').html(r2.data.album_count);
                                            browseKitRefresh();
                                            browseKit_album('<?php echo self::url('album', 'show_photo')?>', {album_id: '<?php echo $album['album']['album_id']?>', keyPress : <?php echo $property['property']['browseKitKeyPress']; ?>});
                                            myConfirm.close();
                                            break;

                                        case 2:
                                            _jBox(r2, 'info');
                                            myConfirm.close();
                                            break;

                                        case 3:
                                            _jBox({message:'P點不足請先儲值'}, 'info');
                                            break;
                                        default:
                                            _jBox(r2, 'error');
                                            myConfirm.close();
                                            break;
                                    }
                                });
                            }
                        },
                        onCloseComplete: function () {
                            myConfirm.destroy();
                        }
                    }).setContent(`<?php echo $property['property']['buyAlbumBoxContent']; ?>`).open();

                    break;

                case 5 :
                    $('a#trip_collect, #preview_mobile').remove();

                    $('a#read').css('width', (95 / $('#preview').find('a').length) + '%').attr('onclick', 'browseKit_album(\'<?php echo self::url('album', 'show_photo')?>\', {album_id: \'<?php echo $album['album']['album_id']?>\', keyPress : <?php echo $property['property']['browseKitKeyPress']; ?>})').html('<?php echo _('Read')?>').removeClass('white');

                    if ($('a#vote').length > 0) $('a#vote, a#vote_mobile').removeClass('threebtns').addClass('twobtns');

                    $('#heart_mobile').attr('onclick', 'browseKit_album(\'<?php echo self::url('album', 'show_photo')?>\', {album_id: \'<?php echo $album['album']['album_id']?>\' keyPress : <?php echo $property['property']['browseKitKeyPress']; ?>})').html('<img src="<?php echo static_file('images/icon_collection_click.svg')?>">');

                    if (r.data) {
                        if (r.data.task.message.length > 0) _TaskAlert(r, 'task');
                    }
                    if (r.data.album_count) $('span.albumstatistics').html(r.data.album_count);
                    browseKitRefresh();
                    browseKit_album('<?php echo self::url('album', 'show_photo')?>', {album_id: '<?php echo $album['album']['album_id']?>', keyPress : <?php echo $property['property']['browseKitKeyPress']; ?>});
                    break;

                default:
                    _jBox(r, 'error');
                    break;
            }
        });
    }

    function checkpoint(i, v) {
        var minPoints = <?php echo $album['album']['point'] ?>,
            maxPoints = 50000,
            customerPoints = <?php echo $property['user']['userpoint'] ?>,
            message = '';
        $('#albumPoint2TWD').html((v/2).toFixed(1));
        if (v < minPoints) {
            message = '<?php echo _('最低為:') ?>' + minPoints + 'P';
        } else if (v > maxPoints) {
            message = '<?php echo _('最高為:') ?>' + maxPoints + 'P';
            $(i).val(maxPoints);
            $('#albumPoint2TWD').html((maxPoints/2).toFixed(1));
        } else if (v > customerPoints) {
            message = '<?php echo _('您的P點不足, 是否前往') ?><a href="javascript:void(0)" onclick="deposit();">儲值</a>?';
        }

        $('p[name="pointTips"]').html(message);
    }

    function deposit() {
        location.href="<?php echo self::url('user', 'point', ['album_id'=> $album['album']['album_id']]) ?>";
    }

    function delete_album() {
        var myConfirm = new jBox('Confirm', {
            cancelButton: '<?php echo _('No')?>',
            confirmButton: '<?php echo _('Yes')?>',
            confirm: function () {
                block_modal = new jBox('Modal', {
                    position: {x: 'center', y: 'center'},
                    width: 150,
                    height: 55,
                    closeOnEsc: false,
                    closeOnClick: false,
                    closeButton: 'title',
                    zIndex: 1500,
                });
                block_modal.setContent('<span style="padding-left:20px;font-weight:bold;color:#2299DD";font-size:26px;><?php echo _('Deleting...'); ?><img src="<?php echo static_file('images/loading.gif'); ?>"></span>').open();

                $.post('<?php echo self::url('user', 'delete_album');?>', {
                    album_id: <?php echo $album['album']['album_id'];?>,
                }, function (r) {
                    window.onbeforeunload = null;
                    block_modal.close();
                    r = $.parseJSON(r);
                    if (r.result == 1) {
                        _jBox(r, 'success_notext');
                    } else {
                        _jBox(r, 'error');
                    }
                });
            },
            onCloseComplete: function () {
                myConfirm.destroy();
            }
        }).setContent(
            '<div class="content">' +
            '<?php echo _('Are you sure you want to delete?')?><br><br><div class="keypoint"><p>※<?php echo _('Attention')?>※</p><?php echo _('The album cannot be restored after deleted. The settlement and download count of this album will be removed.')?></div>' +
            '</div>'
        ).open();
    }

    function likes(id) {
        $.post('<?php echo self::url('album', 'likes') ?>', {
            album_id: id,
        }, function (r) {
            r = $.parseJSON(r);
            switch (r.result) {
                case 1:
                    if (r.data) {
                        $('i[name="likes"]').addClass('likes').next('span').html(parseInt($('i[name="likes"]').next('span').html()) + 1);
                        $('i[name="likes"]').animate({fontSize: "1.2em"}, {
                            queue: false,
                            duration: 80,
                        }).animate({fontSize: "1.5em"}, 50);

                    } else {

                        $('i[name="likes"]').removeClass('likes').next('span').html(parseInt($('i[name="likes"]').next('span').html()) - 1);
                    }
                    break;

                case 2:
                    _jBox(r, 'success_notext');
                    break;

                default :
                    _jBox(r, 'error');
                    break;
            }
        });
    }

    function recommendedBuyAlbum() {
        var myConfirm = new jBox('Confirm', {
            id: 'JboxRecommendedBuyAlbum',
            cancelButton: '<?php echo _('關閉')?>',
            confirmButton: '<?php echo $property['property']['buyAlbumBoxBtn'] ?>',
            closeOnConfirm : false,
            closeButton : 'box',
            confirm: function () {

                var recipient = {}, validation = true;
				<?php if ($property['album']['data']['album']['reward_after_collect'] && $property['property']['balance']>=0) { ?>

                if (!$('input[name="recipient"]').val()) {
                    $('input[name="recipient"]').addClass('warning');
                    validation = false;
                } else {
                    recipient.recipient = $('input[name="recipient"]').val();
                    $('input[name="recipient"]').removeClass('warning') ;
                }

                if (!$('input[name="recipient_tel"]').val() || !$.isNumeric($('input[name="recipient_tel"]').val()) ) {
                    $('input[name="recipient_tel"]').addClass('warning');
                    validation = false;
                } else {
                    recipient.recipient_tel = $('input[name="recipient_tel"]').val();
                    $('input[name="recipient_tel"]').removeClass('warning') ;
                }

                if(!$('input[name="recipient_address"]').val()) {
                    $('input[name="recipient_address"]').addClass('warning');
                    validation = false;
                } else {
                    recipient.recipient_address = $('input[name="recipient_address"]').val();
                    $('input[name="recipient_address"]').removeClass('warning') ;
                }

				<?php } ?>

                if(validation) {

                    $.post('<?php echo self::url('album', 'buyalbum', query_string_parse())?>', {
                        album_id: '<?php echo $album['album']['album_id']?>',
                        buy: true,
                        point_to_use: $('input[name="customerpoint"]').val(),
                        recipient: recipient,
                    }, function (r) {
                        r = $.parseJSON(r);
                        switch (r.result) {
                            case 1:
                                _jBox(r, 'success');
                                $lg.data('lightGallery').destroy();

                                $('a#trip_collect , #preview_mobile').remove();
                                $('a#read').css('width', (90 / $('#preview').find('a').length) + '%').attr('onclick', 'browseKit_album(\'<?php echo self::url('album', 'show_photo')?>\', {album_id: \'<?php echo $album['album']['album_id']?>\'keyPress : <?php echo $property['property']['browseKitKeyPress']; ?>})').html('<?php echo _('Read')?>').removeClass('white');

                                if ($('a#vote').length > 0) $('a#vote, a#vote_mobile').removeClass('threebtns').addClass('twobtns');

                                $('#heart_mobile').attr('onclick', 'browseKit_album(\'<?php echo self::url('album', 'show_photo')?>\', {album_id: \'<?php echo $album['album']['album_id']?>\', keyPress : <?php echo $property['property']['browseKitKeyPress']; ?>})').html('<img src="<?php echo static_file('images/icon_collection_click.svg')?>">');

                                if (r.data) {
                                    if (r.data.task.message.length > 0) _TaskAlert(r, 'task');
                                }
                                if (r.data.album_count) $('span.albumstatistics').html(r.data.album_count);
                                browseKitRefresh();
                                setTimeout(function () {
                                    browseKit_album('<?php echo self::url('album', 'show_photo')?>', {
                                        album_id: '<?php echo $album['album']['album_id']?>',
                                        keyPress : <?php echo $property['property']['browseKitKeyPress']; ?>,
                                        preview_page_length: <?php echo $property['album']['previewPhotos'] ?>});
                                }, 500);
                                myConfirm.close();
                                break;

                            case 2:
                                _jBox(r, 'success_notext');
                                myConfirm.close();
                                break;
                            case 3:
                                _jBox({message:'P點不足請先儲值'}, 'info');
                                break;

                            default:
                                _jBox(r, 'error');
                                myConfirm.close();
                                break;
                        }
                    });
                }
            },
            onCloseComplete: function () {
                myConfirm.destroy();
            }
        }).setContent(`<?php echo $property['property']['buyAlbumBoxContent']; ?>`).open();

        window.RecommendedBuyAlbum = myConfirm;
    }

    function savings_tip() {
        _jBox({'message': '<?php echo _('贊助P點可以閱讀完整作品，P點不足可以到「管理中心」>「商店」>「購買P點'); ?>'}, 'info');
    }

    function share_album(id, qrcode, cover, shareUrl) {
        var str = '<div>' +
            '<ul class="share_album_' + id + '">' +
            '<li class="facebook" title="<?php echo _('分享我的作品至Facebook!') ?>"></li>' +
            '<li class="twitter" title="<?php echo _('分享我的作品至twitter'); ?>"></li>' +
            '<li class="plusone" title="<?php echo _('分享我的作品至Google+'); ?>"></li>' +
            '<li class="pinterest" title="<?php echo _('分享我的作品至pinterest'); ?>" data-media="' + cover + '"></li>' +
            '<li class="line" title="<?php echo _('Share album to Line') ?>"></li>' +
            '<li class="qrcode social-likes__widget" title="<?php echo _('開啟QRcode'); ?>"><a class="imagepop" href="' + qrcode + '"><img width="23" src="<?php echo static_file('images/qr.png')?>" style="padding-top:5px;"></a></li>' +
            '</ul>' +
            '</div><br>' +
            '<div>' +
            '<input style="width:300px;height:2em;" type="text" class="share_url" value="' + shareUrl + '">' +
            '</div>';

        box = new jBox('Modal', {
            closeButton: 'title',
            title: 'Share it',
            width: 350,
            height: 130,
            zIndex: 1002,
            onOpen: function () {
                $('.share_album_' + id).socialLikes({
                    url: shareUrl,
                    title: '<?php echo _('Share the pinpinbox photo album!'); ?>',
                    counters: true,
                    singleTitle: 'Share it!',
                });

                //counter link
                $('.share_album_' + id).on('popup_closed.social-likes', function (event, service) {
                    $(event.currentTarget).socialLikes({forceUpdate: true});
                    var counter = $(event.currentTarget).find('.social-likes__counter_' + service);
                    counter.text(+(counter.text() || 0) + 1).removeClass('social-likes__counter_empty');

                    if (service == 'facebook') {
                        $.post('<?php echo self::url('album', 'clear_task') ?>', {
                            album_id: '<?php echo $album['album']['album_id'] ?>',
                        }, function (r) {
                            r = $.parseJSON(r);
                            switch (r.result) {
                                case 1:
                                    if (r.data) {
                                        if (r.data.task.message.length > 0) _TaskAlert(r, 'task');
                                    }
                                    break;

                                default :

                                    break;
                            }
                        });
                    }
                });

                //initialize social
                $('#social_share').socialLikes({
                    url: '<?php echo self::url('album', 'content', ['album_id' => $album['album']['album_id'], 'categoryarea_id' => $album['categoryarea']['categoryarea_id'], 'autoplay' => true])?>',
                    title: "<?php echo preg_replace('/\s(?=)/', '', htmlspecialchars($album['album']['name'], ENT_QUOTES)) ?>",
                    counters: true,
                    singleTitle: '<?php echo _('Share it!')?>',
                });

                //counter link
                $('#social_share').on('popup_closed.social-likes', function (event, service) {
                    $(event.currentTarget).socialLikes({forceUpdate: true});
                    var counter = $(event.currentTarget).find('.social-likes__counter_' + service);
                    counter.text(+(counter.text() || 0) + 1).removeClass('social-likes__counter_empty');

                    if (service == 'facebook') {
                        $.post('<?php echo self::url('album', 'clear_task') ?>', {
                            album_id: '<?php echo $album['album']['album_id'] ?>',
                        }, function (r) {
                            r = $.parseJSON(r);
                            switch (r.result) {
                                case 1:
                                    if (r.data) {
                                        if (r.data.task.message.length > 0) _TaskAlert(r, 'task');
                                    }
                                    break;

                                default :

                                    break;
                            }
                        });
                    }
                });

                $('.imagepop').magnificPopup({type: 'image',});
            },
        }).setContent(str).open();
    }

    //line icon
    var socialLikesButtons = {
        line: {
            clickUrl: 'http://line.naver.jp/R/msg/text/?<?php echo preg_replace('/\s(?=)/', '', htmlspecialchars($album['album']['name'], ENT_QUOTES)) . ' - ' . self::url('album', 'content', ['album_id' => $album['album']['album_id'], 'categoryarea_id' => $album['categoryarea']['categoryarea_id'], 'autoplay' => true])?>',
            pupupWidth: 650,
            popupHeight: 500,
        }
    };

    //alert用
    function alert_submit() {
        var obj = $('input[name=report]:checked');
        var text = '';
        if (obj.length < 1) {
            alert('<?php echo _('Please select a report intent.')?>');
        } else {
            var value = obj.val();
            if (value == 4) {
                text = $('#input04_textarea').val();
            }
            $.post('<?php echo self::url('album', 'report')?>', {
                value: value,
                text: text,
                album_id: '<?php echo $album['album']['album_id']?>',
            }, function (r) {
                r = $.parseJSON(r);
                if (r.result == 1) {
                    $('#alert_bg').trigger('click');
                    alert(r.message);
                } else if (r.result == 2) {
                    location.href = "<?php echo self::url('user', 'login', ['redirect' => self::url('album', 'content', ['report' => true, 'album_id' => $album['album']['album_id'], 'categoryarea_id' => $album['categoryarea']['categoryarea_id']])]) ?>";
                } else {
                    $('#alert_bg').trigger('click');
                    alert(r.message);
                }
            });
        }
    }
</script>
<script type="text/javascript" src="//media.line.me/js/line-button.js?v=20140411" name="popview"></script>

<script type="text/javascript">
    $(function () {
        <?php
        if ($agent) {
            switch ($agent) {
                case 'mobile':
                    echo 'clickHandler(\'' . self::deeplink('album', 'content', ['album_id' => $album['album']['album_id']]) . '\');';
                    break;
            }
        }

        if ($autoplay) {
            echo 'browseKit_album(\'' . self::url('album', 'show_photo') . '\', {album_id: \'' . $album['album']['album_id'] . '\', keyPress : \''. $property['property']['browseKitKeyPress'] .'\'  });';
        }
        if ($autobuy) {
            if ($user['user_id'] == $album['user']['user_id'] || $property['user']['collected']) {
                echo 'browseKitRefresh();';
                echo 'browseKit_album(\'' . self::url('album', 'show_photo') . '\', {album_id: \'' . $album['album']['album_id'] . '\', keyPress : \''. $property['property']['browseKitKeyPress'] .'\'});';
            } else {
                echo 'buyalbum()';
            }
        }

        ?>

        $('a#g_maps').on('click', function () {
            var location = '<?php echo $album['album']['location'] ?>',
                msg = {
                    'message': '<iframe width="600" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src=\'https://maps.google.com.tw/maps?f=q&hl=zh-TW&geocode=&q=' + location + '&z=16&output=embed&t=\'></iframe>',
                    'data': location
                };
            _jBox(msg, 'map');
        })

        $('.descrip').html($('.descrip').html().autoLink({target: "_blank"}));
        if ($('.descrip').outerHeight() > 130) {
            $('.descrip').showMore({
                minheight: 110,
                buttontxtmore: '更多',
                buttontxtless: '收回',
                buttoncss: 'more_open',
                animationspeed: 250
            });
        }
    });

    $(window).scroll(function () {
        if ($(window).scrollTop() + $(window).height() == $(document).height()) {
            $("#admin_mobile02").css({'position': 'relative'});
        } else {
            $("#admin_mobile02").css({'position': 'fixed'});
        }
    });

    $(document).on('click', '#alert_btn', function (e) {
        alert_submit();
    }).on('click', '.alert_btn', function (e) {
        e.stopPropagation();
        $('#alert_box').fadeIn();
        $('input[name=report]').removeAttr('checked');
        $('#input04_textarea').val('');
        $('#input04_li').hide();
    }).on('click', '#close_alert', function (e) {
        $('#alert_box').fadeOut('slow', function () {
            $('.step02').hide();
            $('.step01').show();
        });
    }).on('click', '#alert_bg', function (e) {
        $('#alert_box').fadeOut(function () {
            $('#close_alert').trigger('click');
        });
    }).on('click', '.step02 .cancel', function (e) {
        $('.step02').hide();
        $('.step01').show();
    }).on('click', '#next_step', function (e) {
        var obj = $('input[name=report]:checked');
        if (obj.val() == 7) {
            $('.step01').hide();
            $('.step02').show();
        } else {
            alert_submit();
        }
    });

    function ios_notice() {
        var myModal = new jBox('Modal', {
            title: '',
            closeButton: 'title',
            onCloseComplete: function () {
                myModal.destroy();
            }
        }).setContent(
            '<div class="content">' +
            '<p class="keypoint"><img src="<?php echo static_file('images/info.png')?>">&nbsp;<?php echo _('Coming Soon!')?></p>' +
            '</div>'
        ).open();
    }

    if ($('.mobilehide02').css('display') == 'block') {
        var target = $('#trip_collect');
        var position = 'n';
    } else {
        var target = $('.mobiledisplay02');
        var position = 'e';
    }

    <?php if (isset($_GET['report']) && $_GET['report']) echo '$(".alert_btn").trigger("click")'; ?>
</script>
