<?php echo $form?>
<script>
$(function() {
	$('#form').validate({
		rules: {},
		submitHandler: function() {
			if (!$('#lang_id').val()) {
				formerror('<?php echo _('Required for : ').$this->get_adminmenu_name_by_class('lang')?>');
				return;
			}
			
			$.post('<?php echo $action?>', {
				keyword_original: $('#keyword_original').val(),
				keyword: $('#keyword').val(),
				lang_id: $('#lang_id').val(),
				value: $('#value').val(),
			}, function(r) {
				r = $.parseJSON(r);
				switch (r.result) {
					case 0:formerror(r.message);break;
					case 1:
						$('#keyword_original').val($('#keyword').val());//替換 keyword, 避免 edit 時對不上
						formconfirm(r);
						break;
				}
			});
		}
	});

	<?php if ('edit' == $_GET['act']) {?>
	$('#lang_id').on('keyup change', function() {
		$.post('<?php echo self::url(M_CLASS, 'extra0')?>', {		
			keyword_original: $('#keyword_original').val(),
			lang_id: $(this).val(),
		}, function(r) {
			r = $.parseJSON(r);
			$('#value').val(r.data.value || '');
			$('#inserttime').text(r.data.inserttime || '');
			$('#modifytime').text(r.data.modifytime || '');
			$('#modifyadmin_id').text(r.data.modifyadmin_id || '');
		});
	});
	<?php }?>
});
</script>