<?php echo $index?>
<script>
$(function(){
    $('#grid').kendoGrid({
    	columns: [
			{field: '<?php echo M_CLASS?>_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{field: 'name', attributes: {'class': 'string'}},
			{field: 'modifytime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
		],
		dataBinding: function(e) {},
		dataBound: function(e) {},
        dataSource: new kendo.data.DataSource({
    		page: 1,
    		pageSize: gridpageSize,
    		serverPaging: true,
    		serverSorting: true,
    		serverFiltering: true,
    		transport: {
    			read: {
    				dataType: 'json', //"jsonp" is required for cross-domain requests; use "json" for same-domain requests
    				type: 'POST',
    				url: '<?php echo self::url(M_CLASS, 'json')?>',
    			}
    		},
    		schema: {
    			data: function(r){return r.data;},
    			total: function(r){return r.total;}
    		},
    		sort: {field: 'modifytime', dir: 'desc'}
    	}),
        filterable: true,
        height: gridheight,
        pageable: {
            refresh: true,
            input: true,
            pageSize: gridpageSize,
            pageSizes: gridpageSizes,
        },
        reorderable: true,
        resizable: true,
        selectable: true,
        sortable: true,
		toolbar: [
		  	{template: '<a class="k-button" onclick="grid_toolbar_add(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'form', array('act'=>'add'))?>\')"><span class="k-icon k-i-plus"></span></a><a class="k-button" onclick="grid_toolbar_edit(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'form', array('act'=>'edit'))?>\', [\'<?php echo M_CLASS?>_id\'])"><span class="k-icon k-i-pencil"></span></a><a class="k-button" onclick="grid_toolbar_delete(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'delete')?>\', [\'<?php echo M_CLASS?>_id\'])"><span class="k-icon k-i-close"></span></a>'},
		],
    });
});
/*
jQuery('#jqgrid').jqGrid({
	caption: '<?php echo $this->get_adminmenu_name_by_class(M_CLASS)?>',
   	url: '<?php echo self::url(M_CLASS, 'json')?>',
   	mtype: 'GET',
	datatype: 'json',
   	colNames: ['<?php echo M_CLASS?>_id', 'name', 'modifytime', 'modifyname'],
   	colModel: [
   		{name:'<?php echo M_CLASS?>_id', index:'<?php echo M_CLASS?>.<?php echo M_CLASS?>_id', width:2, align:'right'},
   		{name:'name', index:'<?php echo M_CLASS?>.name', width:3},
   		{name:'modifytime', index:'<?php echo M_CLASS?>.modifytime', width:3, align:'center'},
   		{name:'modifyname', index:'<?php echo M_CLASS?>.modifyadmin_id', width:2, align:'center'}
   	],
   	rowNum: 20,
   	rowList: [20,50,100],
    autowidth: true,
    height: 'auto',
   	pager: '#pjqgrid',
   	sortname: '<?php echo M_CLASS?>.modifytime',
   	sortorder: 'desc',
   	viewrecords: true,
    gridview: true
});
jQuery('#jqgrid').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: true});
jQuery('#jqgrid').jqGrid('navGrid', '#pjqgrid', {
	search: false,
	addfunc: function () {
		location.href = '<?php echo self::url(M_CLASS, 'form', array('act'=>'add'))?>';
	},
	editfunc: function (id) {
		var ret = jQuery("#jqgrid").jqGrid('getRowData', id);
		location.href = '<?php echo self::url(M_CLASS, 'form', array('act'=>'edit'))?>&<?php echo M_CLASS?>_id='+ret.<?php echo M_CLASS?>_id;
	},
	delfunc: function (id) {
		if (confirm('<?php echo _('Are you sure to delete it?')?>') && id) {
			var ret = jQuery("#jqgrid").jqGrid('getRowData', id);
			$.post('<?php echo self::url(M_CLASS, 'delete')?>', {
				<?php echo M_CLASS?>_id: ret.<?php echo M_CLASS?>_id
			}, function(response){
				response = $.parseJSON(response);
				var result = response.result, message = response.message;
				if (result) {
					jQuery("#jqgrid").jqGrid('delRowData', id);
					alert(message);
				} else {
					alert(message);
				}
			});
		}
	}
});
*/
</script>