<script>
    function countdown(time) {
        $('.count_area').countdown(time, function (event) {
            $(this).find('span.day').html(event.strftime('%D'));
            $(this).find('span.hour').html(event.strftime('%H'));
            $(this).find('span.minute').html(event.strftime('%M'));
            $(this).find('span.second').html(event.strftime('%S'));
        });
    }
	<?php
	switch ($event['contribution']) {
		//一般活動
		case 0 :
			$_this_event = 'private';
			$album_list_class = null;
			$description_class = 'active';
			$img1 = static_file('images/eventdetails_02.svg');
			break;

		//投稿活動
		default :
			$_this_event = 'public';
			/*
				$album_list_class = (!empty($_GET['searchtype'])) ? null : 'active' ;
				$description_class = (!empty($_GET['searchtype'])) ?  'active':  null;
			*/
			//預設都開啟參賽作品標籤

			if ((!empty($_GET['p']) && $_GET['p'] == 'info') || count($album) == 0) {
				$album_list_class = null;
				$description_class = 'active';
				$img1 = static_file('images/eventdetails_02.svg');
				$img2 = static_file('images/otherworks.svg');
			} else {
				$album_list_class = 'active';
				$description_class = null;
				$img1 = static_file('images/eventdetails.svg');
				$img2 = static_file('images/otherworks_02.svg');
			}

			break;
	}

	$href = self::url('event', 'join', array('event_id' => $event['event_id']));
	$onclick = null;
	if (empty(self::user_get())) {
		$href = 'javascript:void(0)';
		$onclick = 'onclick="var r = {result: 0, message: \'' . _('Please login first.') . '\', redirect: \'' . self::url('user', 'login', array('redirect' => self::url('event', 'join', array('event_id' => $event['event_id'])))) . '\'};site_jBox(r);"';
	} elseif ($event['status'] == 'expired') {
		$href = 'javascript:void(0)';
		$onclick = 'onclick="var r = {result: 0, message: \'' . _('Event is expired.') . '\'};site_jBox(r);"';
	}
	?>

</script>
<div class="mobile_button mobiledisplay02"
     style="height:120px;background-color: transparent;width:auto; margin-left: -5%;">
	<?php echo ($_this_event == 'public' && $event['contribute_status'] == 'unexpired') ? '<a href="#" data-uri="' . self::deeplink('event', 'join', ['event_id' => $event['event_id']]) . '" onclick="clickHandler(this.dataset.uri)" class="join" style="width:100%;"><img src="' . static_file('images/contribute.png') . '" onerror="this.onerror=null; this.src=\'' . static_file('images/contribute.png') . '\'"></a>' : null; ?>
	<?php echo ($_this_event == 'public' && $event['contribute_status'] == 'unexpired') ? $exchange_page['mobile'] : null ?>
</div>
<!-- 內容頁開始 -->
<div id="act_content">
    <div id="act_right">
        <div class="act_info">
            <ul>
                <li>
                    <ul id="social_share" class="social-likes social-likes_notext"
                        data-title="<?php echo $event['name']; ?>">
                        <li class="facebook" title="<?php echo _('Share event to Facebook'); ?>"></li>
                        <li class="twitter" title="<?php echo _('Share event to twitter'); ?>"></li>
                        <li class="plusone" title="<?php echo _('Share event to Google+'); ?>"></li>
                        <li class="pinterest" title="<?php echo _('Share event to pinterest'); ?>"
                            data-media="<?php echo $event['image']; ?>"></li>
                        <li class="line" title="<?php echo _('Share event to line'); ?>"></li>
                    </ul>
                </li>
            </ul>
        </div>

        <div class="act_else">
            <ul>
                <li><h3 class="eventtitle"><?php echo $event['name'] ?></h3></li>
                <li>
                    <div class="act_pic"><a href="javascript:void(0)"><img src="<?php echo $event['image'] ?>"></a>
                    </div>
                </li>
                <li class="float_left">
                    <div class="count_area" id="time">
                        <img src="<?php echo static_file('images/assets-v5/icon-countdown-r.png') ?>" height="27"
                             width="27" class="clock">
						<?php
						if ($event['status'] == 'prepare') {
							echo '<span>'._('活動尚未開始').'</span>';
						}else if ($event['status'] == 'unexpired') {
							echo '<p class="date"><span class="day"></span><br>'._('days').'</p>
                                <p class="date"><span class="hour"></span><br>'._('hr').'</p>
                                <p class="date"><span class="minute"></span><br>'._('min').'</p>
                                <p class="date"><span class="second"></span><br>'._('sec').'</p>';
						} else {
							echo '<span>'._('This activity has ended!').'</span>';
						}
						?>
                    </div>
                    <script>countdown('<?php echo $event['endtime']?>')</script>
                    <div id="famous"><img src="<?php echo static_file('images/assets-v5/icon-popularity-r.png') ?>"
                                          height="28" width="27"><?php echo _('Popularity') ?><span
                                class="bigtxt"><?php echo $event['popularity'] ?></span></div>
                    <?php
                    if ($event['contribute_starttime'] != '0000-00-00 00:00:00') echo '<li style="margin:0px;">'._('投稿期間').date('Y/m/d H:i', strtotime($event['contribute_starttime'])).' ~ '.date('Y/m/d H:i', strtotime($event['contribute_endtime'])).'</li>';
                    if ($event['vote_starttime'] != '0000-00-00 00:00:00') echo '<li>'._('投票期間').date('Y/m/d H:i', strtotime($event['vote_starttime'])).' ~ '.date('Y/m/d H:i', strtotime($event['vote_endtime'])).'</li>';
                    ?>
                </li>
                <li>
					<?php if ($_this_event == 'public') { ?>
                        <div id="act_search">
                            <div></div>
                            <div class="big_item">
                                <select id="join_searchtype_pc" name="searchtype">
                                    <option value="album_id" <?php if ($searchtype == 'album_id') echo 'selected' ?>><?php echo _('編號'); ?></option>
                                    <option value="album" <?php if ($searchtype == 'album') echo 'selected' ?>><?php echo _('Albums'); ?></option>
                                    <option value="user" <?php if ($searchtype == 'user') echo 'selected' ?>><?php echo _('Author'); ?></option>
                                </select>
                            </div>
                            <input type="text" id="join_searchkey_pc" class="actsearch_txt" name="join_searchkey"
                                   value="<?php if (!empty($searchkey)) echo $searchkey ?>">
                            <a href="javascript:void(0)" class="clear_box"><i class="fa fa-times"></i></a>
                        </div>
					<?php } ?>
                </li>
                <li class="mobilehide"><?php echo ($_this_event == 'public') ? $exchange_page['web'] : null ?></li>
				<?php
				if ($_this_event == 'public' && $event['contribute_status'] == 'unexpired') echo '<li class="float_right mobilehide"><a href="' . $href . '" class="join" ' . $onclick . '>' . _('I want to join') . '</a></li>';
				?>
            </ul>
        </div>
    </div>
    <div id="act_left">
        <h2><?php // echo $event['name']?></h2>
        <div class="act_pic mobilehide02"><a href="javascript:void(0)"><img src="<?php echo $event['image'] ?>"></a>
        </div>
        <div id="tab-container" class="tab-container">
            <!-- Tabs-->
            <ul class='etabs'>
                <li id="description" class="<?php echo $description_class; ?>" name="tabs1">
                    <a href="#tab02" data-img="eventdetails">
                        <i class="fa fa-info-circle mobiledisplay"></i>
                        <span class="mobiledisplay"><img class="mobilehide" src="<?php echo $img1 ?>"></span>
                    </a>
                </li>
				<?php
				echo ($_this_event == 'public') ? '<li name="tabs2" onclick="msry();" class="' . $album_list_class . ' "><a href="#tab01" data-img="otherworks"><i class="fa fa-users mobiledisplay"></i><span class="mobiledisplay"><img class="mobilehide" src="' . $img2 . '"></span></a></li>' : null;
				echo ($_this_event == 'public' && count($user_album) != 0) ? '<li name="tabs3" onclick="msry();" ><a id="my_albums" href="#tab04" data-img="myworks"><i class="fa fa-user mobiledisplay"></i><span class="mobiledisplay"><img class="mobilehide" src="' . static_file('images/myworks.svg') . '"></span></a></li>' : null;
				?>
                <li name="tabs4"><a href="#tab03" data-img="messageboard"><i
                                class="fa fa-comments mobiledisplay"></i><span class="mobiledisplay"><img
                                    class="mobilehide"
                                    src="<?php echo static_file('images/messageboard.svg') ?>"></span></a></li>
            </ul>
            <!-- //Tabs-->
            <!-- Tabs content-->
            <div class="tab_content ">
                <div id="tab01" class="tab <?php echo $album_list_class ?>">
                    <div class="act_title mobiledisplay"><?php echo _('參賽作品'); ?></div>
                    <div class="water_content">
						<?php
						foreach ($album as $k => $v) {
							echo '
							<div id="my_' . $v['album_id'] . '" data-album_id="' . $v['album_id'] . '" class="item_box">';
							echo ($k <= ($event['show_rank_num'] - 1)) ? '<div class="album_award"><div class="award_num">' . ($k + 1) . '</div></div>' : null;
							echo '<a href="javascript:void(0)" onclick="a_album_item=[]; browseKit_album(\'' . self::url('album', 'show_photo') . '\', {album_id:' . $v['album_id'] . '})" data-album_id="' . $v['album_id'] . '">
										<img src="' . $v['cover'] . '" ></a>';
							echo in_array($v['album_id'], $user_voted)
								? '<div class="vote_btn" data-album_id="' . $v['album_id'] . '"><a href="javascript:void(0)" class="vote_box active"><img class="voteicon" src="' . static_file('images/assets-v6/icon-ticket-green-25.svg') . '"><span class="votenum">' . $v['vote'] . '</span></a></div>'
								: '<div class="vote_btn" data-album_id="' . $v['album_id'] . '"><a href="javascript:void(0)" class="vote_box "><img class="voteicon" src="' . static_file('images/assets-v6/icon-ticket-green-25.svg') . '"><span class="votenum">' . $v['vote'] . '</span></a></div>';
							echo '	
								<div class="item_info">
									<div class="info_icon">
										<a href="javascript:void(0)" onclick="share_album(' . $v['album_id'] . ', \'' . $v['qrcodeUrl'] . '\', \'' . $v['cover'] . '\')"><i class="fa fa-share add_info"></i></a>
										<a href="' . $v['url'] . '" target="_blank"><i class="fa fa-exclamation add_info"></i></a>
									</div>
									<div class="info_name">
										<h3> <a href="' . $v['url'] . '" target="_blank">' . $v['name'] . '</a></h3>
										<p>' . _('編號') . '：' . $v['album_id'] . '</p>
									</div>
									<a href="' . $v['user_url'] . '">
										<div class="info_user">
											<div class="user_face"><img src="' . $v['picture'] . '" height="101" width="101" onerror="this.src=\'' . static_file('images/face_sample.svg') . '\'"></div>
											<div class="user_name">
												<p class="name_id">' . $v['user_name'] . '</p>
												<p><i class="fa fa-eye"></i>' . $v['viewed'] . '</p>
											</div>
										</div>
									</a>
								</div>
							</div>';
						}
						?>
                    </div>
                </div>
                <div id="tab04" class="tab">
                    <div class="act_title mobiledisplay"><?php echo _('我的作品'); ?></div>
                    <div class="water_content">
						<?php
						foreach ($user_album as $k => $v) {
							echo '
						<div id="my_' . $v['album_id'] . '" data-album_id="' . $v['album_id'] . '" class="item_box">
							<a href="javascript:void(0)" onclick="a_album_item=[]; browseKit_album(\'' . self::url('album', 'show_photo') . '\', {album_id:' . $v['album_id'] . '})" data-album_id="' . $v['album_id'] . '">
								<img src="' . $v['cover'] . '" ></a>';
							echo in_array($v['album_id'], $user_voted)
								? '<div class="vote_btn" data-album_id="' . $v['album_id'] . '"><a href="javascript:void(0)" class="vote_box active"><i class="fa fa-thumbs-o-up"></i><span>' . $v['vote'] . '</span></a></div>'
								: '<div class="vote_btn" data-album_id="' . $v['album_id'] . '"><a href="javascript:void(0)" class="vote_box"><i class="fa fa-thumbs-o-up"></i><span>' . $v['vote'] . '</span></a></div>';
							echo '	
							<div class="item_info">
								<div class="info_icon">
									<a href="javascript:void(0)" onclick="share_album(' . $v['album_id'] . ', \'' . $v['qrcodeUrl'] . '\', \'' . $v['cover'] . '\')"><i class="fa fa-share add_info"></i></a>
									<a href="' . $v['url'] . '" target="_blank"><i class="fa fa-exclamation add_info"></i></a>
								</div>										
								<div class="info_name">
									<h3> <a href="' . $v['url'] . '" target="_blank">' . $v['name'] . '</a></h3>
									<p>' . _('編號') . '：' . $v['album_id'] . '</p>
								</div>
								<a href="' . $v['user_url'] . '">
									<div class="info_user">
										<div class="user_face"><img src="' . $v['picture'] . '" height="101" width="101" onerror="this.src=\'' . static_file('images/face_sample.svg') . '\'"></div>
										<div class="user_name">
											<p class="name_id">' . $v['user_name'] . '</p>
											<p><i class="fa fa-eye"></i>' . $v['viewed'] . '</p>
										</div>
									</div>
								</a>
							</div>
						</div>';
						}
						?>
                    </div>
                </div>

                <div id="tab02" class="tab <?php echo $description_class ?>">
                    <div class="act_title mobiledisplay">活動詳情</div>
                    <div id="act_more_all"><?php echo $event['description'] ?></div>
                </div>
                <div id="tab03" class="tab">
                    <div class="act_title mobiledisplay">留言板</div>
					<?php include(dirname(dirname(__FILE__)) . '/pinpinboard.phtml'); ?>
                </div>
            </div>
            <!--bot tabs-->
            <ul class='etabs'>
                <li name="tabs1" id="description" class="<?php echo $description_class; ?>">
                    <a href="#tab02" data-img="eventdetails">
                        <i class="fa fa-info-circle mobiledisplay"></i>
                        <span class="mobiledisplay"><img class="mobilehide" src="<?php echo $img1 ?>"></span>
                    </a>
                </li>
				<?php
				echo ($_this_event == 'public') ? '<li name="tabs2" class="' . $album_list_class . '"><a href="#tab01" data-img="otherworks"><i class="fa fa-users mobiledisplay"></i><span class="mobiledisplay"><img class="mobilehide" src="' . $img2 . '"></span></a></li>' : null;
				echo ($_this_event == 'public' && count($user_album) != 0) ? '<li name="tabs3" class=""><a id="my_albums" href="#tab04" data-img="myworks"><i class="fa fa-user mobiledisplay"></i><span class="mobiledisplay"><img class="mobilehide" src="' . static_file('images/myworks.svg') . '"></span></a></li>' : null;
				?>
                <li name="tabs4">
                    <a href="#tab03" data-img="messageboard"><i class="fa fa-comments mobiledisplay"></i>
                        <span class="mobiledisplay"><img class="mobilehide"
                                                         src="<?php echo static_file('images/messageboard.svg') ?>"></span>
                    </a>
                </li>
            </ul>
            <!-- //bot tabs-->
            <!-- //Tabs content-->
        </div>
    </div>
</div>
</div>
<div id="show_photo" style="display:none;"></div>
<script>
    window.onload = msry;

    //search
    $('input[name="join_searchkey"]').on('keypress', function (e) {
        if (e.which == 13 || e.keyCode == 13) join_search();
    });

    function join_search() {
        var type = $('#join_searchtype_pc :selected').val();
        var key = $('#join_searchkey_pc').val();
		<?php
		$tmp = array(
			'event_id' => $event['event_id'],
		);
		?>
        (key == '') ? location.href = '<?php echo self::url('event', 'content', $tmp)?>&searchtype=' + type : location.href = '<?php echo self::url('event', 'content', $tmp)?>&searchtype=' + type + '&searchkey=' + encodeURIComponent(key);
    }

    $(function () {
        $('.vote_btn').on('click', function () {
            var event_status = '<?php echo $event['status']?>';
            if (event_status == 'expired') {
                var r = {result: 0, message: '<?php echo _('Event is expired.')?>'};
                site_jBox(r);
                return;
            }

            var act = 'addvote', obj_div = $(this), obj = obj_div.find('a'), num_display = obj.find('span');

            if (obj.hasClass('active')) {
                _jBox({message: '<?php echo _('今天已經投過票囉, 請明天再來。') ?>'}, 'error');
            } else {
                obj_div.removeClass('vote_btn');
                $.post('<?php echo self::url('event', 'vote', query_string_parse())?>', {
                    act: act,
                    event_id: <?php echo $event['event_id']?>,
                    album_id: $(this).data('album_id'),
                }, function (r) {
                    r = $.parseJSON(r);
                    if (r.result == 1) {
                        //取消投票 取消投票及總票數
                        r.data = 'Modal';
                        site_jBox(r, 'success');
                        obj.removeClass('active');
                        num_display.text(Number(num_display.html()) - 1);
                        $('.bigtxt').text(Number($('.bigtxt').html()) - 1);
                    } else if (r.result == 2) {
                        //完成投票 累加投票及總票數
                        r.data = 'Modal';
                        site_jBox(r, 'success');
                        obj.addClass('active');
                        num_display.text(Number(num_display.html()) + 1);
                        $('.bigtxt').text(Number($('.bigtxt').html()) + 1);
                    } else if (r.result == 3) {
                        site_jBox(r);
                    } else {
                        site_jBox(r, 'error');
                    }
                });
            }
        });
		<?php echo $auto_vote; ?>
		<?php echo $auto_tab; ?>
		<?php echo $auto_play; ?>
        $(window).scroll(function () {
            var $this = $(document).scrollTop(), $taget = $("#act_right");
            ($this > 63 && $(window).width() > 1024 && $(window).height() > $taget.outerHeight() + $("#header").outerHeight() + $("#footer").outerHeight() + 20) ? $taget.css("top", $this) : $taget.css("top", 20);
        });

        //clear searchkey
        $(".clear_box").hide();
        $(".actsearch_txt").on("keydown", function () {
            ($(".actsearch_txt").val() != '' ) ? $(".clear_box").show() : $(".clear_box").hide();
        });
        $(".clear_box").click(function () {
            $(".actsearch_txt").val("");
            $(".clear_box").hide();
        });

        $(window).resize(function () {
            ($(window).width() > 1024) ? $(".social-likes__widget_line").hide() : $(".social-likes__widget_line").show();
        })

        $('.etabs li a').hover(function () {
            $(this).find('img').attr('src', '<?php echo static_file('images/') ?>' + $(this).data('img') + '_02.svg');
        }, function () {
            if (!$(this).parent('li').hasClass('active')) {
                $(this).find('img').attr('src', '<?php echo static_file('images/') ?>' + $(this).data('img') + '.svg');
            }
        });

        $('li[name^="tabs"]>a').on('click', function () {
            name = $(this).parent('li').attr('name');
            _thisObj = $('li[name="' + name + '"]');
            _thisObjImage = '<?php echo static_file('images/') ?>' + _thisObj.children('a').data('img') + '_02.svg';
            _thisObjImage2 = '<?php echo static_file('images/') ?>' + _thisObj.children('a').data('img') + '.svg';
            if (_thisObj.hasClass('active')) {
                _thisObj.addClass('active').find('img').attr('src', _thisObjImage);
                _thisObj.siblings('li').each(function (k, v) {
                    $(v).removeClass('active').find('img').attr('src', '<?php echo static_file('images/') ?>' + $(v).children('a').data('img') + '.svg');
                })
            }
        });

    });

    $(document).on('click', '#show_tutorial_img', function () {
        $.post('<?php echo self::url('event', 'tutorial_img')?>', {
            event_id: <?php echo $event['event_id']?>,
        }, function (r) {
            r = $.parseJSON(r);
            if (r.result == 1) {
                var html = '';
                for (var i in r.data) {
                    html += '<img src="' + r.data[i] + '">';
                }
                $('#show_photo').html(html);
                browseKit();
            } else {
                site_jBox(r, 'error');
            }
        });
    }).on('click', '.share_url', function () {
        this.select();
    });

    function share_album(id, qrcode, cover) {
        var str = '<div>' +
            '<ul class="share_album_' + id + '">' +
            '<li class="facebook" title="<?php echo _('分享我的參賽作品至Facebook!') ?>"></li>' +
            '<li class="twitter" title="<?php echo _('分享我的參賽作品至twitter'); ?>"></li>' +
            '<li class="plusone" title="<?php echo _('分享我的參賽作品至Google+'); ?>"></li>' +
            '<li class="pinterest" title="<?php echo _('分享我的參賽作品至pinterest'); ?>" data-media="' + cover + '"></li>' +
            '<li class="line" title="<?php echo _('Share album to Line') ?>"></li>' +
            '<li class="qrcode social-likes__widget" title="<?php echo _('開啟QRcode'); ?>"><a class="imagepop" href="' + qrcode + '"><img width="23" src="<?php echo static_file('images/qr.png')?>" style="padding-top:5px;"></a></li>' +
            '</ul>' +
            '</div><br>' +
            '<div>' +
            '<input style="width:300px" type="text" class="share_url" value="<?php echo self::url('album', 'content', ['album_id' => '']);?>' + id + '">' +
            '</div>',
            lineUrl = 'http://line.naver.jp/R/msg/text/?<?php echo urlencode(self::url('album', 'content', ['album_id' => null]))?>' + id;

        box = new jBox('Modal', {
            closeButton: 'title',
            title: 'Share it',
            width: 350,
            height: 130,
            zIndex: 200,
            onOpen: function () {
                socialLikesButtons.line.clickUrl = lineUrl;
                $('.share_album_' + id).socialLikes({
                    url: '<?php echo self::url('album', 'content', ['album_id' => '']);?>' + id,
                    title: '<?php echo _('Share the pinpinbox photo album!'); ?>',
                    counters: true,
                    singleTitle: 'Share it!',
                });

                $('.imagepop').magnificPopup({type: 'image',});
            },
        }).setContent(str).open();
    }

    function recommendedBuyAlbum(album_id) {
        $.post('<?php echo self::url('event', 'content_property') ?>', {
            album_id: album_id,
        }, function (r) {
            r = $.parseJSON(r);
            switch (r.result) {
                case 1:
                    var myConfirm = new jBox('Confirm', {
                        id: 'JboxRecommendedBuyAlbum',
                        cancelButton: '<?php echo _('No')?>',
                        confirmButton: r.data.property.buyAlbumBoxBtn,
                        confirm: function () {
                            $.post('<?php echo self::url('album', 'buyalbum', query_string_parse())?>', {
                                album_id: album_id,
                                buy: true,
                                point_to_use: $('input[name="customerpoint"]').val(),
                            }, function (r2) {
                                r2 = $.parseJSON(r2);
                                switch (r2.result) {
                                    case 1:
                                        $lg.data('lightGallery').destroy();

                                        if (r2.data) {
                                            if (r2.data.task.message.length > 0) _TaskAlert(r2, 'task');
                                        }

                                        setTimeout(function () {
                                            browseKitRefresh();
                                            browseKit_album('<?php echo self::url('album', 'show_photo')?>', {album_id: album_id});
                                        }, 700);

                                        break;

                                    case 2:
                                        location.href = '<?php echo self::url('user', 'login', ['redirect' => self::url('event', 'content', ['event_id' => $event['event_id'], 'auto_play' => null])]) ?>' + album_id;
                                        break;
                                    case 3:
                                        deposit();
                                        break;

                                    default:
                                        _jBox(r, 'error');
                                        break;
                                }
                            });

                        },
                        onCloseComplete: function () {
                            myConfirm.destroy();
                        }
                    }).setContent(r.data.property.buyAlbumBoxContent).open();

                    window.RecommendedBuyAlbum = myConfirm;
                    break;

                default :

                    break;
            }
        });
    }

    function msry() {
        setTimeout(function () {
            var $container = $('.water_content');
            $gird = $container.masonry({
                itemSelector: '.item_box',
                horizontalOrder: true,
            });
        }, 500);
    }

    //line icon
    var socialLikesButtons = {
        line: {
            clickUrl: 'http://line.naver.jp/R/msg/text/?<?php echo $event['title'] . '  -  ' . self::url('event', 'content', array('event_id' => $event['event_id']))  ?>',
            pupupWidth: 650,
            popupHeight: 500,
        }
    };

    //initialize social
    $('#social_share').socialLikes({
        url: '<?php echo self::url('event', 'content', array('event_id' => $event['event_id'], 'p' => 'info')); ?>',
        title: '<?php echo _('Share the pinpinbox photo album!'); ?>',
        counters: true,
        singleTitle: 'Share it!',
    });

    //counter link
    $('#social_share').on('popup_closed.social-likes', function (event, service) {
        $(event.currentTarget).socialLikes({forceUpdate: true});
        var counter = $(event.currentTarget).find('.social-likes__counter_' + service);
        counter.text(+(counter.text() || 0) + 1).removeClass('social-likes__counter_empty');
    });

    deeplink.setup({
        iOS: {
            appName: "pinpinbox",
            appId: "<?php echo Core::settings('IOS_APP_ID'); ?>",
        },
        android: {
            appId: "<?php echo Core::settings('ANDROID_APP_URL'); ?>"
        }
    });

    function deposit() {
        window.open('<?php echo self::url('user','point', ['eventcontent'=>encrypt([$event['event_id']])]) ?>', 'userpoint',  config='height=800,width=1200');
    }

    function clickHandler(uri) {
        deeplink.open(uri);
        return false;
    }

</script>
<!-- Line  -->
<script type="text/javascript" src="//media.line.me/js/line-button.js?v=20140411"></script>