<div id="content" class="temp">
	<h3 class="page_title"><?php echo _('Create'); ?></h3>
	<div id="tem_tips">
		<div class="tips_image" style="display:block;"><img src="<?php echo static_file('images/tem_start.png'); ?>" height="621" width="1880" ></div>
	</div>

	<div class="row new_nav">
		<div class="col-md-7 tree_box">
			<ol class="breadcrumb">
				<img src="<?php echo static_file('images/p_icon.png') ?>" height="19" width="19" alt="">
				<?php echo '<li><a href="'.self::url('template', 'index').'">'._('所有版型').'</a></li>'; ?>
				<!-- Level 1 : style -->
				<li class="dropdown">
					<?php 
						echo (!empty($style_name)) 
						? '<a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span id="categoryarea_name">'.$style_name.'</span> <span class="caret"></span></a>'
						: '<a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span id="categoryarea_name">'._('所有版型').'</span> <span class="caret"></span></a>';
					?>
					<ul class="dropdown-menu" role="menu">
						<?php 
							foreach($a_style as $k0 => $v0) {
								echo '<li><a href="'.$v0['url'].'">'.$v0['name'].'</a></li>';
							}
						?>
					</ul>
				</li>
			</ol>
		</div>
		<div class="col-md-5">
			<div class="btn-group btn-group-justified">
				<div class="btn-group">
					<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><?php echo $rank_name[$rank_id] ?>  <span class="caret"></span></button>
					<ul class="dropdown-menu" role="menu">
						<li><a href="<?php echo $rank0?>" <?php if ($rank_id == 0) echo 'class="active"'?>><?php echo _('Latest'); ?></a></li>
						<li><a href="<?php echo $rank1?>" <?php if ($rank_id == 1) echo 'class="active"'?>><?php echo _('Hot'); ?></a></li>
						<li><a href="<?php echo $rank2?>" <?php if ($rank_id == 2) echo 'class="active"'?>><?php echo _('Free'); ?></a></li>
						<li><a href="<?php echo $rank3?>" <?php if ($rank_id == 3) echo 'class="active"'?>><?php echo _('Paid'); ?></a></li>
						<li><a href="<?php echo $rank4?>" <?php if ($rank_id == 4) echo 'class="active"'?>><?php echo _('Purchased'); ?></a></li>
					</ul>								
				</div>	
				<div class="btn btn-default" ><a href="<?php echo self::url('album', 'index') ?>" data-toggle="tooltip" data-placement="bottom"  data-original-title="<?php echo _('Explore'); ?>"><i class="demo-icon icon-icon_album-01"></i></a></div>
				<div class="btn active"><a href="javascript:void(0)" data-toggle="tooltip" data-placement="bottom"  data-original-title="<?php echo _('Create'); ?>"><i class="demo-icon icon-icon_start-01"></i></a></div>	
				<div class="btn btn-default"><a href="<?php echo self::url('creative', 'index') ?>" data-toggle="tooltip" data-placement="bottom"  data-original-title="職人專區"><i class="demo-icon icon-icon_creator-01"></i></a></div>			
			</div>
		</div>
	</div>

	<div class="water_content " id="freewall">
		<?php 
			foreach($template as $k => $v0) {
				if($v0['type'] == 'ad') {
					echo '<div class="item_box">'.$v0['ad']['content'].'</div>';
				} else {
					echo '<div class="item_box" style="opacity:0;">
						<a href="'.$v0['template']['cover_url'].'"><img src="'.$v0['template']['image'].'" class="tem_bg" onerror="this.src=\''.static_file('images/origin.jpg').'\'" height="330" width="220"></a>
						<div class="item_info">
							<div class="info_name">
								<div class="info_icon">
									'.$v0['template']['record'].'
									'.$v0['template']['event_templatejoin'].'
								</div>
								<h3> <a href="'.$v0['template']['name_url'].'">'.$v0['template']['name'].'</a></h3>
								<div class="name_more">
									<p>'.$v0['template']['description'].'</p>
								</div>
							</div>
							<a href="'.$v0['user']['url'].'">
								<div class="info_user">
									<div class="user_face"><img src="'.$v0['user']['picture'].'" onerror="this.src=\''.static_file('images/face_sample.svg').'\'" height="101" width="101"></div>
									<div class="user_name">
										<p class="name_id">'.$v0['user']['name'].'</p>
										<p><i class="fa fa-eye"></i>'.$v0['template']['viewed'].'</p>
									</div>
								</div>
							</a>
						</div>
					</div>';
				}	
			}
			if (!empty($more)) echo '<div style="display:none;" class="more"><a href="'.$more.'"></a></div>'
		?>		
	</div>
	<?php
		$end_style = null;
		if (!empty($more)) {
			echo '<div class="end image"><p class="image"><img src="'.static_file('images/8.gif').'" ></p></div>';
			$end_style = 'style="display:none;"';
		}
	?>
	<div <?php echo $end_style; ?> class="end"><p>End</p></div>
</div>
<script>
deeplink.setup({
	iOS: {
		appName: "pinpinbox",
		appId: "<?php echo Core::settings('IOS_APP_ID'); ?>",
	},
	android: {
		appId: "<?php echo Core::settings('ANDROID_APP_URL'); ?>"
	}
});

function name_more_slice(obj) {var divH = $(obj).height(),$p = $("p", $(obj)).eq(0),str = $p.text();if ($p.outerHeight() > divH) {$p.text( str.slice(0, 70)+'...' );};}

function clickHandler(uri) { deeplink.open(uri); return false;}

$(function() {
	var $container = $('.water_content');
	$container.imagesLoaded(function(){
		$container.masonry({
			itemSelector: '.item_box',
			columnWidth: '.item_box',	
			gutter: 15,
		});
		$('div.item_box').animate({ opacity: 1 });
	});
	
	$container.infinitescroll({
		navSelector  : '.more',
		nextSelector : '.more a',
		itemSelector : '.item_box',
		pathParse: function (path, nextPage) {
			var customPath = path + "&page=";
			path = [customPath, ''];
			return path;
		},
		//If no more content, response here
		errorCallback: function() {$('div.end').css('display', 'block')},
	},function( newElements ) {
		var $newElems = $( newElements ).css({ opacity: 0 });
		$newElems.imagesLoaded(function(){
			$newElems.animate({ opacity: 1 });
			$container.masonry( 'appended', $newElems, true );
		});		
		$(".name_more").each(function(i) {name_more_slice($(this));});
	});	
	
	$('#album_category ul li ul').hide();
	$('#album_category > ul > li > a').click(function(){
		$(this).next().slideToggle('normal');
	});	
		
	var trip = new Trip([
	{ sel : $(".start_temp"), content : "Tips：點擊這裡快速上傳照片來建立相本!", position : "w", animation: 'bounceIn' },], {
		showNavigation : true,
		showCloseBox : true,
		delay : -1,
		prevLabel: '<?php echo _('Previous'); ?>',
		nextLabel: '<?php echo _('Next'); ?>',
		finishLabel: '關閉',  
	});
	<?php if(!$trip) echo 'trip.start();'; ?>
	
	//控制溢出文字加"..."
	$(".name_more").each(function(i) {name_more_slice($(this));});
	
});
</script>