<?php echo $form ?>
<script>
    $(function () {
        $('#form').validate({
            rules: {
                repassword: {
                    equalTo: '#password'
                },
                name: 'required'
            },
            submitHandler: function () {
                $.post('<?php echo $action?>', {
                    oldpassword: $('#oldpassword').val(),
                    name: $('#name').val(),
                    password: $('#password').val()
                }, function (r) {
                    r = $.parseJSON(r);
                    switch (r.result) {
                        case 0:
                            formerror(r.message);
                            break;
                        case 1:
                            formsuccess(r.message);
                            break;
                        case 2:
                            formnotice(r);
                            break;
                    }
                });
            }
        });


    });
</script>