<style type="text/css">
.owl-carousel .owl-wrapper-outer{
	box-shadow: 0px 0px 0px #d2d2d2, 0px 0px 0px #d2d2d2;
}
</style>
<!-- 內容頁開始 -->
<div id="rescuit_ad" style="color:#108199;font-size:2.3em;"><?php echo _('pinpinbox - Cooperation') ?></div>
<div id="rescuit_content">
	<div id="rescuit_in">
		<ul>
			<li><h2><?php echo _('多功能行銷工具');?></h2></li>
			<li>
				<div class="featureA">
					<div class="item"> 
						<img class="mobilehide02" src="<?php echo static_file('images/assets-v5/feature-01.svg') ?>"> 
						<img class="mobiledisplay02" src="<?php echo static_file('images/assets-v5/feature-1.svg') ?>"> 
					</div>
					<div class="item"> 
						<img class="mobilehide02" src="<?php echo static_file('images/assets-v5/feature-02.svg') ?>"> 
						<img class="mobiledisplay02" src="<?php echo static_file('images/assets-v5/feature-2.svg') ?>"> 
					</div>
					<div class="item"> 
						<img class="mobilehide02" src="<?php echo static_file('images/assets-v5/feature-03.svg') ?>"> 
						<img class="mobiledisplay02" src="<?php echo static_file('images/assets-v5/feature-3.svg') ?>"> 
					</div>
					<div class="item"> 
						<img class="mobilehide02" src="<?php echo static_file('images/assets-v5/feature-04.svg') ?>"> 
						<img class="mobiledisplay02" src="<?php echo static_file('images/assets-v5/feature-4.svg') ?>"> 
					</div>
					<div class="item"> 
						<img class="mobilehide02" src="<?php echo static_file('images/assets-v5/feature-05.svg') ?>"> 
						<img class="mobiledisplay02" src="<?php echo static_file('images/assets-v5/feature-5.svg') ?>"> 
					</div>
					<div class="item"> 
						<img class="mobilehide02" src="<?php echo static_file('images/assets-v5/feature-06.svg') ?>"> 
						<img class="mobiledisplay02" src="<?php echo static_file('images/assets-v5/feature-6.svg') ?>"> 
					</div>
				</div>
			</li>
			<li><div class="line"></div></li>
			<li><h2><?php echo _('跟我們合作的好處');?></h2></li>
			<li>
				<div class="featureB">
					<div class="item"> 
						<p><img src="<?php echo static_file('images/assets-v5/recruit_1.svg') ?>"></p>
						<p class="itemTitle"><?php echo _('虛實整合行銷')?></p>
						<p class="text"><?php echo _('透過條碼掃瞄、兌換券、抽獎券等機制，簡單串連線上和線下的活動。');?></p>
					</div>
					<div class="item"> 
						<p><img src="<?php echo static_file('images/assets-v5/recruit_3.svg') ?>"></p>
						<p class="itemTitle"><?php echo _('多媒體型錄');?></p>
						<p class="text"><?php echo _('集合圖像、影音、PDF、URL、地圖導航、錄音等，清楚傳遞商品和活動資訊。');?></p>
					</div>	
					<div class="item"> 
						<p><img src="<?php echo static_file('images/assets-v5/recruit_2.svg') ?>"></p>
						<p class="itemTitle"><?php echo _('免安裝主動推播');?></p>
						<p class="text"><?php echo _('您所發布、更新的內容能100%主動推播給追蹤者，輕易維繫顧客緊密度。');?></p>
					</div>
				</div>
			</li>
			<li><div class="line"></div></li>
			<li><h2><?php echo _('合作夥伴');?></h2></li>
			<li>
				<div class="featureC cooperationFotorama mobilehide02">
					<div class="item"> 
						<img src="<?php echo static_file('images/assets-v5/cooperation-1.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-2.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-3.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-4.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-5.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-6.png') ?>">
					</div>
					<div class="item"> 
						<img src="<?php echo static_file('images/assets-v5/cooperation-7.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-8.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-9.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-10.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-11.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-12.png') ?>">
					</div>
				</div>

				<div class="featureC m_cooperationFotorama mobiledisplay02">
					<div class="item"> 
						<img src="<?php echo static_file('images/assets-v5/cooperation-1.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-2.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-3.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-4.png') ?>">
					</div>
					<div class="item">						
						<img src="<?php echo static_file('images/assets-v5/cooperation-5.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-6.png') ?>">					
						<img src="<?php echo static_file('images/assets-v5/cooperation-7.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-8.png') ?>">
					</div>
					<div class="item">
						<img src="<?php echo static_file('images/assets-v5/cooperation-9.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-10.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-11.png') ?>">
						<img src="<?php echo static_file('images/assets-v5/cooperation-12.png') ?>">
					</div>
				</div>
			</li>
			<li><div class="line"></div></li>
			<li><h2><?php echo _('活動舉辦經驗');?></h2></li>
			<li>
				<div class="featureD">
					<div class="list">
						<?php 
							foreach ($event as $k0 => $v0) {
								echo '<div class="item"> 
									<p><img style="height:205px;width:100%;" src="'.URL_UPLOAD.$v0['image'].'"></p>
									<p class="text"><a href="'.self::url('event', 'content', ['event_id'=>$v0['event_id']]).'">'.$v0['name'].'</a></p>
								</div>';
							}
						?>
					</div>
				</div>
			</li>
			<li><div class="line"></div></li>
			<li><h2><?php echo _('廠商聯絡表單') ?></h2></li>
			<li>
				<form class="form-horizontal" id="js_recruit_form">
					<div class="control-group col-sm-6">
						<label class="control-label"><?php echo _('Name of the Company') ?></label>
						<div class="controls">
							<input type="text" name="recruit_name">
						</div>
					</div>
					<div class="control-group col-sm-6">
						<label class="control-label"><?php echo _('連絡電話') ?></label>
						<div class="controls">
							<input type="text" name="recruit_telephone">
						</div>
					</div>
					<div class="control-group col-sm-6">
						<label class="control-label"><?php echo _('Contact Name') ?></label>
						<div class="controls">
							<input type="text" name="recruit_contact_name" >
						</div>
					</div>
					<div class="control-group col-sm-6">
						<label class="control-label"><?php echo _('電子信箱') ?></label>
						<div class="controls">
							<input type="text" name="recruit_email">
						</div>
					</div>
			</li>
			<li><h2 style="display:none;"><?php echo _('Cooperation intentions') ?></h2></li>
			<li><div class="line"></div></li>
			<li>	
					<div class="form-horizontal">
						<div class="control-group">
							<label class="control-label" for="inputEmail"><?php echo _('Cooperation intentions') ?></label>
							<div class="controls">
								<select id="recruitintent_id" name="recruit_recruitintent_id">
									<?php 
										foreach($recruitintent as $k => $v){
											echo '<option value='.$v['recruitintent_id'].'>'.$v['name'].'</option>';
										}
									?>
								</select>
							</div>
						</div>
						<div class="control-group" >
							<label class="control-label" for="inputEmail"><?php echo _('Introduction to the proposal') ?></label>
							<div class="TextAreacontrols">
								<textarea name="recruit_proposal" rows="8"></textarea>
							</div>
						</div>	
						<input type="submit" style="display:none;" id="js_recruit_edit">
					</div>
				</form>
			</li>
			<li class="textcenter">
				<div style="width:50%; margin:0 auto;" id="slider"></div><p><?php echo _('Slide the lever to verify.') ?></p>
				<label class="checkbox">
					<?php echo _('submit means that you have read and accept the ').'<a target="_blank" href="'.self::url('index', 'terms').'">'._('specifications').'</a>'._(' and ').'<a target="_blank" href="'.self::url('index', 'privacy').'">'._('Privacy statement').'</a>';?>
				</label>
			</li>
		</ul>
	</div>
</div>

<div class="button">
	<a href="javascript:void(0)"  class="recruit_enter" onclick="$('#js_recruit_edit').trigger('click')"><?php echo _('Submit') ?></a>
	<img style="width:20px;height:20px;" class="loading_img" src="<?php echo static_file('images/loading.gif')?>">
</div>

<script type="text/javascript">

$(document).ready(function(){
	var owl = ($(window).width() > 1024 ) ? $('.cooperationFotorama') : $('.m_cooperationFotorama') ;

	owl.owlCarousel({
		width:'100%',
		ratio : '960/350',
		autoPlay: 5000,
		lazyLoad: true,
		paginationSpeed: 1200,
		singleItem: true,
		stopOnHover: true,
	});


	$('#slider').slider({
		animate: true,
		max: <?php echo $max?>,
		stop: function(event, ui) {
			if (ui.value == <?php echo $max?>) {
				$(this).slider('disable').next('p').css({'color': 'green'}).text('<?php echo _('Authentication passed') ?>');
			} else {
				$(this).find('a').animate({'left': 0});
			}
		}
	});


	$('#js_recruit_form').validate({	
		rules: {},
		submitHandler: function() {
			$('.recruit_enter').hide().next('img').show();

			if ($('#slider').slider('value') != <?php echo $max?>) {
				var siteModal=new jBox('Modal', {
					onCloseComplete:function(){
						$('.recruit_enter').show().next('img').hide();
					},
				});
				siteModal.setContent("<img src=\"<?php echo static_file('images/error.png'); ?>\">&nbsp;<?php echo _('Slide the lever to verify.'); ?>").open();			
				return;
			}
			
			$.post('<?php echo self::url('recruit', 'index') ;?>', {
				recruit_name: $('input[name="recruit_name"]').val(),
				recruit_telephone: $('input[name="recruit_telephone"]').val(),
				recruit_email: $('input[name="recruit_email"]').val(),
				recruit_contact_name: $('input[name="recruit_contact_name"]').val(),
				recruit_recruitintent_id: $('#recruitintent_id :selected').val(),
				recruit_proposal: $('[name="recruit_proposal"]').val(),
				captcha: $('#slider').slider('value'),
			}, function(r) {
				r = $.parseJSON(r);
				if (r.result == 1) {
					site_jBox(r,'success');	
					$('.recruit_enter').show().next('img').hide();
				} else {
					site_jBox(r,'error');					
					$('.recruit_enter').show().next('img').hide();
				}				
			});
		}
	});
	$('.loading_img').hide();
});
</script>