<?php echo $form?>
<script>
$(function(){
	$('#form').validate({
		rules: {},
		submitHandler: function(){
			$.post('<?php echo $action?>', {
				<?php if ('edit' == $_GET['act']) {?>
				<?php echo M_CLASS?>_id: $('#<?php echo M_CLASS?>_id').val(),
				<?php }?>
				name: $('#name').val(),
				platform: $('#platform').val(),
				task_for: $('#task_for').val(),
				event_id: $('#event_id').val(),
				reward: $('#reward').val(),
				reward_value: $('#reward_value').val(),
				restriction: $('#restriction').val(),
				restriction_value: $('#restriction_value').val(),
				condition: $('#condition').val(),
				condition_value: $('#condition_value').val(),
				whitelist: $('#whitelist').val(),
				blacklist: $('#blacklist').val(),
				feedback_message_success: $('#feedback_message_success').val(),
				feedback_message_fail: $('#feedback_message_fail').val(),
				upperlimit: $('#upperlimit').val(),
				description: $('#description').val(),
				starttime: $('#starttime').val(),
				endtime: $('#endtime').val(),
				act: $('input[name="act"]:checked').val()
			}, function(r) {
				r = $.parseJSON(r);
				switch (r.result) {
					case 0:formerror(r.message);break;
					case 1:formconfirm(r);break;
				}
			});
		}
	});

	<?php if ('edit' == $_GET['act']) {?>
	//eventjoin
    $('#taskqueue-grid').kendoGrid({
    	columns: [
			{
				title: 'Task : <?php echo $task_name; ?> - 已發放 : <?php echo $report; ?> ',
				columns: [
					{field: 'user_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
					{title: '@info', field: 'albumX', attributes: {'class': 'string'}, encoded: false, filterable: false, sortable: false},
					{field: 'type', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
					{field: 'type_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
					{title: '@info', field: 'albumX2', attributes: {'class': 'string'}, encoded: false, filterable: false, sortable: false},
				]
			},
			{field: 'reward_value', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{field: 'inserttime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
		],
		dataBinding: function(e) {},
		dataBound: function(e) {},
        dataSource: new kendo.data.DataSource({
        	filter: {field: '<?php echo M_CLASS?>_id', operator: 'eq', value: <?php echo $task_id ?>},
    		page: 1,
    		pageSize: gridpageSize,
    		schema: {
    			data: function(r){return r.data;},
    			total: function(r){return r.total;}
    		},
    		serverPaging: true,
    		serverSorting: true,
    		serverFiltering: true,
    		sort: {field: 'inserttime', dir: 'desc'},
    		transport: {
    			read: {
    				data: {'case': 'taskqueue'},
    				dataType: 'json', //"jsonp" is required for cross-domain requests; use "json" for same-domain requests
    				type: 'POST',
    				url: '<?php echo self::url(M_CLASS, 'json')?>',
    			}
    		},
    	}),
        filterable: true,
        pageable: {
            refresh: true,
            input: true,
            pageSize: gridpageSize,
            pageSizes: gridpageSizes,
        },
        reorderable: true,
        resizable: true,
        selectable: true,
        sortable: true,
		toolbar: [
		  	'excel',
		],
    });
    <?php }?>
});
</script>