<div id="analysis">
	<?php include 'nav.phtml'?>
	<div class="content">
		<table class="table">
			<tr class="row">
				<td class="cell cell-8">
					<div class="panel">
						<div class="panel-title">Pageview<span class="k-icon k-i-arrowhead-n"></span></div>
						<div class="panel-content"><div id="userpageview-chart" style="width: 100%; height: 300px; margin: 0 auto"></div></div>
					</div>
				</td>
				<td class="cell cell-4 list">
					<ul>
						<li class="list-key">平均(日) - Pageview：</li><li class="list-value"><?php echo number_format($pageview_average)?></li>
						<li class="list-key">平均(日) - User：</li><li class="list-value"><?php echo number_format($user_average)?></li>
						<li class="list-key">單日最高日期／數量 - Pageview：</li><li class="list-value"><?php echo $pageview_highest[0].'／'.number_format($pageview_highest[1])?></li>
						<li class="list-key">單日最高日期／數量 - User：</li><li class="list-value"><?php echo $user_highest[0].'／'.number_format($user_highest[1])?></li>
					</ul>
				</td>
			</tr>
		</table>
		<table class="table">
			<tr class="row">
				<td class="cell cell-8">
					<div class="panel">
						<div class="panel-title">Age<span class="k-icon k-i-arrowhead-n"></span></div>
						<div class="panel-content"><div id="userage-chart" style="width: 100%; height: 300px; margin: 0 auto"></div></div>
					</div>
				</td>
				<td class="cell cell-4 list">
					<ul>
						<li class="list-key">平均（Unknown 不計入） - Age：</li><li class="list-value"><?php echo $age_average?></li>
						<li class="list-key">最低／最高 - Age：</li><li class="list-value"><?php echo $age_lowest.'／'.$age_highest?></li>
					</ul>
				</td>
			</tr>
		</table>
		<table class="table">
			<tr class="row">
				<td class="cell cell-3">
					<div class="panel">
						<div class="panel-title">Gender<span class="k-icon k-i-arrowhead-n"></span></div>
						<div class="panel-content"><div id="usergender-chart" style="width: 100%; height: 300px; margin: 0 auto"></div></div>
					</div>
				</td>
				<td class="cell cell-3">
					<div class="panel">
						<div class="panel-title">Relationship<span class="k-icon k-i-arrowhead-n"></span></div>
						<div class="panel-content"><div id="userrelationship-chart" style="width: 100%; height: 300px; margin: 0 auto"></div></div>
					</div>
				</td>
				<td class="cell cell-6">
				</td>
			</tr>
		</table>
	</div>
</div>
<script>
$(function(){
	//userpageview
	$('#userpageview-chart').highcharts({
        chart: {
            zoomType: 'xy'
        },
        title: {text: null},
        tooltip: {shared: true},
        series: <?php echo $userpageview?>,
        xAxis: {type: 'datetime'},
        yAxis: {
        	allowDecimals: false,
        	stackLabels: {enabled: true},
            title: {text: null}
        },
    });
    
	//userage
	$('#userage-chart').highcharts({
        chart: {
            type: 'column',
            zoomType: 'xy'
        },
        title: {text: null},
        tooltip: {shared: true},
        plotOptions: {
        	column: {stacking: 'normal'}
        },
        series: <?php echo $userage_series?>,
        xAxis: {
            categories: <?php echo $userage_x?>
        },
        yAxis: {
            title: {text: null}
        },
    });
    
    //usergender
    $('#usergender-chart').highcharts({
        chart: {
            type: 'pie',
        },
        title: {text: null},
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '{point.name}: {point.percentage:.1f}%',
                }
            }
        },
        series: <?php echo $usergender?>
    });

    //userrelationship
    $('#userrelationship-chart').highcharts({
        chart: {
            type: 'pie',
        },
        title: {text: null},
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '{point.name}: {point.percentage:.1f}%',
                }
            }
        },
        series: <?php echo $userrelationship?>
    });
});
</script>