<div id="analysis">
	<?php include 'nav.phtml'?>
	<div class="content">
		<table class="table">
			<tr class="row">
				<td class="cell cell-8">
					<div class="panel">
						<div class="panel-title">Growth<span class="k-icon k-i-arrowhead-n"></span></div>
						<div class="panel-content"><div id="usergrowth-chart" style="width: 100%; height: 300px; margin: 0 auto"></div></div>
					</div>
				</td>
				<td class="cell cell-4 list">
					<ul>
						<li class="list-key">總數量：</li><li class="list-value"><?php echo number_format($totalamount)?></li>
						<li class="list-key">平均(日) - Registration：</li><li class="list-value"><?php echo number_format($registration_average)?></li>
						<li class="list-key">單日最高日期／數量：</li><li class="list-value"><?php echo $registration_highest[0].'／'.number_format($registration_highest[1])?></li>
					</ul>
				</td>
			</tr>
		</table>
		<table class="table">
			<tr class="row">
				<td class="cell cell-3">
					<div class="panel">
						<div class="panel-title">Way<span class="k-icon k-i-arrowhead-n"></span></div>
						<div class="panel-content"><div id="userway-chart" style="width: 100%; height: 300px; margin: 0 auto"></div></div>
					</div>
				</td>
				<td class="cell cell-9">
				</td>
			</tr>
		</table>
	</div>
</div>
<script>
$(function(){
	//usergrowth
	$('#usergrowth-chart').highcharts({
        chart: {
            zoomType: 'xy'
        },
        title: {text: null},
        tooltip: {shared: true},
        plotOptions: {
        	column: {stacking: 'normal'},
        },
        series: <?php echo $usergrowth?>,
        xAxis: {type: 'datetime'},
        yAxis: {
        	allowDecimals: false,
            title: {text: null}
        },
    });

	//userway-chart
	$('#userway-chart').highcharts({
        chart: {
            type: 'pie',
        },
        title: {text: null},
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '{point.name}: {point.percentage:.1f}%',
                }
            }
        },
        series: <?php echo $userway?>
    });
});
</script>