<?php echo $index?>
<script>
$(function(){
    $('#grid').kendoGrid({
    	columns: [
			{field: '<?php echo M_CLASS?>_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{field: 'script_id', attributes: {'class': 'string'}},
			{field: 'runtime', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{field: 'request', attributes: {'class': 'string'}, encoded: false, filterable: false, sortable: false},
			{field: 'return', attributes: {'class': 'string'}, encoded: false, filterable: false, sortable: false},
			{field: 'state', attributes: {'class': 'enums state-#:state#'}},
			{field: 'modifytime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
		],
		dataBinding: function(e) {},
		dataBound: function(e) {},
        dataSource: new kendo.data.DataSource({
    		page: 1,
    		pageSize: gridpageSize,
    		serverPaging: true,
    		serverSorting: true,
    		serverFiltering: true,
    		transport: {
    			read: {
    				dataType: 'json', //"jsonp" is required for cross-domain requests; use "json" for same-domain requests
    				type: 'POST',
    				url: '<?php echo self::url(M_CLASS, 'json')?>',
    			}
    		},
    		schema: {
    			data: function(r){return r.data;},
    			total: function(r){return r.total;}
    		},
    		sort: {field: 'modifytime', dir: 'desc'}
    	}),
        filterable: true,
        height: gridheight,
        pageable: {
            refresh: true,
            input: true,
            pageSize: gridpageSize,
            pageSizes: gridpageSizes,
        },
        reorderable: true,
        resizable: true,
        selectable: true,
        sortable: true,
		toolbar: [
		  	'excel',
		],
    });
});
</script>