<?php echo $form?>
<script>
$(function() {
	$('#form').validate({
		rules: {},
		submitHandler: function() {
			$.post('<?php echo $action?>', {
				categoryarea_id: $('#categoryarea_id').val(),
				category_id: $('#category_id').val(),
				act: $('input[name="act"]:checked').val(),
				sequence: $('#sequence').val(),
			}, function(r) {
				r = $.parseJSON(r);
				switch (r.result) {
					case 0:formerror(r.message);break;
					case 1:formconfirm(r);break;
				}
			});
		}
	});
});
</script>