<?php echo $index?>
<script>
$(function(){
	var dataSource = new kendo.data.DataSource({
		batch: true,
		page: 1,
		pageSize: gridpageSize,
		serverPaging: true,
		serverSorting: true,
		serverFiltering: true,
		transport: {
			read: {
				dataType: 'json',//"jsonp" is required for cross-domain requests; use "json" for same-domain requests
				type: 'POST',
				url: '<?php echo self::url(M_CLASS, 'json')?>',
			},
			update: {
				beforeSend: function() {},
				complete: function(xhr) {
					r = $.parseJSON(xhr.responseText);
					switch(r.result) {
						case 0:griderror(r.message);break;
						case 1:gridsuccess(r.message);break;
					}
				},
				dataType: 'json',
				type: 'POST',
				url: '<?php echo self::url(M_CLASS, 'grid_edit')?>',
			},
		},
		schema: {
			data: function(r){return r.data;},
			total: function(r){return r.total;},
			model: {
				id: 'categoryarea_id',
                fields: {
                	categoryarea_id: {editable: false},
                	categoryareaX: {editable: false},
                	category_id: {editable: false},
                	categoryX: {editable: false},
                	act: {editable: false},
                	sequence: {type: 'number', validation: {required: true, min: 0, max: 255}},
                	modifytime: {editable: false},
                	modifyadmin_id: {editable: false},
                }
            }
		},
		sort: {field: 'modifytime', dir: 'desc'}
	});
    $('#grid').kendoGrid({
    	columns: [
			{
				title: 'categoryarea',
				columns: [
					{field: 'categoryarea_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
					{title: '@info', field: 'categoryareaX', attributes: {'class': 'string'}, encoded: false, filterable: false, sortable: false}
				]
			},
			{
				title: 'category',
				columns: [
					{field: 'category_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
					{title: '@info', field: 'categoryX', attributes: {'class': 'string'}, encoded: false, filterable: false, sortable: false}
				]
			},
			{field: 'act', attributes: {'class': 'enums act-#:act#'}},
			{field: 'sequence', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{field: 'modifytime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
			{field: 'modifyadmin_id', attributes: {'class': 'string'}},
		],
		dataBinding: function(e) {},
		dataBound: function(e) {},
        dataSource: dataSource,
		editable: {
			confirmation: false,
			mode: 'incell'
		},
        filterable: true,
        height: gridheight,
        pageable: {
            refresh: true,
            input: true,
            pageSize: gridpageSize,
            pageSizes: gridpageSizes,
        },
        reorderable: true,
        resizable: true,
        selectable: true,
        sortable: true,
		toolbar: [
		  	{template: '<a class="k-button" onclick="grid_toolbar_add(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'form', array('act'=>'add'))?>\')"><span class="k-icon k-i-plus"></span></a><a class="k-button" onclick="grid_toolbar_edit(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'form', array('act'=>'edit'))?>\', [\'categoryarea_id\',\'category_id\'])"><span class="k-icon k-i-pencil"></span></a><a class="k-button" onclick="grid_toolbar_delete(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'delete')?>\', [\'categoryarea_id\',\'category_id\'])"><span class="k-icon k-i-close"></span></a>'},
		  	'save',
		  	'cancel',
		],
    });
});
</script>