<?php echo $form?>
<script>
$(function() {
	$('#form').validate({
		rules: {},
		submitHandler: function() {
			$.post('<?php echo $action?>', {
				user_id: $('#user_id').val(),
			}, function(r) {
				r = $.parseJSON(r);
				switch (r.result) {
					case 0:formerror(r.message);break;
					case 1:formconfirm(r);break;
				}
			});
		}
	});

	$('#user_id').on('keyup change', function() {
		$.post('<?php echo self::url(M_CLASS, 'extra0')?>', {
			user_id: $(this).val(),
		}, function(r) {
			r = $.parseJSON(r);
			if (r.result) {
				$('img[data-info="avatar"]').prop('src', r.data.avatar);
				$('span[data-info="account"]').text(r.data.account);
				$('span[data-info="name"]').text(r.data.name);
			}
		});
	});
});
</script>