<?php echo $index?>
<script>
$(function() {
    $('#grid').kendoGrid({
    	columns: [
    		{
    			title: 'user',
    			columns: [
    				{field: 'user_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
    				{title: '@info', field: 'userX', attributes: {'class': 'string'}, encoded: false, filterable: false, sortable: false}
    			]
    		},
			{field: 'inserttime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
		],
		dataBinding: function(e) {},
		dataBound: function(e) {},
        dataSource: new kendo.data.DataSource({
        	batch: true,
    		page: 1,
    		pageSize: gridpageSize,
    		serverPaging: true,
    		serverSorting: true,
    		serverFiltering: true,
    		transport: {
    			read: {
    				dataType: 'json', //"jsonp" is required for cross-domain requests; use "json" for same-domain requests
    				type: 'POST',
    				url: '<?php echo self::url(M_CLASS, 'json')?>',
    			},
    			update: {
    				beforeSend: function() {},
    				complete: function(xhr) {
    					r = $.parseJSON(xhr.responseText);
    					switch(r.result) {
    						case 0:griderror(r.message);break;
    						case 1:gridsuccess(r.message);break;
    					}
    				},
    				dataType: 'json',
    				type: 'POST',
    				url: '<?php echo self::url(M_CLASS, 'grid_edit')?>',
    			},
    		},
    		schema: {
    			data: function(r) {return r.data;},
    			total: function(r) {return r.total;},
    			model: {
    				id: 'user_id',
                    fields: {
                    	user_id: {editable: false},
                    	userX: {editable: false},
                    	inserttime: {editable: false},
                    }
                }
    		},
    		sort: {field: 'inserttime', dir: 'desc'}
    	}),
		editable: {
			confirmation: false,
			mode: 'incell'
		},
        filterable: true,
        height: gridheight,
        pageable: {
            refresh: true,
            input: true,
            pageSize: gridpageSize,
            pageSizes: gridpageSizes,
        },
        reorderable: true,
        resizable: true,
        selectable: true,
        sortable: true,
		toolbar: [
		  	{template: '<a class="k-button" onclick="grid_toolbar_add(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'form', array('act'=>'add'))?>\')"><span class="k-icon k-i-plus"></span></a><a class="k-button" onclick="grid_toolbar_delete(\'\\#grid\', \'<?php echo self::url(M_CLASS, 'delete')?>\', [\'user_id\'])"><span class="k-icon k-i-close"></span></a>'},
		],
    });
});
</script>