<div id="header">
	<!-- 電腦版使用導覽列 -->
	<div id="head_desk">
		<div class="head_top">
			<div class="head_center">
				<div class="logo"><a href="<?php echo URL_ROOT ?>"><?php echo _('pinpinbox'); ?></a></div>
				<div class="top_search" <?php if(!$headbar_user) echo 'style="width:550px;"' ?> >
					<div class="input-group">
						<div class="input-group-btn">
							<button type="button" id="header_searchtype_list" name="header_searchtype_list" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false" data-searchtype="<?php echo ($headbar_searchtype == null) ? 'album' : $headbar_searchtype ; ?>"><?php echo _('Album'); ?> <span class="caret"></span></button>
							<ul class="dropdown-menu dropdown-menu-headerbar" role="menu">
							  <li><a href="javascript:void(0)" data-searchtype="album"><?php echo _('Album'); ?></a></li>							  
							  <li><a href="javascript:void(0)" data-searchtype="user"><?php echo _('Author'); ?></a></li>
							</ul>								
						</div>
						<!-- header PC search-->
						<input type="text" class="form-control height30" id="searchkey_pc" name="searchkey" value="<?php echo $headbar_searchkey; ?>">
						<div class="input-group-btn">
							<button class="btn btn-default" type="button" onclick="_search()">
								<i class="fa fa-search"></i>
							</button>
						</div>
					</div>							
				</div>
				<div id="head_other">
					<ul>
						<li class="member_hide">
							<?php echo (!empty($import_icon_show)) ? $import_icon_show : null; ?>
							<a style="z-index: 99;" href="javascript:void(0);" class="member cicle_btn icon_user" data-iconfor="user" id="member_open">
								<img src="<?php echo $headbar_user? $headbar_user['picture'] : static_file('images/login.png')?>" height="149" width="149"  onerror="this.src='<?php echo static_file('images/face_sample.svg')?>'">
							</a>
							<ul>
								<li><div class="member_nav">
									<ul>
									<?php
									if ($headbar_user) {
										echo '
										<li style="color:#D0D0D0;">'.$headbar_user['name'].'</li>
										<li><div class=line></div></li>
										<li><a href="'.self::url('user', 'settings').'">'._('Member Center').'</a></li>										
										<li><a href="'.Core::get_creative_url($headbar_user['user_id']).'">'._('My Zone').'</a></li>
										<li><div class=line></div></li>
										<li><a href="'.self::url('user', 'order').'">'._('Fees').'</a></li>
										<!-- <li><a href="'.self::url('user', 'album').'">'._('My Album').'</a></li>-->
										<li><div class=line></div></li>
										<li><a href="'.self::url('user', 'question').'">'._('Feedback').'</a></li>
										<li><a href="'.self::url('user', 'logout').'">'._('Log out').'</a></li>';
									} else {
										echo '
										<li>Hi ~ '._('Guest').'</li>
										<li><div class=line></div></li>
										<li><a href="'.self::url('user', 'login', $login_redirect).'">'._('Log in').'</a></li>
										<li><a href="'.self::url('user', 'register').'">'._('Register').'</a></li>';
									}
									?>
									</ul>
								</div></li>
							</ul>
						</li>											
						<?php if($headbar_user) { ?>
							<li class="notice_hide">
								<a href="javascript:void(0)" class="cicle_btn" data-toggle="tooltip" data-placement="bottom" >
                                    <?php echo $pushqueue_viewed_icon ?>
									<img src="<?php echo static_file('images/assets-v5/notice_a.svg'); ?>" onerror="this.onerror=null; this.src='<?php echo static_file('images/assets-v5/notice_a.png') ;?>'" >
								</a>
								<ul>
									<li>
										<div class="notice_nav">
											<ul>
												<li style="font-size:14px;"><?php echo _('通知中心')?></li>
												<li><div class="notice_line"></div></li>
												<div class="noticeWarpper">
												</div>
												<li class="bottom">
													<a style="color:white;font-size:14px;" href="<?php echo self::url('notifications') ?>"> <?php echo _('顯示全部') ?> </a>
												</li>
											</ul>
										</div>
									</li>
								</ul>
							</li>
						<?php } ?>
						<li>
							<a href="<?php echo self::url('event', 'index') ?>" class="cicle_btn icon_event" data-iconfor="event" data-toggle="tooltip" data-placement="bottom"  data-original-title="<?php echo _('Activities') ?>">
								<img src="<?php echo static_file('images/assets-v5/event_a.svg') ;?>" onerror="this.onerror=null; this.src='<?php echo static_file('images/assets-v5/event_a.png') ;?>'" >
							</a>
						</li>
						<li>
							<a href="javascript:void(0)" onclick="createAlbum();" class="cicle_btn icon_diy" data-iconfor="diy" data-toggle="tooltip" data-placement="bottom"  data-original-title="<?php echo _('Create'); ?>">
								<img src="<?php echo static_file('images/assets-v5/diy_b.svg'); ?>" onerror="this.onerror=null; this.src='<?php echo static_file('images/assets-v5/diy_b.png') ;?>'" >
							</a>
						</li>
						<?php 
						if (!empty(self::user_get()) && false ) {
							echo '
							<li>
								<a href="'.self::url('follow').'" class="follow_btn" title="'._('Search album').'">
									<img src="'.static_file('images/head_follow.jpg').'" height="20" width="14" class="follow_icon">
								</a>
							</li>';
						}
						?>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<!-- 手機板使用導覽列 -->
	<div id="head_mobile">
		<div id="head_nav02">
			<div id="close_nav02"><a href="javascript:void(0);"><img src="<?php echo static_file('images/close.png')?>" height="83" width="82"  ></a></div>
			<ul>
				<?php
				if ($headbar_user) {
					echo '<li><div id="login_no"><a href="javascript:void(0)"><img src="'.$headbar_user['picture'].'" height="149" width="149"   onerror="this.src=\''.static_file('images/face_sample.svg').'\'">'.$headbar_user['name'].'</a></div></li>';
				} else {
					echo '<li><div id="login_ok"><a href="'.self::url('user', 'login').'"><img src="'.static_file('images/login.png').'" height="40" width="40"  >'._('Log in').'</a></div></li>';
				}
				?>
				<li><div class="line"></div></li>
				<li>
					<div id="nav_wrapper">
						<div id="scroller">
							<ul>
								<?php
								if ($headbar_user) {
									$_password = ($headbar_user['way'] == 'facebook') ? null : '<li><a href="'.self::url('user', 'password').'">'._('Password changed').'</a></li>';

									echo '<li><a href="'.Core::get_creative_url($headbar_user['user_id']).'">'._('My Zone').'</a></li>';
									if($headbar_user) echo'<li><a href="'.self::url('notifications').'">'._('通知中心').'</a></li>';
									echo '<li><a href="'.self::url('user', 'sale_album').'" >'._('Sponsor Management').'</a></li>';

									echo'
									<li>
										<a href="javascript:void(0);" class="drop">'._('Member Center').'
											<ul>
												<li><a href="'.self::url('user', 'settings').'">'._('Member Information').'</a></li>
												'.$_password.'
												<!-- <li><a href="'.self::url('user', 'album').'">'._('My Album').'</a></li> -->
												<li><a href="'.self::url('user', 'order').'">'._('Fees').'</a></li>
											</ul>
										</a>
									</li>
									
									<li><a href="'.self::url('user', 'point').'">'._('Buy P Points').'</a></li>

									<li><a href="'.self::url('user', 'question').'">'._('Feedback').'</a></li>
									<li><div class="line"></div></li>

									<li><a href="'.self::url('about').'">'._('關於我們').'</a></li>
									<li><a href="'.self::url('album', 'explore').'" >'._('Explore').'</a>
										<ul>';
									foreach ($headbar_rank as $v0) {
										//echo '<li><a href="'.$v0['url'].'">'.$v0['name'].'</a></li>';
									}
									echo '
										</ul>	
									</li>									
									<li><a href="'.self::url('event').'">'._('Activities').'</a></li>
									<li><a target="_blank" href="'.Core::settings('FACEBOOK_PAGE_URL').'">'._('Facebook粉絲專頁').'</a></li>
									<li><div class="line"></div></li>
									<li><a href="'.self::url('user', 'logout').'">'._('Log out').'</a></li>';
								
								} else {
									echo '
									<li><a href="'.self::url('about').'">'._('關於我們').'</a></li>				
									<li><a href="'.self::url('album', 'explore').'">'._('Explore').'</a>
										<ul>';
									foreach ($headbar_rank as $v0) {
										// echo '<li><a href="'.$v0['url'].'">'.$v0['name'].'</a></li>';
									}
									echo '
										</ul>
									</li>
									<li><a href="'.self::url('event').'">'._('Activities').'</a></li>
									<li><a target="_blank" href="'.Core::settings('FACEBOOK_PAGE_URL').'">'._('Facebook粉絲專頁').'</a></li>
									<li><a href="'.self::url('user', 'register').'">'._('Register').'</a></li>';
								}
								?>
							</ul>
						</div>
					</div>
				</li>
			</ul>
		</div>
		<div id="head_all">
			<div id="head_in">
				<div class="logo mobilehide02"><a href="<?php echo URL_ROOT?>"><img src="<?php echo static_file('images/logo.png'); ?>" height="84" width="79"></a></div>
				<div class="logo mobilehidedispaly02"><a href="<?php echo URL_ROOT?>"><img src="<?php echo static_file('images/m_logo.png'); ?>" height="84" width="79"></a></div>
				<div class="top_search">
						<div class="input-group">
							<div class="input-group-btn">
								<button type="button" id="header_searchtype_list" name="header_searchtype_list" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false" data-searchtype="<?php echo ($headbar_searchtype == null) ? 'album' : $headbar_searchtype ; ?>"><?php echo _('Album'); ?> <span class="caret"></span></button>
								<ul class="dropdown-menu dropdown-menu-headerbar" role="menu">
								  <li><a href="javascript:void(0)" data-searchtype="album"><?php echo _('Album'); ?></a></li>
								  <li><a href="javascript:void(0)" data-searchtype="user"><?php echo _('Author'); ?></a></li>
								</ul>								
							</div>
							<!-- header Mobile search-->
							<input type="text" class="form-control" id="searchkey_m" name="searchkey" value="<?php echo $headbar_searchkey; ?>">
							
							<div class="input-group-btn"><button class="btn btn-default" type="button" onclick="_search()"><i class="fa fa-search"></i></button></div>
						</div>
				</div>					
				
				<div class="menu02">
					<a href="javascript:;" id="menu2_open"><img src="<?php echo static_file('images/menu02.png')?>" height="177" width="174"  ></a>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="right_btn">
	<?php if(M_CLASS != 'album' || (M_CLASS =='album' && M_FUNCTION !='content')) {?>
	<div id="scroll_top" <?php if(M_CLASS == 'user') echo 'style="bottom:65px;"' ?> ><a href="javascript:void(0)"><img src="<?php echo static_file('images/icon_top.svg'); ?>" height="53" width="52"  ></a></div>
	<?php }?>
	<div id="fb_link"><a href="<?php echo Core::settings('FACEBOOK_PAGE_URL'); ?>" target="_blank" title="造訪 pinpinbox粉絲團!"><img src="<?php echo static_file('images/icon_fb.svg') ?>" onerror="this.onerror=null; this.src='<?php echo static_file('images/icon_fb.png') ?>'"></a></div>
</div>
<script>

//Mobile - notice
function mobile_notice() {
	var myConfirm = new jBox('Modal', {
		cancelButton: '<?php echo _('No')?>',
		confirmButton: '<?php echo _('Yes')?>',
		confirm: function() {	
			buyalbum();
		},
		onCloseComplete: function() {	
			myConfirm.destroy();
		}
	}).setContent(
		'<div class="content">' +
		'<p class="keypoint"><img src="<?php echo static_file('images/info.png')?>">&nbsp;<?php echo _('Coming Soon!')._('Only a PC device is supported at present.') ;?></p>' +
		// '<p><a data-uri="<?php echo Core::settings('ANDROID_DATA_URI') ?>" onclick="clickHandler(this.dataset.uri)" href="javascript:void(0)"><img class="app" src="<?php echo static_file('images/jbox_and.png')?>"></a>'+
		// '<a data-uri="<?php echo Core::settings('IOS_DATA_URI') ?>" onclick="clickHandler(this.dataset.uri)" href="javascript:void(0)"><img class="app" src="<?php echo static_file('images/jbox_ios.png')?>"></a></p><br>' +
		'</div>'
	).open();
}
</script>