<!-- 內容頁開始 -->
<div id="banner" class="index_banner">
	<div id="banner_content">
		<div class="fotorama" style="width:960px;" >
			<?php 
				foreach($creative_group as $k0 => $v0) {
					echo '<div class="page">
						<div class="creator_box">
							<div class="color_box color0'.($k0+1).'"></div>
						</div>
						<div class="creator_list">';
							foreach($v0['sort'] as $k1 => $v1) {
								echo '<a href="'.$v1['url'].'">
									<div class="creator_item">
										<div class="face"><img src="'.$v1['picture'].'" height="101" width="101" onerror="this.onerror=null; this.src=\''.static_file('images/face_sample.svg').'\'"></div>
										<div class="name">'.$v1['name'].'</div>
									</div>
								</a>';
							}
						echo '</div>
						<div class="line color0'.($k0+1).'"></div>
					</div>';
				}
			?>
		</div>
	</div>
</div>
<div class="mobile_banner" style="height: auto;">
	<div>
		<a href="javascript:void(0)"><img src="<?php echo static_file('images/creator_banner.jpg'); ?>"></a>
	</div>
</div>
<br>
<div id="main_content">
	<div id="content" class="temp">
		<div class="row new_nav">
			<div class="col-md-7 tree_box" style="display: none;">
				<ol class="breadcrumb">
					<img src="<?php echo static_file('images/p_icon.png') ?>" height="19" width="19" alt="">
					<?php echo '<li><a href="'.self::url('creative', 'index').'">'._('Author’s').'</a></li>'; ?>
					<!-- Level 1 : style -->
					<li class="dropdown">
						<?php 
							echo '<a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span id="categoryarea_name">'._('所有職人').'</span> <span class="caret"></span></a>';
						?>
						<ul class="dropdown-menu" role="menu">
							<li><a href="javascript:void(0)"><?php echo _('所有職人'); ?></a></li>
						</ul>
					</li>
				</ol>
			</div>
			<div class="col-md-5"  style="display: none;">
				<div class="btn-group btn-group-justified">
					<div class="btn-group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><?php echo $rank_name[$rank_id] ?>  <span class="caret"></span></button>
						<ul class="dropdown-menu" role="menu">
							<li><a href="<?php echo $rank0?>" <?php if ($rank_id == 0) echo 'class="active"'?>><?php echo _('Latest'); ?></a></li>
							<li><a href="<?php echo $rank1?>" <?php if ($rank_id == 1) echo 'class="active"'?>><?php echo _('Hot'); ?></a></li>
						</ul>							
					</div>	
					<div class="btn btn-default" ><a href="<?php echo self::url('album', 'index') ?>" data-toggle="tooltip" data-placement="bottom"  data-original-title="<?php echo _('Explore'); ?>"><i class="demo-icon icon-icon_album-01"></i></a></div>
					<div class="btn btn-default"><a href="<?php echo self::url('template', 'index') ?>" data-toggle="tooltip" data-placement="bottom"  data-original-title="<?php echo _('Create'); ?>"><i class="demo-icon icon-icon_start-01"></i></a></div>	
					<div class="btn active"><a href="javascript:void(0)" data-toggle="tooltip" data-placement="bottom"  data-original-title="<?php echo _('職人專區'); ?>"><i class="demo-icon icon-icon_creator-01"></i></a></div>			
				</div>
			</div>
		</div>			
		
		<div class="water_content " id="freewall">
			<?php 
			if(!empty($creator)) {
				foreach($creator as $k0 => $v0) {
					echo '<div class="item_box" style="opacity:0;">
					<a href="'.$v0['cover_url'].'">
						<div class="user_face"><img src="'.$v0['picture'].'" onerror="this.onerror=null; this.src=\''.static_file('images/face_sample.svg').'\'"></div>
					</a>
					<div class="item_info">
						<div class="info_name">
							<h3 class="user_name"> <a href="'.$v0['cover_url'].'">'.$v0['name'].'</a></h3>
						</div>
						<div class="user_number">
							<p><i class="fa fa-eye"></i>'.$v0['viewed'].'</p>
							<p><i><img src="'.static_file('images/icon_pin.svg"').'" onerror="this.onerror=null; this.src=\''.static_file('images/pin.png').'\'"></i>'.$v0['follow'].'</p>
						</div>
						<div class="line color0'.$v0['creative_belong'].'"></div>
					</div>
				</div>';
				}
			}
			if (!empty($more)) echo '<div style="display:none;" class="more"><a href="'.$more.'"></a></div>'
			?>			
		</div>
	</div>
</div>

</div>
<script type="text/javascript">
function name_more_slice(obj) {var divH = $(obj).height(),$p = $("p", $(obj)).eq(0),str = $p.text();if ($p.outerHeight() > divH) {$p.text( str.slice(0, 70)+'...' );};}
$(document).ready(function() {
	var owl = $(".fotorama");
	owl.owlCarousel({
		singleItem:true,
		autoPlay : 3000,
		stopOnHover : true,
		autoHeight : true,
	});
	owl.trigger('owl.jumpTo', 0);
	
	// if($(window).width()<1024){
	// 	$(".mobile_banner").owlCarousel({
	// 		singleItem:true,
	// 		autoPlay : 5000,
	// 		stopOnHover : true,
	// 		autoHeight : true,
	// 	})  	
	// }
	
	$(window).resize(function(){
		if($(window).width()<1024){
			$(".mobile_banner").show();
				$(".mobile_banner").owlCarousel({
					singleItem:true,
					autoPlay : 5000,
					stopOnHover : true,
					autoHeight : true,
				})
			}else{$(".mobile_banner").hide()}
	})

	var $container = $('.water_content');
	$container.imagesLoaded(function(){
		$container.masonry({
			itemSelector: '.item_box',
			columnWidth: '.item_box',
			gutter: 15,
		});
		$('div.item_box').animate({ opacity: 1 });
	});
	
	$container.infinitescroll({
		navSelector  : '.more',
		nextSelector : '.more a',
		itemSelector : '.item_box',
		pathParse: function (path, nextPage) {
			var customPath = path + "&page=";
			path = [customPath, ''];
			return path;
		},
		//If no more content, response here
		errorCallback: function() {$('div.end').css('display', 'block')},
	},function( newElements ) {
		var $newElems = $( newElements ).css({ opacity: 0 });
		$newElems.imagesLoaded(function(){
			$newElems.animate({ opacity: 1 });
			$container.masonry( 'appended', $newElems, true );
		});		
		$(".name_more").each(function(i) {name_more_slice($(this));});
	});		
	
	
	//控制溢出文字加"..."
	$(".name_more").each(function(i) {name_more_slice($(this));});
});	
</script>