<div id="album_content">
	<h2><?php echo _('Member Center'); ?></h2>
	<ul>
		<li><?php include 'member_nav.phtml';?></li>
		<li>
			<div id="album_item">
				<div id="tem_content" >
					<div id="rescuit_in">
						<ul>
							<li>
								<div id="tab-container" class="tab-container">
									<ul class='etabs'>
										<!-- <li class="<?php echo $creative['applyfor']['personal'] ?>"><a id="personal" href="#tab01"><?php echo _('Individual'); ?></a></li>
										<li class="<?php echo $creative['applyfor']['company'] ?>"><a id="company" href="#tab02"><?php echo _('Company'); ?></a></li> -->
									</ul>
									<div  class="tab_content">
										<div id="tab01" class="tab <?php echo $creative['applyfor']['personal'] ?>">	
											<ul>
												<li><h2><?php echo _('匯款資料變更'); ?></h2></li>
												<li><div class="line"></div></li>
												<li>
													<form id="personal_form" class="form-horizontal">
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Email'); ?></label>
															<div class="controls">
																<input type="text" name="personal_email" required value="<?php echo $creative['personal_email']; ?>">
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Country'); ?></label>
															<div class="controls">
																<select id="personal_country" required>
																	<option value="">--<?php echo _('Country'); ?>--</option>
																	<option <?php echo ($creative['personal_country'] =='TW') ? 'selected="selected"' : null ; ?> value="TW"><?php echo _('Taiwan'); ?></option>
																	<option <?php echo ($creative['personal_country'] =='CN') ? 'selected="selected"' : null ; ?>value="CN"><?php echo _('China'); ?></option>
																	<option <?php echo ($creative['personal_country'] =='JP') ? 'selected="selected"' : null ; ?>value="JP"><?php echo _('Japan'); ?></option>
																</select>
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Zip code'); ?></label>
															<div class="controls">
																<input type="text" maxlength="5" name="personal_zipcode" required placeholder="<?php echo _('Zip code'); ?>" class="web_url" value="<?php echo $creative['personal_zipcode'] ?>">
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Contact address'); ?></label>
															<div class="controls">
																<input type="text" name="personal_address" required placeholder="<?php echo _('Contact address'); ?>" value="<?php echo $creative['personal_address'] ?>">
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" name="personal_career" for="inputEmail"><?php echo _('Job'); ?></label>
															<div class="controls">
																<select id="personal_job" required>
																	<option value="">--<?php echo _('Job'); ?>--</option>
																	<?php
																	foreach ($career as $v0) {
																		echo '<option value="'.$v0['value'].'">'.$v0['text'].'</option>';
																	}
																	?>
																</select>
															</div>
														</div>
														<div class="control-group" style="display: none;">
															<label class="control-label" for="inputEmail"><?php echo _('Personal website'); ?></label>
															<div class="controls">
																<input name="personal_website" type="text" placeholder="<?php echo _('Personal website'); ?>"  value="<?php echo $creative['personal_website'] ?>">
															</div>
														</div>

														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('ID No.'); ?></label>
															<div class="controls">
																<input name="personal_idcardnumber" type="password" required placeholder="<?php echo _('ID No.'); ?>"  value="<?php echo $creative['personal_idcardnumber'] ?>" style="width:93%;">
																<a href="javascript:void(0)" class="eye_unencryp"><i class="fa fa-eye" aria-hidden="true"></i></a>
															</div>
														</div>

														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Unicode'); ?></label>
															<div class="controls">
																<input type="text" name="company_vatnumber" id="inputEmail" placeholder="<?php echo _('Unicode'); ?>" value="<?php echo $creative['company_vatnumber']; ?>">
															</div>
														</div>
														<input type="submit" style="display:none;" id="personal_apply">
													</form>
												</li>
											</ul>
										</div>
										<div id="tab02" class="tab <?php echo $creative['applyfor']['company'] ?>">
											<ul>
												<li><h2><?php echo _('Company'); ?></h2></li>
												<li><div class="line"></div></li>
												<li>
													<form id="company_form" class="form-horizontal">
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Email'); ?></label>
															<div class="controls">
																<input type="text" name="company_email" required value="<?php echo $creative['company_email']; ?>">
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Country'); ?></label>
															<div class="controls">
																<select id="company_country" required>
																	<option value="">--<?php echo _('Country'); ?>--</option>
																	<option <?php echo ($creative['company_country'] =='TW') ? 'selected="selected"' : null ; ?> value="TW"><?php echo _('Taiwan'); ?></option>
																	<option <?php echo ($creative['company_country'] =='CN') ? 'selected="selected"' : null ; ?> value="CN"><?php echo _('China'); ?></option>
																	<option <?php echo ($creative['company_country'] =='JP') ? 'selected="selected"' : null ; ?> value="JP"><?php echo _('Japan'); ?></option>
																</select>
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Name of the Company(Chinese)'); ?></label>
															<div class="controls">
																<input type="text" name="company_name_zh_TW" id="inputEmail" required placeholder="<?php echo _('Name of the Company(Chinese)'); ?>" value="<?php echo $creative['company_name_zh_TW']; ?>">
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Name of the Company(English)'); ?></label>
															<div class="controls">
																<input type="text" name="company_name_en_US" id="inputEmail" required placeholder="<?php echo _('Name of the Company(Chinese)'); ?>" value="<?php echo $creative['company_name_en_US']; ?>">
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Unicode'); ?></label>
															<div class="controls">
																<input type="text" name="company_vatnumber" id="inputEmail" required placeholder="<?php echo _('Unicode'); ?>" value="<?php echo $creative['company_vatnumber']; ?>">
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Tel'); ?></label>
															<div class="controls">
																<input type="text" name="company_telephone" id="inputEmail" required placeholder="<?php echo _('Tel'); ?>" value="<?php echo $creative['company_telephone']; ?>">
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Zip code'); ?></label>
															<div class="controls">
																<input type="text" name="company_zipcode" id="inputEmail" required placeholder="<?php echo _('Zip code'); ?>" class="web_url" value="<?php echo $creative['company_zipcode']; ?>">
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Add'); ?></label>
															<div class="controls">
																<input type="text" name="company_address" id="inputEmail" required placeholder="<?php echo _('Add'); ?>" value="<?php echo $creative['company_address']; ?>">
															</div>
														</div>
														<div class="control-group">
															<label class="control-label" for="inputEmail"><?php echo _('Official Website'); ?></label>
															<div class="controls">
																<input type="text" name="company_website" id="inputEmail"  placeholder="<?php echo _('Official Website'); ?>" value="<?php echo $creative['company_website']; ?>">
															</div>
														</div>
														<input type="submit" style="display:none;" id="company_apply">
													</form>
												</li>
											</ul>
										</div>
									</div>
								</div>
							</li>
							<li>
								<form class="form-horizontal">
									<div class="control-group">
										<label class="control-label" for="inputEmail"><?php echo _('Remittance Method'); ?></label>
										<div class="controls">
											<select id="pay_option">
												<option value="">--<?php echo _('Please select country of residence'); ?>--</option>
											</select>
										</div>
									</div>
									<div id="form1" class="box pay1" style="display: none;">
										<div class="pay_info">
											<a href="https://www.paypal.com/">Paypal</a>, <?php echo _('A safer and easier trade payment platform across countries.'); ?><br>
											<?php '<a href="javascript:void(0)">Paypal</a>'._('helps you pay and receive cost of purchase from 203 countries throughout the world.'); ?><br>
											<?php '<a href="javascript:void(0)">Paypal</a>'._('safeguards all buyers’ transaction that is considered qualified.'); ?>
										</div>
										<div class="control-group" >
											<label class="control-label" for="inputEmail"><?php echo _('Paypal account'); ?></label>
											<div class="controls">
												<input type="text" name="paypal_account" placeholder="<?php echo _('Paypal account'); ?>" value="<?php echo $creative['remittance']['remittance_info']['paypal_account'] ?>">
											</div>
										</div>
										<div class="control-group" >
											<label class="control-label" for="inputEmail"><?php echo _('Currency for payment'); ?></label>
											<div class="controls">
												<select id="paypal_currency">
													<option value="">--<?php echo _('Currency for payment'); ?>--</option>
													<?php
													foreach (json_decode(Core::settings('CURRENCY'), true) as $k0 => $v0) {
														if($k0 == $creative['remittance']['remittance_info']['paypal_currency']) {
															echo '<option selected="selected" value="'.$k0.'">'.$v0.'</option>';
														} else {
															echo '<option value="'.$k0.'">'.$v0.'</option>';
														}
														
													}
													?>
												</select>
											</div>
										</div>
									</div>
									<div id="form2" class="box pay2" style="display: none;">
										<div class="pay_info">
											<?php echo _('If you have other more suitable methods, please fill in the information required in the box below'); ?><br>
											<?php echo _('To let Pinpinbox know more about your needs, make sure that the filled-in information is correct, or you will be unable to receive the benefits!'); ?>
										</div>
										<div class="control-group" >
											<label class="control-label" for="inputEmail"><?php echo _('Account Name'); ?></label>
											<div class="controls">
												<input name="name" type="text" placeholder="<?php echo _('Account Name'); ?>" value="<?php echo $creative['remittance']['remittance_info']['name'] ?>">
											</div>
										</div>
										<div class="control-group" >
											<label class="control-label" for="inputEmail"><?php echo _('Bank '); ?></label>
											<div class="controls">
												<input name="bank" type="password" placeholder="<?php echo _('Bank '); ?>" class="web_url" value="<?php echo $creative['remittance']['remittance_info']['bank'] ?>" style="width:93%;">
												<a href="javascript:void(0)" class="eye_unencryp"><i class="fa fa-eye" aria-hidden="true"></i></a>
											</div>
										</div>
										<div class="control-group" >
											<label class="control-label" for="inputEmail"><?php echo _('Branch'); ?></label>
											<div class="controls">
												<input name="branch" type="text" placeholder="<?php echo _('Branch'); ?>" class="web_url" value="<?php echo $creative['remittance']['remittance_info']['branch'] ?>">
											</div>
										</div>
										<div class="control-group" >
											<label class="control-label" for="inputEmail"><?php echo _('Account No.'); ?></label>
											<div class="controls">
												<input name="account" type="password" placeholder="<?php echo _('Account No.'); ?>" value="<?php echo $creative['remittance']['remittance_info']['account'] ?>" style="width:93%;">
												<a href="javascript:void(0)" class="eye_unencryp"><i class="fa fa-eye" aria-hidden="true"></i></a>
											</div>
										</div>
										<div class="control-group" >
											<label class="control-label" for="inputEmail"><?php echo _('Remarks'); ?></label>
											<div class="controls">
												<textarea name="remark" rows="3"><?php echo $creative['remittance']['remittance_info']['remark'] ?></textarea>
											</div>
										</div>
									</div>	
								</form>
							</li>
							<li style="width:35%; margin:0 auto;" class="textcenter"><div id="slider"></div><p><?php echo _('Slide the lever to verify.'); ?></p></li>
							<li class="textcenter"><label class="checkbox"><?php echo _('submit means that you have read and accept the ').'<a target="_blank" href="'.self::url('index', 'terms').'">'._('specifications').'</a>'._(' and ').'<a target="_blank" href="'.self::url('index', 'privacy').'">'._('Privacy statement').'</a>';?></label></li>
						</ul>
					</div>
					<ul>
						<li><a class="used" onclick="_submit()" href="javascript:void(0)"><?php echo _('Submit'); ?></a></li>
					</ul>
				</div>
			</div>
		</li>
	</ul>
</div>
<script>
$("#personal_job").children().each(function(){
    if ($(this).val()== '<?php echo $creative['personal_career'] ?>'){ $(this).attr("selected", "true");  }
});

function _submit() {
	if ($('#slider').slider('value') != <?php echo $max?>) {
		r = {'data': 'Modal', 'message': '<?php echo _('Slide the lever to verify.')?>'};
		var siteModal = new jBox(r.data, {
			title: '<span style="display: inline-block;height: 100%;vertical-align: middle;"></span><img style="vertical-align: middle;" src="<?php echo static_file('images/info.png')?>">',
			maxWidth: 600,
			minWidth: 100,
		}).setContent(r.message).open();
		return;
	}
	
	$('#personal_apply').trigger('click');
}

$(function(){
	
	$('#slider').slider({
		animate: true,
		max: <?php echo $max?>,
		stop: function(event, ui) {
			if (ui.value == <?php echo $max?>) {
				$(this).slider('disable').next('p').css({'color': 'green'}).text('<?php echo _('Authentication passed'); ?>');
			} else {
				$(this).find('a').animate({'left': 0});
			}
		}
	});

	$('#pay_option').on('change', function() {
		$('.box').hide();
		switch ($(this).val()) {
			case 'paypal':
				$('.pay1').show();
				break;

			case 'other':
				$('.pay2').show();
				break;
		}
	});
	
	//country select => pay option
	$('#personal_country, #company_country').on('change', function() {	
		$('#pay_option').find('option').remove();
		$('.pay1').hide();$('.pay2').hide();
		
		var option = [];
		option.push('<option value="">--<?php echo _('Remittance Method'); ?>--</option>');
		option.push('<option value="paypal"><?php echo _('Paypal'); ?></option>');
		option.push('<option value="other"><?php echo _('Others'); ?></option>');
		option.push('<option value="">--<?php echo _('Please select country of residence'); ?>--</option>');
		
		switch ($(this).val()) {
			case 'TW':
				$('#pay_option').append(option[0],option[1],option[2]);
				$('input[name="personal_idcardnumber"]').removeAttr('disabled');
				$('input[name="company_vatnumber"]').removeAttr('disabled');
				break;

			case 'CN':
			case 'JP':
				$('#pay_option').append(option[0],option[1]);
				$('input[name="personal_idcardnumber"]').attr('disabled', 'true');
				$('input[name="company_vatnumber"]').attr('disabled', 'true');
				break;
			
			default:
				$('#pay_option').append(option[3]);
				break;
		}
	});
	
	<?php
		if ($creative['applyfor']['personal'] == null) {
			echo '$(\'#company_country\').val(\''.$creative['company_country'].'\').trigger(\'change\');';
			echo '$("#tab01").hide();';
		}

		if ($creative['applyfor']['company'] == null) {
			echo '$(\'#personal_country\').val(\''.$creative['personal_country'].'\').trigger(\'change\');';
			echo '$("#tab02").hide();';
		}
	?>
	
	$('#pay_option').val('<?php echo $creative['remittance']['remittance']; ?>').trigger('change');

	$('#personal_form').validate({
		rules: {},
		submitHandler: function() {
			$('.apply').hide().next('img').show();
			$.post('<?php echo self::url('user', 'creative_edit')?>', {
				apply: 'personal',
				personal_email: $('input[name=personal_email]').val(),
				personal_country: $('#personal_country :selected').val(),
				personal_zipcode: $('input[name=personal_zipcode]').val(),
				personal_address: $('input[name=personal_address]').val(),
				personal_career: $('#personal_job :selected').val(),
				personal_website: $('input[name=personal_website]').val(),
				personal_idcardnumber: ($('#personal_country :selected').val() == 'TW') ? personal_idcardnumber = $('input[name=personal_idcardnumber]').val() : '' ,
				company_vatnumber:  ($('#personal_country :selected').val() == 'TW') ? company_vatnumber = $('input[name=company_vatnumber]').val() : '',
				remittance :$("#pay_option").val(),
				paypal_account : $('input[name=paypal_account]').val(),
				paypal_currency : $('#paypal_currency :selected').val(),
				name : $('input[name=name]').val(),
				bank : $('input[name=bank]').val(),
				branch : $('input[name=branch]').val(),
				account : $('input[name=account]').val(),
				remark : $('[name=remark]').val(),
				captcha: $('#slider').slider('value'),
			}, function(r) {
				r = $.parseJSON(r);
				if (r.result == 1) {
					_jBox(r, 'success_notext');
				} else {
					_jBox(r, 'error');
				}
				$('.apply').show().next('img').hide();
			});
		}
	});	
	
	$('#company_form').validate({
		rules: {},
		submitHandler: function() {
			$('.apply').hide().next('img').show();
			
			$.post('<?php echo self::url('user', 'creative_edit')?>', {
				apply: 'company',
				company_email: $('input[name=company_email]').val(),
				company_country: $('#company_country :selected').val(),
				company_name_zh_TW: $('input[name=company_name_zh_TW]').val(),
				company_name_en_US: $('input[name=company_name_en_US]').val(),
				company_vatnumber:  ($('#company_country :selected').val() == 'TW') ? company_vatnumber = $('input[name=company_vatnumber]').val() : '',
				company_telephone: $('input[name=company_telephone]').val(),
				company_zipcode: $('input[name=company_zipcode]').val(),
				company_address: $('input[name=company_address]').val(),
				company_website: $('input[name=company_website]').val(),
				remittance :$("#pay_option").val(),
				paypal_account : $('input[name=paypal_account]').val(),
				paypal_currency : $('#paypal_currency :selected').val(),
				name : $('input[name=name]').val(),
				bank : $('input[name=bank]').val(),
				branch : $('input[name=branch]').val(),
				account : $('input[name=account]').val(),
				remark : $('[name=remark]').val(),
				captcha: $('#slider').slider('value'),				
			}, function(r) {
				r = $.parseJSON(r);
				if (r.result == 1) {
					_jBox(r, 'success_notext');
				} else {
					_jBox(r, 'error');
				}
				$('.apply').show().next('img').hide();
			});
		}
	});
	
	$('.loading_img').hide();

	$('.eye_unencryp').on('mousedown', function(){
		$(this).prev('input').attr('type', 'text');
	}).on('mouseup', function(){
		$(this).prev('input').attr('type', 'password');
	})
});
</script>