	<!-- 內容頁開始 -->
		<div id="album_content">
			<h2><?php echo _('Member Center'); ?></h2>
			<ul>
				<li class="mobiledisplay"><h3><?php echo _('Fees'); ?></h3></li>
				<li class="mobiledisplay"><div class="line"></div></li>
				<li class="mobile_open02">
					<a href="<?php echo self::url('user', 'order') ?>" ><?php echo _('Purchasing history query'); ?></a>
					<a href="javascript:void(0)" class="active"><?php echo _('P Point consumption query'); ?></a>
				</li>

				<li>
					<?php include 'member_nav.phtml';?>
					<div id="memberbox_item">
						<div id="album_tab">
							<h3><?php echo _('Fees'); ?></h3>
						</div>
						<div class="album_info">
							<ul>
								<li>
									<a href="<?php echo self::url('user', 'order') ?>"><p class="title"><?php echo _('Purchasing history query'); ?></p></a>
								</li>
								<li>
									<a href="<?php echo self::url('user', 'exchange') ?>"><p class="title active"><?php echo _('P Point consumption query'); ?></p></a>
								</li>
							</ul>
						</div>
						<div class="album_all">
							<div id="table_box">
							   <table class="footable" data-limit-navigation="5" data-page-size="10">
					                <thead>
						                <tr>
						                    <th>
						                        <?php echo _('Date of consumption'); ?>
						                    </th>
						                    <th data-hide="phone">
						                        <?php echo _('Previous P Point balance'); ?>
						                    </th>
						                    <th >
						                        <?php echo _('Sum of P Point consumption'); ?>
						                    </th>
						                    <th data-hide="phone,tablet">
						                        <?php echo _('Details'); ?>
						                    </th>
						                    <th data-hide="phone">
						                        <?php echo _('P point balance after consumption'); ?>
						                    </th>
						                </tr>
					                </thead>
									<?php 
									if(!empty($exchange)){
										foreach($exchange as $k => $v){
											echo '<tbody>
												<tr>
													<td>'.$v['inserttime'].'</td>
													<td>'.$v['point_before_total'].'</td>
													<td>'.$v['point'].'</td>
													<td>'.$v['memo'].'</td>
													<td>'.$v['surplus'].'</td>
												</tr>
											</tbody>';
										}
									}
									?>
					                <tfoot>
						                <tr>
						                    <td colspan="5">
						                        <div class="pagination pagination-centered"></div>
						                    </td>
						                </tr>
					                </tfoot>					               
					            </table>								
							</div>
						</div>
					</div>					
				</li>
			</ul>
		</div>
<script type="text/javascript">
$(function(){
	$('table').bind('footable_breakpoint', function(){
		$('table').trigger('footable_expand_first_row');
	}).footable();
});
</script>