<!-- 內容頁開始 -->
	<div id="album_content">
		<h2><?php echo _('Member Center'); ?></h2>
		<ul>
			<li>
				<?php include ('member_nav.phtml') ;?>
			</li>
			<li>
				<div id="album_item">
					<div id="tem_content" >
						<div id="memset_info">
							<ul>
								<form id="js_user_password_form">
									<li><div class="sett_title"><?php echo _('Password changed'); ?></div></li>
									<li>
										<div class="tdtitle"><?php echo _('Current'); ?></div>
										<div class="tdtxt"><input type="password" name="old_pass"></div>		
									</li>
									<li>
										<div class="tdtitle"><?php echo _('New'); ?></div>
										<div class="tdtxt"><input type="password" name="new_pass"></div>		
									</li>
									<li>
										<div class="tdtitle"><?php echo _('Retype New'); ?></div>
										<div class="tdtxt"><input type="password" name="new_pass_check"></div>		
									</li>
									<li><a href="javascript:void(0)" class="used" onclick="$('#js_user_password').trigger('click')"><?php echo _('Done editing'); ?></a></li>			
									<img style="width:20px;height:20px;display:block; margin:auto; display:none;" class="loading_img " src="<?php echo static_file('images/loading.gif')?>">
									<input style="display:none;" id="js_user_password" type="submit"> <!-- ajax驗證用submit -->
								</form>
							</ul>
						</div>
					</div>
				</div>
			</li>
		</ul>
	</div>
<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<script type="text/javascript">
$(function(){
	$('.loading_img').css('display', 'none');
// 驗證表單按下submit事件 0217
	$('#js_user_password_form').validate({
		rules: {},
		submitHandler: function() {
			$('.loading_img').css('display', 'block');
			$('.loading_img').prev('li').css('display', 'none');
			$.post('<?php echo self::url('user', 'password') ;?>', {
				old_pass: $('input[name="old_pass"]').val(),
				new_pass: $('input[name="new_pass"]').val(),
				new_pass_check: $('input[name="new_pass_check"]').val()
			}, function(r) {
				$('.loading_img').css('display', 'none');
				$('.loading_img').prev('li').css('display', 'block');
				r = $.parseJSON(r);
				if (r.result == 1) {
					$('input[type=password]').each( function () {
						$(this).val('');
					});
					siteModal=new jBox('Modal' ,{ onCloseComplete: function() {if (r.redirect) location.href = r.redirect;}});
					siteModal.setContent("<img src=\"<?php echo static_file('images/success.png'); ?>\">&nbsp;"+r.message).open();
				} else {
					site_jBox(r,'error');
				}				
			});
		}
	});
});

</script>