<!-- 內容頁開始 -->
<div id="album_content">
	<h2><?php echo _('Member Center'); ?></h2>
	<ul>
		<li class="mobiledisplay"><h3><?php echo _('Buy P Points'); ?></h3></li>
		<li class="mobiledisplay"><div class="line"></div></li>
		<li>
			<?php include 'member_nav.phtml';?>
			<div id="memberbox_item">
				<div id="album_tab"><h3><?php echo _('Buy P Points'); ?></h3></div>
				<div class="album_all">
					<div id="point_content">
						<div class="point_info"><?php echo _('Balance of P Point'); ?><img src="<?php echo static_file('images/point.png')?>" height="30" width="30"><span class="green"><?php echo $point?> P <?php echo _('Point'); ?></span></div>
						<?php
						foreach ($buy as $v0) {
							echo '
							<div class="point_list" data-buy_id="'.$v0['buy_id'].'" data-assets="'.$v0['assets'].'" data-assets_item="'.$v0['assets_item'].'" data-total="'.$v0['total'].'" data-currency="'.$v0['currency'].'" data-obtain="'.$v0['obtain'].'">
								<div class="choose"><img src="'.static_file('images/wh_select.png').'" height="20" width="30" alt=""></div>
								<!--<div class="point_count"><p>SAVE 0%</p></div>-->
								<ul>
									<li><img src="'.static_file('images/point.png').'" height="30" width="30" alt=""><span>'.$v0['obtain'].' P '._('Point').'</span></li>
									<li>NT$'.$v0['total'].'</li>
								</ul>
							</div>
							';
						}
						?>
						<div style="clear:both"></div>
					</div>
				</div>
			</div>					
		</li>
	</ul>
</div>

<input type="hidden" id="buy_id" name="buy_id">
<input type="hidden" id="assets" name="assets">
<input type="hidden" id="assets_item" name="assets_item">
<input type="hidden" id="total" name="total">
<input type="hidden" id="currency" name="currency">
<input type="hidden" id="obtain" name="obtain">
<div id="cashflow"></div>			

<script>
$(function(){
	$('.point_list').on('click', function() {
		var that = $(this);
		that.addClass('active').siblings().removeClass('active');
		['buy_id', 'assets', 'assets_item', 'total', 'currency', 'obtain'].forEach(function(entry) {
		    $('#' + entry).val(that.data(entry));
		});

		buy();
	});
});

function buy() {
	if (!$('#total').val() || !$('#obtain').val()) {
		r = {'message': '<?php echo _('Please choose one item on sale.')?>'};
		site_jBox(r);
		return;
	}
	
	var total = $('#total').val(), obtain = $('#obtain').val();
	
	var siteConfirm = new jBox('Confirm', {
		cancelButton: '<?php echo _('No')?>',
		confirm: function() {
			$.post('<?php echo self::url('user', 'point')?>', {
				buy_id: $('#buy_id').val(),
				assets: $('#assets').val(),
				assets_item: $('#assets_item').val(),
				total: parseInt(String(total).replace(/\,/g, ''), 10),
				currency: $('#currency').val(),
				obtain: parseInt(String(obtain).replace(/\,/g, ''), 10),
                redirectAlbumId : '<?php echo $redirectAlbumId ?>',
			}, function(r) {
				r = $.parseJSON(r);
				if (1 == r.result) {
					window.onbeforeunload = null;
					$('#cashflow').html(r.data).find('form').submit().remove();
				} else if (2 == r.result) {
					site_jBox(r);
				} else {
					site_jBox(r, 'error');
				}
			});
		},
		confirmButton: '<?php echo _('Yes')?>',
		onCloseComplete: function() {
			siteConfirm.destroy();
		}
	}).setContent(
		'<div class="content">' +
		'<?php echo _('P Point')?>:&nbsp;<span class="red">' + obtain + '</span><br>' +
		'<?php echo _('Total')?>:&nbsp;<span class="red">NT$' + total + '</span><br><br>' +
		'<?php echo _('System will guide you to the online trading page, are you sure?').'<br><br><span class="keypoint">※'._('Attention').'※<br>'._('P points cannot be used across platforms given the platform policies. If P points are purchased using the').'<span class="red">web</span>(apple/google/web)'._('as platform, you can use the pinpinbox webpage.').'</span>'?>' +
		// '<?php echo _('System will guide you to the online trading page, are you sure?').'<br><br><span class="keypoint">※'._('Attention').'※<br>'._('You purchase P point belongs platform of').' <span class="red">web</span>(apple/google/web)'._(', ')._('P point cannot be cross-platform use')._('.').'</span>'?>' +
		'</div>'
	).open();
}
</script>