<?php echo $form?>
<script>
$(function(){
	$('#form').validate({
		rules: {},
		submitHandler: function() {
			$.post('<?php echo $action?>', {
				<?php if ('edit' == $_GET['act']) {?>
				<?php echo M_CLASS?>_id: $('#<?php echo M_CLASS?>_id').val(),
				<?php }?>
				state: $('input[name="state"]:checked').val(),
			}, function(r) {
				r = $.parseJSON(r);
				switch (r.result) {
					case 0:formerror(r.message);break;
					case 1:formconfirm(r);break;
				}
			});
		}
	});

	<?php if ('edit' == $_GET['act']) {?>
    $('#grid').kendoGrid({
		columns: [
  			{field: 'settlement_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{
				title: 'user',
				columns: [
					{field: 'user_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
					{title: '@info', field: 'userX', attributes: {'class': 'string'}, encoded: false, filterable: false, sortable: false}
				]
			},
			{
				title: 'income',
				columns: [
					{field: 'income_id', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
					{title: '@info', field: 'incomeX', attributes: {'class': 'string'}, encoded: false, filterable: false, sortable: false}
				]
			},
			{field: 'point_album', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{field: 'point_template', attributes: {'class': 'number'}, filterable: {ui: function(e){e.kendoNumericTextBox({format: 'n0'});}}},
			{field: 'starttime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
			{field: 'endtime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
			{field: 'state', attributes: {'class': 'enums state-#:state#'}},
			{field: 'modifytime', attributes: {'class': 'date'}, filterable: {ui: function(e){e.kendoDateTimePicker({format: 'yyyy-MM-dd HH:mm:ss'});}}},
			{
				title: 'exchange',
				columns: [
					{title: '@count', field: 'exchangeX', attributes: {'class': 'number'}, filterable: false, sortable: false}
				]
			},
		],
		dataBinding: function(e) {},
		dataBound: function(e) {},
        dataSource: new kendo.data.DataSource({
        	filter: {field: '<?php echo M_CLASS?>_id', operator: 'eq', value: <?php echo $income_id?>},
    		page: 1,
    		pageSize: gridpageSize,
    		schema: {
    			data: function(r){return r.data;},
    			total: function(r){return r.total;}
    		},
    		serverPaging: true,
    		serverSorting: true,
    		serverFiltering: true,
    		sort: {field: 'modifytime', dir: 'desc'},
    		transport: {
    			read: {
    				data: {'case': 'settlement'},
    				dataType: 'json', //"jsonp" is required for cross-domain requests; use "json" for same-domain requests
    				type: 'POST',
    				url: '<?php echo self::url(M_CLASS, 'json')?>',
    			}
    		},
    	}),
        filterable: true,
        pageable: {
            refresh: true,
            input: true,
            pageSize: gridpageSize,
            pageSizes: gridpageSizes,
        },
        reorderable: true,
        resizable: true,
        selectable: true,
        sortable: true,
		toolbar: [
			{template: '<a class="k-button" onclick="grid_toolbar_edit(\'\\#grid\', \'<?php echo self::url('settlement', 'form', array('act'=>'edit'))?>\', [\'settlement_id\'])"><span class="k-icon k-i-pencil"></span></a>'},
		],
    });
	<?php }?>
});
</script>