<?php echo $form?>
<script>
$(function(){
	$('#form').validate({
		rules: {},
		submitHandler: function() {
			$.post('<?php echo $action?>', {
				<?php if ('edit' == $_GET['act']) {?>
				<?php echo M_CLASS?>_id: $('#<?php echo M_CLASS?>_id').val(),
				<?php }?>
				account: $('#account').val(),
				password: $('#password').val(),
				repassword: $('#repassword').val(),
				name: $('#name').val(),
				telphone: $('#telphone').val(),
				address: $('#address').val(),
				vatnumber: $('#vatnumber').val(),
				title: $('#title').val(),
				description: CKEDITOR.instances['description'].getData(),
				image: $('#image').val(),
				sequence: $('#sequence').val(),
				act: $('input[name="act"]:checked').val()
			}, function(r) {
				r = $.parseJSON(r);
				switch (r.result) {
					case 0:formerror(r.message);break;
					case 1:formconfirm(r);break;
				}
			});
		}
	});
});
</script>