<!doctype html>
<html lang="en">
<head>
<link rel="icon" type="image/vnd.microsoft.icon" href="<?php echo static_file('images/favicon.ico')?>" />
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?php echo Core::settings('SITE_TITLE')?></title>
</head>
<body>
<?php echo Core::settings('GOOGLE_ANALYTICS_TRACKINGCODE')?>
<img src="<?php echo static_file('images/maintain.jpg')?>" style="display: block; margin-left: auto; margin-right: auto;">
</body>
</html>